Lib9c/Model/Quest/ItemEnhancementQuest.cs
Lib9c/Model/Quest/Quest.cs

The usage of property `Goal` in `ItemEnhancementQuest` class is different from super class `Quest`, so the derived `Progress` property was not working as intended.
So, I've made `Progress` property `virtual`, and implemented properly in `ItemEnhancementQuest`.

Fix bug in `Progress` property in `ItemEnhancementQuest`.

---

Lib9c/Action/ActionBase.cs
Lib9c/Lib9c.csproj

This PR is continued from #19 . 
It changes the internal serialization layout from `(FAV.MajorUnit, FAV.MinorUnit)` to `FAV.RawValue`.

Replace (FAV.MajorUnit, FAV.MinorUnit) with FAV.RawValue

---

Lib9c/BlockPolicy.cs

Make` BlockPolicy.GetRenderer()` to return a concrete type (i.e., `ActionRenderer`) instead of an abstract type (`IRenderer<PolymorphicAction<ActionBase>>`), so that client code can subscribe its observables without downcasting to `ActionRenderer`.

Make BlockPolicy.GetRenderer() to return a concrete type

---

Lib9c/Action/Buy.cs

1. In the Buy action, the updated addresses between the rehearsal and the main run are different, so the TX is invalidated.

Fix bug/Not equal updated addresses in buy action

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
Lib9c/Action/ActionBase.cs

The title says it all. 
I haven't finished writing the unittest becuase `ActionBase.ActionEvaluation<T>` doesn't implement `IEquatable<T>`, so I left `FIXME` ther.

Fix serialization in ActionBase.ActionEvaluation

---

.Lib9c.Tests/Action/ActionContext.cs
Lib9c/Lib9c.csproj

To use Libplanet's [delayed renderers][1], upgrades it to 0.10.0-dev.20200904141108.
[1]: https://github.com/planetarium/libplanet/pull/980

Update Libplanet to 0.10.0-dev.20200904141108

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/BlockPolicySource.cs

According to this change, a `logger` should be given when creating `BlockPolicySource` instance. (i.e. `Log.Logger`, `Logger.None`)

Use LoggedRenderers

---

Lib9c/BlockPolicySource.cs

Since `LoggedActionRenderer` extends `LoggedRenderer`, duplicated logs were given in block related actions.

GetRenderer to return BlockRenderer instead of LoggedBlockRenderer

---

Lib9c/BlockHelper.cs

Since planetarium/libplanet#986, `stateRootHash` became a required field when using `TrieStateStore`. And it should pass block action to get the correct state root hash. If not, it will have an incorrect state root hash and the validation will fail. So this pull request makes it pass block action also.

Pass block action also into MineGenesisBlock

---

.Lib9c.Tests/Action/RendererTest.cs
Lib9c/Action/BlockRenderer.cs

Fixed a bug where `BlockRenderer.RenderReorgEnd()` did not update `ReorgEndSubject`.

RenderReorgEnd to update ReorgEndSubject

---

.Lib9c.Tests/Model/State/AvatarStateTest.cs
Lib9c/Action/Buy.cs
Lib9c/Action/CombinationConsumable.cs
Lib9c/Action/HackAndSlash.cs
Lib9c/Action/Sell.cs
Lib9c/Action/SellCancellation.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/RankingMapState.cs

Before this pull request, `AvatarState`'s constructor constructs a different state with different `updatedAt` for each call. This pull request fixes the problem by presenting it as an index of the block the state created and the state updated.

Make AvatarState deterministic

---

.github/workflows/publish.yml

It makes Lib9c available on NuGet and users can use Lib9c as a package.
You can see GitHub Actions logs and the package on NuGet.
https://github.com/moreal/lib9c/runs/1101605761?check_suite_focus=true
https://www.nuget.org/packages/Lib9c

Publish Lib9c to NuGet

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/BlockPolicy.cs
Lib9c/BlockPolicySource.cs

This change `GetNextBlockDifficulty` to use the minimum difficulty in blocks for authorized miners.

Use the minimum difficulty in blocks for authorized miners

---

Lib9c/BlockPolicySource.cs

In Libplanet, `Swarm<T>` doesn't fill chain states before `ActionExecutionState` phase. so we can't check tx's signer based on its state during preloading.
Therefore, this PR adds a workaround that ignoring `IncompleteBlockStatesException` in `IsSignerAuthorized` for this situation. but I guess it can be a sort of vulnerability... (or, it can be okay because we're protecting output states via `Block<T>.StateRootHash`)

Workaround for IncompleteBlockStatesException during signer check

---

.Lib9c.Tests/Model/State/WeeklyArenaStateTest.cs
Lib9c/Model/State/WeeklyArenaState.cs

- Consider the case where there is no `ArenaInfo` registered in the `WeeklyArenaState`.

Fix bug in WeeklyArenaState

---

.Lib9c.Tests/Model/ConsumableTest.cs
.Lib9c.Tests/Model/ItemUsableTest.cs
Lib9c/Action/DeleteAvatar.cs
Lib9c/Model/Item/Consumable.cs
Lib9c/Model/Item/Inventory.cs
Lib9c/Model/Item/ItemUsable.cs
Lib9c/Model/Mail/Mail.cs
Lib9c/Model/Quest/Quest.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/DeletedAvatarState.cs

- When serializing an object that implements `IState`, it sorts the List<T> fields that the object contains.
- Change type of `DeletedAvatarState.deletedAt` from `DateTimeOffset` to `long`.

Bug fix/make list deterministic

---

.Lib9c.Tests/Action/InitializeStatesTest.cs
.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/Action/InitializeStates.cs
Lib9c/BlockHelper.cs

This PR forces to keep `InitializeStates`'s fields as serialized to avoid unnecessary serialization.

Keep InitailizeStates's fields to serialized

---

.Lib9c.Tests/TableSheetsImporter.cs

- To make a fixture available in another repository using Lib9c as a submodule.

Make get fixture dir on TableSheetsImporter.ImportSheet

---

.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tests/Renderer/RendererTest.cs
Lib9c/Renderer/ActionRenderer.cs
Lib9c/Renderer/ValidatingActionRenderer.cs

Now compares actions rendered in renderer with actions in actual block that rendered at `ValidatingActionRenderer<T>.RenderBlockEnd()`. It became to take `IBlockPolicy` in its constructor.

Validate action render in `ValidatingActionRenderer<T>`

---

.Lib9c.Tools/Program.cs
.Lib9c.Tools/SubCommand/Genesis.cs
.Lib9c.Tools/SubCommand/Tx.cs

This PR adds `tx` sub-command to `Lib9c.Tools.exe` to enable users to create directly `TransferAsset` action and tx containing it.
```pwsh
PS C:\Users\X1E\electron-launcher\NineChronicles.Standalone\Lib9c\.Lib9c.Tools> dotnet run -- tx transfer-asset 9686661FDcf33Ce01aFF59a371bcdB7f748f7155 9686661FDcf33Ce01aFF59a371bcdB7f748f7155 1000 .\genesis-block-9c-beta-8-rc2
6c7531333a5472616e7366657241737365746475363a616d6f756e746c647531333a646563696d616c506c61636573313a0275373a6d696e746572736c32303a2de26698a6245f477dff4cfc0d172f9c070ea18d6575363a7469636b657275333a4e43476569313030303030656575393a726563697069656e7432303a9686661fdcf33ce01aff59a371bcdb7f748f715575363a73656e64657232303a9686661fdcf33ce01aff59a371bcdb7f748f71556565
PS C:\Users\X1E\electron-launcher\NineChronicles.Standalone\Lib9c\.Lib9c. …
```

Add tx sub-command to Lib9c.Tools.exe

---

.Lib9c.Tools/Lib9c.Tools.csproj
.Lib9c.Tools/SubCommand/Genesis.cs
Lib9c/BlockHelper.cs

This PR is a follow-up of #128 . it introduces `CreditsState` to `BlockHelper.MineGenesisBlock()`

Add creditsState to BlockHelper

---

.Lib9c.Tests/Action/RawState.cs
.Lib9c.Tests/JsonStatesLoader.cs
.Lib9c.Tests/JsonStatesLoaderTest.cs

You can export all states from the planet CLI feature (https://github.com/planetarium/libplanet/pull/1026).
And this pull request introduces a new `IAccountStateDelta` implementation and the JSON loader for the implementation.

Load state from json file fixture

---

Lib9c/Action/ActivateAccount.cs
Lib9c/BlockPolicySource.cs
Lib9c/Model/State/PendingActivationState.cs

This PR adds a filter for `BlockPolicy` to block txs containing illegal `ActivateAccount` action.

Filter illegal ActivateAccount on BlockPolicy

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/BlockHelper.cs
Lib9c/BlockPolicy.cs
Lib9c/BlockPolicySource.cs
Lib9c/InvalidTxCountException.cs

It checks number of transactions in blocks to append, reject if its count exceeds the maximum.

Reject blocks with too many transactions in BlockPolicy

---

.Lib9c.Tests/JsonStatesLoader.cs
.Lib9c.Tests/JsonStatesLoaderTest.cs
.Lib9c.Tests/Lib9c.Tests.csproj

There was an issue to resolve the path of the JSON file because of the Zio's file system abstraction policy. So I replaced it with `System.IO.Abstractions`. And I also fixed the problem that can't load states from JSON successfully.

fix: replace zio abstraction with another.

---

.github/workflows/main.yml
Lib9c.sln
Lib9c/Lib9c.csproj
Lib9c/Lib9c.ruleset
global.json

*(This should be merged after <https://github.com/planetarium/libplanet/pull/1034> is merged.)*
This applies *Libplanet.Analyzer.CSharp* to *Lib9c*.  With this analyzer, if we make a change like below:
```diff
diff --git a/Lib9c/Action/CreateAvatar.cs b/Lib9c/Action/CreateAvatar.cs
index 8931d6e..63dc575 100644
--- a/Lib9c/Action/CreateAvatar.cs
+++ b/Lib9c/Action/CreateAvatar.cs
@@ -81,10 +81,11 @@ namespace Nekoyume.Action
$"Aborted as the input name {name} does not follow the allowed name pattern.");
}
+            var r = new Random();
var sw = new Stopwatch();
sw.Start();
var started = DateTimeOffset.UtcNow;
-            Log.Debug("CreateAvatar exec started.");
+            Log.Debug($"CreateAvatar exec started. {r.Next()}");
AgentState existingAgentState = …
```

Apply Libplanet.Analyzers

---

.github/workflows/publish.yml

It was due to a change from a355f7899a07c497a0bc2ca87192c6638ded8c6c.

Fix a broken deployment job

---

.Lib9c.Tools/SubCommand/Genesis.cs
Lib9c/BlockHelper.cs

This PR adds `--private-key` option to `9c-tools genesis` to provide signer key for genesis block.

Add private-key option for 9c-tools genesis

---

Lib9c/Action/RewardGold.cs

This PR is the alternative of #170. it doesn't change the serialization format of `GoldDIstributions` but it only affects `RewardGold`'s semantic to support decimal amount. 
It assumes two hard-coded addresses (`F9A15F870701268Bd7bBeA6502eB15F4997f32f9` and `Fb90278C67f9b266eA309E6AE8463042f5461449`) that used for Nine Chronicles' closed beta testnet.

Scale GoldDistribution.AmountPerBlock for mainnet

---

.Lib9c.Tools.Tests/UtilsTest.cs
.Lib9c.Tools/Utils.cs

This PR makes that `CreateActivationKey()` runs in parallel to improve its performance

Parallize activation key creation

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/BlockPolicySource.cs

This PR makes that `BlockPolicy.DoesTransactionFollowsPolicy()` denies transactions signed by authorized miners.

Deny transactions from authorized miners

---

Lib9c/Model/State/RedeemCodeState.cs
Lib9c/TableData/RedeemCodeListSheet.cs

Made `RedeemCodeState` to avoid needless `PublicKey` instantiation, which is time expensive.
I am going to try to find the similar pattern in other areas like activation code.

Avoid needless PublicKey instantiation (which is time expensive)

---

.Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
Lib9c/Action/AccountStateDeltaExtensions.cs
Lib9c/Action/Buy.cs
Lib9c/Action/CombinationConsumable.cs
Lib9c/Action/HackAndSlash2.cs
Lib9c/Action/RankingBattle2.cs
Lib9c/Action/RedeemCode.cs

- Delete SetState with no changes.
- Use `TryGetAvatarState` instead of `TryGetAgentAvatarStates`.

Reduce GetState, SetState call count in IAction.Execute

---

.github/workflows/main.yml
Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
Lib9c.Benchmarks/Program.cs
Lib9c.sln
Lib9c/BlockPolicySource.cs

Here's usage; the following command executes all actions in the first 50,000 blocks in the SNAPSHOT_PATH (assuming it uses RocksDB):
```bash
dotnet run -p Lib9c.Benchmarks -- SNAPSHOT_PATH 50000
```
The following executs the last 50,000 blocks (there's `-` sign):
```bash
dotnet run -p Lib9c.Benchmarks -- SNAPSHOT_PATH -50000
```

Action execution benchmark

---

Lib9c.Benchmarks/Program.cs

- Fixed a part where a compilation error occurred in an external project.
- Temporarily displays total milli seconds.

Fix compile error that occurred in other project

---

Lib9c/Action/Buy.cs
Lib9c/Action/Buy2.cs
Lib9c/Action/Buy3.cs
Lib9c/Action/Sell.cs
Lib9c/Action/Sell2.cs
Lib9c/Action/SellCancellation.cs
Lib9c/Action/SellCancellation2.cs
Lib9c/Action/SellCancellation3.cs

This PR changes `Buy`, `Sell`, `SellCancellation` actions to use raw `Dictionary` instead of `ShopState` to reduce the serialization and deserialization time.
--- 
Before:
```
[22:45:28 DBG] Buy Total Executed Time: 00:00:00.3772240
[22:45:42 DBG] Sell Total Executed Time: 00:00:00.3090630
[22:46:38 DBG] Sell Cancel Total Executed Time: 00:00:00.2639720
```
After:
```
[22:50:03 DBG] Buy Total Executed Time: 00:00:00.1555280
[22:50:15 DBG] Sell Total Executed Time: 00:00:00.1101030
[22:51:02 DBG] Sell Cancel Total Executed Time: 00:00:00.0872910
```

Use raw Dictionary instead of ShopState

---

.Lib9c.Tests/Model/Item/ArmorTest.cs
.Lib9c.Tests/Model/Item/BeltTest.cs
.Lib9c.Tests/Model/Item/ChestTest.cs
.Lib9c.Tests/Model/Item/ConsumableTest.cs
.Lib9c.Tests/Model/Item/CostumeTest.cs
.Lib9c.Tests/Model/Item/EquipmentTest.cs
.Lib9c.Tests/Model/Item/MaterialTest.cs
.Lib9c.Tests/Model/Item/NecklaceTest.cs
.Lib9c.Tests/Model/Item/ShopItemTest.cs
Lib9c/Action/CreateAvatar.cs
Lib9c/Model/Item/Armor.cs
Lib9c/Model/Item/Belt.cs
Lib9c/Model/Item/Chest.cs
Lib9c/Model/Item/Consumable.cs
Lib9c/Model/Item/Costume.cs
Lib9c/Model/Item/Equipment.cs
Lib9c/Model/Item/ItemBase.cs
Lib9c/Model/Item/ItemUsable.cs
Lib9c/Model/Item/Material.cs
Lib9c/Model/Item/Necklace.cs
Lib9c/Model/Item/Ring.cs
Lib9c/Model/Item/ShopItem.cs
Lib9c/Model/Item/Weapon.cs

- The title says it all.
- In fact, we don't use the `Chest` object. However, it is cumbersome to remove it, so temporary measures are taken to avoid causing an error.

Fix runtime deserialization of `Chest`

---

.Lib9c.Tests/Action/HackAndSlash4Test.cs
.Lib9c.Tests/Action/MimisbrunnrBattle2Test.cs
.Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
.Lib9c.Tests/Action/RankingBattle3Test.cs
.Lib9c.Tests/Model/PlayerTest.cs
.Lib9c.Tests/Model/State/AvatarStateTest.cs
Lib9c/Action/DuplicateEquipmentException.cs
Lib9c/Action/HackAndSlash3.cs
Lib9c/Action/HackAndSlash4.cs
Lib9c/Action/MimisbrunnrBattle2.cs
Lib9c/Action/RankingBattle3.cs
Lib9c/Battle/RankingSimulator.cs
Lib9c/Battle/Simulator.cs
Lib9c/Battle/StageSimulator.cs
Lib9c/GameConfig.cs
Lib9c/Model/Character/Player.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/TableData/Character/CharacterLevelSheet.cs

- Bug fix/failed to `HackAndSlash3` when `AvatarState` already max level and max exp
- Improve equipment validation. (Prevent equipping more equipments than the slot that player has.)

Bug fix/failed to `HackAndSlash3` when `AvatarState` already max level and max exp

---

Lib9c/DebugPolicy.cs

Bumps `Libplanet` submodule to  [`1515c8edf684b3e021a6a7042736d2ad96aa0f37`](https://github.com/planetarium/libplanet/commits/1515c8edf684b3e021a6a7042736d2ad96aa0f37).

Bump Libplanet

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/AssemblyInfo.cs
Lib9c/BlockPolicy.cs
Lib9c/BlockPolicySource.cs
Lib9c/Miner.cs

This fixes [THE-9C-013](https://docs.google.com/document/d/13HQC9X_sz9wTrkOEt_qPnoMrPcoRpaohNytPwYArPqQ/edit).
As this changes the signature of `Miner()` constructor, NineChronices.Headless should be changed after this PR is merged:
https://github.com/planetarium/NineChronicles.Headless/blob/2f8de03237598fce639c65b9dc97ef7e5dd5c2ff/NineChronicles.Headless/NineChroniclesNodeService.cs#L160
Closes https://github.com/planetarium/lib9c/issues/301.

Fix THE-9C-013

---

Lib9c/BlockPolicy.cs

Reverts planetarium/lib9c#367 since we found misconfiguration and fixed it.

Revert "hotfix: condition"

---

Lib9c/Action/ActivateAccount.cs

This PR adds a log for `ActivateAccount` to help to track the activation code. (it's a temporary solution and we should remove it after https://github.com/planetarium/libplanet/issues/1156.

Activation log message

---

.Lib9c.Tests/Action/ActionContext.cs
.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/Action/ActionBase.cs
Lib9c/Model/Stat/StatType.cs
Lib9c/Model/State/AgentState.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/GoldCurrencyState.cs
Lib9c/Model/State/StateExtensions.cs

This pull request applies:
- planetarium/libplanet#1242
- planetarium/libplanet#1264
- planetarium/libplanet#1268
- planetarium/libplanet#1270
- planetarium/libplanet#1271
- planetarium/libplanet#1272
- planetarium/libplanet#1273
- planetarium/libplanet#1275
- planetarium/libplanet#1277
- planetarium/libplanet#1278
- planetarium/libplanet#1281
- planetarium/libplanet#1283 
- planetarium/libplanet#1289
- planetarium/libplanet#1291
After this pull request, you should take care when you use `Currency.Serialize()` because planetarium/libplanet#1289 pull request introduced `Libplanet.Assets.Currency.Serialize()` and the method signature conflicts with `Nekoyume.CurrencyExtensions.Serialize(this Currency)`.

chore: bump `Libplanet` into 0aaa054f14c4444ca4436e26d33df8f4b0fd9625

---

Lib9c/Action/HackAndSlash4.cs
Lib9c/Action/RankingBattle.cs
Lib9c/Battle/RankingSimulator.cs
Lib9c/Model/State/WeeklyArenaState.cs

`Lib9c.Benchmarks` result from latest 20 blocks.
before
```
Loading blocks  00:00:03.4116559
Executing actions       6438ms
Average per block       306ms
Average per tx  90ms
Average per action      76ms
Total elapsed   00:00:09.8500511
```
after
```
Loading blocks  00:00:02.6202123
Executing actions       5321ms
Average per block       253ms
Average per tx  74ms
Average per action      63ms
Total elapsed   00:00:07.9416374
```

Improve HackAndSlash, RankingBattle execution time

---

.Lib9c.Tests/BlockPolicyTest.cs
Lib9c/BlockPolicy.cs

Blocks without transactions are not accepted to prevent selfish mining.

Ignore block without transaction

---

.Lib9c.Tests/CanonicalChainComparerTest.cs
Lib9c/BlockPolicy.cs
Lib9c/CanonicalChainComparer.cs

As long as we have authorized miners who authorize a chain every 50 blocks, comparing blocks before the last authorized block is unnecessary for determining the canonical chain.  This patch tries an experimental approach to compare chains' *generation number* first, and then compare total difficulties among longest generations.
For example, suppose we have 4 competing chains (tips):
| Chains:          | Chain A | Chain B | Chain C |
|------------------|---------|---------|---------|
| Tip index        | 10001   | 10002   | 9999    |
| Last authorized  | 10000   | 10000   | 9950    |
| Generation       | 200     | 200     | 199     |
| Total difficulty | 50010   | 50009   | 50011   |
Under the existing rule ([`Libplanet.Blockchain.TotalDifficultyComparer`](https://github.com/planetarium/lib …

Proof of concept: See candidate chains' generation number first

---

.Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
.Lib9c.Tests/Action/MonsterCollectTest.cs
Lib9c/Action/ClaimMonsterCollectionReward.cs
Lib9c/Action/MonsterCollect.cs
Lib9c/Model/State/MonsterCollectionState.cs

This PR extends `MonsterCollectionState.DeriveAddress()` to receive collection round for previous monster collection. it can help migration due to continuing previous state.

Add support for previous monster collection

---

.Lib9c.Tests/Action/MonsterCollect2Test.cs
Lib9c/Action/MonsterCollect2.cs

This PR obsoletes previous `MonsterCollect`(`monster_collect2`) to `MonsterCollect2` and introduces new `MonsterCollect`(`monster_collect3`) to fix a bug where balance checking in `MonsterCollect` hadn't correct because it hadn't reflected refunded gold.

Fix balance checking in Monstercollect

---

Lib9c/Action/ActivateAccount.cs
Lib9c/Action/ActivateAccount0.cs
Lib9c/Action/IActivateAction.cs
Lib9c/BlockPolicySource.cs

This PR is continuous from #509 .
It allows `ActivateAccount0` from activation check for pre-migration situations and previous chain replaying.

Fix ActivateAccount0 handling

---

Lib9c/BlockPolicy.cs

This PR is continued from #494 . it adjusts the start block that will be applied new policy from 2,100,000 to 2,150,000.

Adjust prams for tx limit

---

Lib9c/BlockPolicy.cs

#539 adjusted start block to 2,150,000 (Scheduled for around August 13th). since this is too far to get the result, I correct it to 2,110,000 blocks

Retake of 539

---

Lib9c/BlockPolicySource.cs

This PR adds `using Lib9c` for Unity Editor

Fix missing using error on Unity Editor

---

.Lib9c.Tests/Action/HackAndSlashTest.cs
.Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
Lib9c/Action/ActionBase.cs
Lib9c/Action/HackAndSlash.cs
Lib9c/Action/MimisbrunnrBattle.cs
Lib9c/Renderer/ActionRenderer.cs

This PR removes `.Result` property to lighten the action, reducing the memory load.

Remove .Result properties from `HackAndSlash` (and its likes)

---

.Lib9c.Tests/Action/CombinationConsumableTest.cs
.Lib9c.Tests/Action/CombinationEquipmentTest.cs
.Lib9c.Tests/Model/Item/InventoryTest.cs
Lib9c/Action/CombinationConsumable.cs
Lib9c/Action/CombinationConsumable0.cs
Lib9c/Action/CombinationConsumable2.cs
Lib9c/Action/CombinationConsumable3.cs
Lib9c/Action/CombinationConsumable4.cs
Lib9c/Action/CombinationConsumable5.cs
Lib9c/Action/CombinationConsumable6.cs
Lib9c/Action/CombinationEquipment.cs
Lib9c/Action/CombinationEquipment0.cs
Lib9c/Action/CombinationEquipment2.cs
Lib9c/Action/CombinationEquipment3.cs
Lib9c/Action/CombinationEquipment4.cs
Lib9c/Action/CombinationEquipment5.cs
Lib9c/Action/CombinationEquipment6.cs
Lib9c/Action/ItemEnhancement0.cs
Lib9c/Action/ItemEnhancement2.cs
Lib9c/Action/ItemEnhancement3.cs
Lib9c/Action/ItemEnhancement4.cs
Lib9c/Action/ItemEnhancement5.cs
Lib9c/Action/ItemEnhancement6.cs
Lib9c/Action/ItemEnhancement7.cs
Lib9c/Action/Sell2.cs
Lib9c/Model/Item/Inventory.cs
Lib9c/Model/State/AvatarState.cs

- Remove useless method
- Rename `LegacyRemoveNonFungibleItem()` to `RemoveNonfungibleItem2()` of `Inventory`
- Archive `UpdateFromCombination()` and `UpdateFromItemEnhancement()` of `AvatarState`
- Improve test for Inventory
- Fix bug of `CombinationConsumable`
- Fix bug of `CombinationEquipment`

Bug fix/remove fungible item in combination actions

---

.Lib9c.Tests/MinerTest.cs
Lib9c/Miner.cs

This patch depends on <https://github.com/planetarium/lib9c/pull/619>, as it uses [`txPriority` option which is Libplanet's recent feature][1].
[1]: https://github.com/planetarium/libplanet/pull/1477

Give priority to proof transactions so that they are never cut off from mining

---

Lib9c/Model/State/WeeklyArenaState.cs

This PR restores AgentAddress and AvatarName on ArenaInfo to restore GraphQL API to fetch that information.

Restore needed props in ArenaInfo

---

Lib9c/Model/State/ArenaInfo.cs

Revert few obsoleted fields of `ArenaInfo` for headless

---

.Lib9c.Benchmarks/Program.cs

This PR adds an `offset` argument to `Lib9c.Benchmarks` so that it has the option to execute blocks from the offset value. 
```
dotnet run --project .\.Lib9c.Benchmarks\Lib9c.Benchmarks.csproj [store-path] [limit] [offset]
```
- Example:
```
dotnet run --project .\.Lib9c.Benchmarks\Lib9c.Benchmarks.csproj C:\Users\user\9c-main 10 20
- This will execute blocks from #20 to #29.
dotnet run --project .\.Lib9c.Benchmarks\Lib9c.Benchmarks.csproj C:\Users\user\9c-main 10
- This will execute blocks from #0 to #9 like the original benchmark because an offset value is not provided.
```
**Note)** 
When using the `offset value`, the blockchain store **MUST CONTAIN STATES** for those blocks or else, a `KeyNotFoundException`(https://github.com/planetarium/libplanet/blob/main/Libplanet.RocksDBStore/Rocks …

add offset argument to `Lib9c.Benchmarks`

---

.Lib9c.Benchmarks/Program.cs
.Lib9c.Tests/Data/TableCSV/Item/MaterialItemSheet.csv

from https://github.com/planetarium/NineChronicles/blob/development/nekoyume/Assets/AddressableAssets/TableCSV/Item/MaterialItemSheet.csv
I update the latest sheet from the NineChronicles repository for a new headless unit test case.
https://github.com/planetarium/NineChronicles.Headless/blob/InventoryItemType/NineChronicles.Headless.Tests/GraphTypes/States/Models/InventoryTypeTest.cs

[sheet modified] Update arena season 0 medal item 

---

Lib9c/Policy/BlockPolicySource.cs

1. namespace of DebugPolicy was changed `Lib9c` to `Nekoyume.BlockChain.Policy` in this [commit](https://github.com/planetarium/lib9c/commit/451fba16b558122761fccc60efb0b271e8a59a6f)
2. This made compile error in unity, so I fixed it.
https://github.com/planetarium/lib9c/commit/451fba16b558122761fccc60efb0b271e8a59a6f

Fix compile error

---

Lib9c/BlockHelper.cs
Lib9c/ReorgMiner.cs

Unless there is a specific reason, max transactions per block should be controlled by policy.

Max transactions removed from `ReorgMiner.MineBlockAsync()`

---

.Lib9c.Tests/StagePolicyTest.cs
Lib9c/Policy/BlockPolicySource.cs

As [headless] uses a custom policy in several places for testing, simply removing a deprecated `GetPolicy()` results in much increased time for performing tests. From [headless]'es perspective, one might want to perform tests on a chain with a policy identical to the deployed one, but I don't think this should grant [headless] permission to "customize" the underlying [lib9c] policy on the fly, as it isn't really a proper feature that is needed for [headless] to care about. This is an ad hoc fix instead of a proper fix that would provide a set of fixtures as a part of a testing suite for [headless] to use on a [lib9c] level. 🙃 
[headless]: https://github.com/planetarium/NineChronicles.Headless
[lib9c]: https://github.com/planetarium/lib9c

Removed deprecated GetPolicy() and added GetTestPolicy()

---

Lib9c/Policy/BlockPolicySource.cs
Lib9c/Policy/MaxBlockBytesPolicy.cs
Lib9c/Policy/MaxTransactionsPerSignerPerBlockPolicy.cs

Closes #701, #702.
Indices must be **finalized** before this gets **deployed**.

Policy updates with context

---

Lib9c/Action/Buy.cs
Lib9c/Action/Buy9.cs
Lib9c/Action/IBuy5.cs

There are `IBuy5` interface which implemented in the `Buy` action since the `Buy5` action. But the `Buy9` action doesn't.

Implement missing interface

---

.Lib9c.Tests/MinerTest.cs
.Lib9c.Tests/Policy/BlockPolicyTest.cs
Lib9c/Miner.cs

Partially addresses https://github.com/planetarium/NineChronicles.Headless/issues/853.
Should be also included in https://github.com/planetarium/NineChronicles.Headless/pull/857 once this is merged.

Specialized authorized miner behavior option removed from Miner

---

.github/workflows/main.yml

Unreleased version of Libplanet shouldn't be used.  Instead, use the latest released version: <https://github.com/planetarium/libplanet/releases/tag/0.21.1>.

Use Libplanet 0.21.1 (instead of bleeding edge)

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
.Lib9c.Tests/Action/ActivateAccountTest.cs
.Lib9c.Tests/Action/MonsterCollect2Test.cs
.Lib9c.Tests/Action/MonsterCollectTest.cs
.Lib9c.Tests/Model/State/StateExtensionsTest.cs
.Lib9c.Tests/Types/BencodexTypesListTest.cs
.Lib9c.Tools/SubCommand/Tx.cs
Lib9c/Action/ActionBase.cs
Lib9c/Action/Buy5.cs
Lib9c/Action/Buy6.cs
Lib9c/Action/Buy7.cs
Lib9c/Action/InitializeStates.cs
Lib9c/Action/Sell4.cs
Lib9c/Action/Sell5.cs
Lib9c/Action/Sell6.cs
Lib9c/Action/SellCancellation5.cs
Lib9c/Action/SellCancellation6.cs
Lib9c/CurrencyExtensions.cs
Lib9c/Model/Item/Inventory.cs
Lib9c/Model/Item/OrderLock.cs
Lib9c/Model/State/ActivatedAccountsState.cs
Lib9c/Model/State/StateExtensions.cs
Lib9c/Policy/BlockPolicy.cs
Lib9c/Policy/BlockPolicySource.Utils.cs
Lib9c/Policy/BlockPolicySource.cs
Lib9c/Policy/DebugPolicy.cs
Lib9c/Policy/MaxBlockBytesPolicy.cs
Lib9c/TableData/Item/MaterialItemSheet.cs

This bump purposes to take advantage of performance improvements made from the recent (unreleased) changes of Bencodex.  See also:
- https://github.com/planetarium/libplanet/pull/1609
- https://github.com/planetarium/bencodex.net/pull/54
- https://github.com/planetarium/bencodex.net/pull/49

Upgrade Libplanet to 0.22.0-nightly.20211124+a3eddcb

---

.github/workflows/main.yml

This patch fixes two bugs of the *.Libplanet* submodule check on CI:
- It had disallowed *.Libplanet* to refer to an unsigned tag.  Now it is okay whether the tag is signed or not.
- It had checked if *.Libplanet* refers to a tagged commit even on the development branch.  However, as it is not convenient to make a new release of Libplanet to apply only a part of changes of unreleased Libplanet to Lib9c's development branch, now the check is skipped on the development branch.  It only runs on the main or rc- branches or tags.

Fix a broken submodule check on CI

---

.github/workflows/main.yml

Port <https://github.com/planetarium/lib9c/pull/756> to development:
> This patch fixes two bugs of the *.Libplanet* submodule check on CI:
>
> - It had disallowed *.Libplanet* to refer to an unsigned tag.  Now it is okay whether the tag is signed or not.
>
> - It had checked if *.Libplanet* refers to a tagged commit even on the development branch.  However, as it is not convenient to make a new release of Libplanet to apply only a part of changes of unreleased Libplanet to Lib9c's development branch, now the check is skipped on the development branch.  It only runs on the main or rc- branches or tags.

Port #756 to development: Fix a broken submodule check on CI

---

.Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
.Lib9c.Tests/Action/RankingBattle0Test.cs
.Lib9c.Tests/Action/RankingBattle2Test.cs
.Lib9c.Tests/Action/RankingBattle3Test.cs
.Lib9c.Tests/Action/RankingBattle4Test.cs
.Lib9c.Tests/Action/RankingBattle5Test.cs
.Lib9c.Tests/Action/RankingBattle6Test.cs
.Lib9c.Tests/Action/RankingBattle7Test.cs
.Lib9c.Tests/Action/RankingBattle8Test.cs
.Lib9c.Tests/Action/RankingBattleTest.cs
.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tests/Model/State/WeeklyArenaStateTest.cs
.Lib9c.Tools.Tests/Lib9c.Tools.Tests.csproj
.Lib9c.Tools/Lib9c.Tools.csproj
global.json

This fixes MSBuild files and *global.json* so that the entire project can be built and tested using .NET 6 on Apple Silicon (aarch64-apple-darwin), commonly known as M1 series.  On other platforms/processors, it still uses .NET Core 3.1 SDK.
Note that .NET 6 disallows value types to be used without explicit assignment: [CS0165].  So I give explicit `default` values to unassigned variables.  (These changes don't affect their semantics.)
See also my other patches done the same thing:
- <https://github.com/planetarium/libplanet/pull/1635>
- <https://github.com/planetarium/rocksdb-sharp/pull/6>
- <https://github.com/planetarium/bencodex.net/commit/cea19a5aa27030c0c58bd22ab016c102b879d4fa>
[CS0165]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/cs0165

Build on Apple Silicon (aarch64-apple-darwin)

---

.Lib9c.Tests/Action/HackAndSlash7Test.cs
.Lib9c.Tests/Action/HackAndSlash8Test.cs
.Lib9c.Tests/Action/HackAndSlash9Test.cs
.Lib9c.Tests/Action/HackAndSlashTest.cs
.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tests/Model/QuestListExtensions.cs
.Lib9c.Tests/Model/QuestListTest.cs
.Lib9c.Tests/Model/State/LazyStateTest.cs
.Lib9c.Tests/TestHelper/BencodexHelper.cs
.Lib9c.Tools/Lib9c.Tools.csproj
.Lib9c.Tools/Program.cs
.Lib9c.Tools/SubCommand/Account.cs
.Lib9c.Tools/SubCommand/Market.cs
.Lib9c.Tools/SubCommand/State.cs
.Lib9c.Tools/Utils.cs
Lib9c/Action/Buy0.cs
Lib9c/Action/CombinationEquipment0.cs
Lib9c/Action/HackAndSlash2.cs
Lib9c/Model/CollectionMap.cs
Lib9c/Model/Item/Inventory.cs
Lib9c/Model/Quest/Quest.cs
Lib9c/Model/Quest/QuestList.cs
Lib9c/Model/Quest/QuestReward.cs
Lib9c/Model/State/ArenaInfo.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/LazyState.cs
Lib9c/Model/State/RankingState.cs
Lib9c/Model/State/StateExtensions.cs
Lib9c/Model/State/WeeklyArenaState.cs
Lib9c/Model/WorldInformation.cs

To utilize [Libplanet's recent optimization](https://github.com/planetarium/libplanet/pull/1636) which enables offloading and lazy-loading of fragmented states, I added `LazyState<TState, TEncoding>` and applied it to several model types:
- `CollectionMap`
- `RankingState`
- `WeeklyArenaState`
- `Inventory.Item`[^1]
- `WorldInformation`
- `QuestList`
It's just my first try, and I'm going to work on further optimization later.
I wanted to make it faster to execute actions, but there was no change time-wise (it's neither slower though).  Instead, it became to take much less disk space: 1.35 GB → 436 MB for about 20,000 blocks.[^2]
[^1]: I tried to work on the entire `Inventory` type, but it's quite complex to change things in it without breaking backward compatibility.
[^2]: blocks \#0 …

Upgrade Libplanet to 0.23.0 & lazy-load only needed subtrees

---

Lib9c/Policy/BlockPolicySource.cs

According to policy, it was extended to 5,716,957, estimated by calculation with ended time '2022.12.31. 09:00:00 UTC' and time per block '12s'.
- It uses [the 2936621 block](https://9cscan.com/blocks/2936621) as start point. It was mined on *December 10, 2021, 05:00:10 UTC*.
- We want the authorized block to be ended about *December 31, 2022, 09:00:00 UTC*.
- It assumed 12 seconds as block mining time.
The below line is Python code to estimate it.
```python
>>> 2936558 + (datetime.datetime.fromisoformat("2022-12-31T09:00:00.000000") - datetime.datetime.fromisoformat("2021-12-10T05:00:10.000000")).total_seconds() // 12
5716957.0
```

feat: extend 'authorized miner end index'

---

.Lib9c.Tests/Action/RenewAdminStateTest.cs
.Lib9c.Tools/SubCommand/Tx.cs
Lib9c/Action/RenewAdminState.cs

The `AdminState` will be soon expired after the 3153600 block number. When the `AdminState` was expired, some actions like `PatchTableSheet` and `CreatePendingAccount` will not work. But the Proof-of-Stake or other system is not built yet.
So this pull request introduces `RenewAdminState` action which renew `AdminState.ValidUntil` field. It requires Admin permission so it should be executed before the block 3153600.

feat: introduce `RenewAdminState` action

---

Lib9c/Policy/BlockPolicySource.cs

Attempts to prevent invalid `Transaction<T>`s clogging the network making the game unplayable for those who try to activate an account more than once.
@longfin should take a look. 🙄

Prevent double activation attempt

---

.Lib9c.Tools/SubCommand/Tx.cs

This PR adds `tx create-activation-keys` command to generate activation key(a.k.a. invitation code)s. 
it also adjusts `tx create-pending-activations` to receive a csv file from `tx create-activation-keys`.

Add `create-activation-keys` command

---

Lib9c/Miner.cs

Originally, `Miner` mined block and append it in two steps. But `BlockChain<T>.MineBlock()` supports to append block in once to avoid evaluating actions again.

Optimize miner to append block

---

.Lib9c.Tests/Action/RenewAdminStateTest.cs

This pull request adds a test to simulate creating pending activations as the admin does.

test: create pending activations with renew admin state

---

Lib9c.sln
Lib9c/Lib9c.csproj

This reverts commit 90b65d444aea4caeba03f44135383beb4f974cd4 (except that .Libplanet submodule now refers to 0.28.1 instead of 0.28.0.)

Upgrade Libplanet to 0.28.1

---

.github/workflows/main.yml

I worked on the GitHub Actions workflow triggered by tag pushes.  Now it does the following process for every tag push:
1. Check if the tag refers to a property merge commit, or a commit signed by GitHub @web-flow.  In other words, it ensures that the tagged commit is made by the merge button on GitHub web.
2. Open pull requests to _rc-v\*_ branches of *NineChronicles.Headless* & *NineChronicles* so that their submodules become to refer to the just released tag.  It will be done by @planet-submodule-updater account.  See also [Submodule Updater].
[Submodule Updater]: https://github.com/planetarium/submodule-updater

Release automation

---

Lib9c/GameConfig.cs

For the debug, the editor conditionally changed the value so that the action could be used in Mimir even at level 1. The condition that controls this is `GameConfig.IsEditor`.
In Editor 🔽

Add contidional value change `ActionsInMimisbrunnr`

---

.gitmodules

- The submodule name and its path did not match.  Now it shares the same identifier.
- The submodule URL changed from SSH URL to HTTPS URL.  GitHub's SSH clone URLs require contributors to have permission to push commits to the repository.  HTTPS clone URLs, however, require only permission to clone/pull.

Fix up Git submodules

---

Lib9c/Policy/BlockPolicySource.Utils.cs
Lib9c/Policy/BlockPolicySource.cs

This PR restores `IsAuthorizedMinerTransactionRaw()` (see also #911) check due to process previous blocks already in the chain.

Restore IsAuthorizedMinerTransactionRaw

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/StakeTest.cs

Currently, there are `Stake` & `ClaimStakeReward` actions and they aren't registered to `PolymorphicAction<ActionBase>` because they don't have `ActionTypeAttribute`. And it is intended.
So this pull request adds more tests to check `Stake` & `ClaimStakeReward` not registered yet explicitly.

More tests to check `Stake` & `ClaimStakeReward` not registered yet

---

.Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
.Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tools.Tests/Lib9c.Tools.Tests.csproj
.Lib9c.Tools/Lib9c.Tools.csproj
.github/workflows/main.yml
.github/workflows/publish.yml
global.json

[Because .NET 3.1 LTS support will be stopped on December 3, 2022][dotnet-lifecycle], we should move to .NET 6 LTS before it.
This pull request does it and the project contributors should install .NET 6 if you didn't install it yet.
[dotnet-lifecycle]: https://docs.microsoft.com/ko-kr/lifecycle/products/microsoft-net-and-net-core

Move to .NET 6

---

.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
Lib9c/Action/MigrateMonsterCollection.cs

This pull request introduces `MigrationMonsterCollection` action to migrate `MonsterCollectionState` to `StakeState` for keeping staking period.

Introduce `MigrateMonsterCollection` action

---

Lib9c/Policy/BlockPolicySource.cs

This pull request introduces the `BlockPolicySource.GetDefaultPolicy()` method to create the `IBlockPolicy<T>` instance with default options, without authorized mining and permissioned mining. Because the addresses are fixed in the code, other networks cannot be generated without updating the code.

Introduce `BlockPolicySource.GetDefaultPolicy()` method

---

.Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
.Lib9c.Tests/Action/CombinationEquipmentTest.cs
.Lib9c.Tests/CrystalCalculatorTest.cs
.Lib9c.Tests/Model/State/CrystalCostStateTest.cs
Lib9c/Action/AccountStateDeltaExtensions.cs
Lib9c/Action/CombinationEquipment.cs
Lib9c/Addresses.cs
Lib9c/Helper/CrystalCalculator.cs
Lib9c/Model/State/CrystalCostState.cs

- MVP for CRYSTAL price.
- Calculate the crystal cost by the ratio of the previous week's and before previous week's crystal costs.
- Add cost history by day & week.

Introduce CRYSTAL price fluctuation MVP

---

Lib9c/Helper/AvatarStateExtensions.cs

Ever since the addition of `HackAndSlashSweep`, the action execution result between `amd` and `arm` architectures have shown some inconsistency. 
After some research, this issue appears to have been caused by the different results of `dividing by zero` between two architectures. 
This fix ensures that the calculation results are consistent in both `amd` and `arm`.

fix zero division inconsistency between amd and arm architecture

---

.Lib9c.Tests/Action/JoinArenaTest.cs
.Lib9c.Tests/Model/Arena/ArenaAvatarStateTest.cs
.Lib9c.Tests/Model/Arena/ArenaInformationTest.cs
.Lib9c.Tests/Model/Arena/ArenaParticipantsTest.cs
.Lib9c.Tests/Model/Arena/ArenaScoreTest.cs
.Lib9c.Tests/TableData/ArenaSheetTest.cs
.Lib9c.Tests/TableSheets.cs
Lib9c/Action/AccountStateDeltaExtensions.cs
Lib9c/Action/JoinArena.cs
Lib9c/Action/NotEnoughMedalException.cs
Lib9c/Addresses.cs
Lib9c/Arena/ArenaHelper.cs
Lib9c/Extensions/SheetsExtensions.cs
Lib9c/Helper/AvatarStateExtensions.cs
Lib9c/Model/Arena/ArenaExceptions.cs
Lib9c/Model/Arena/ArenaInformation.cs
Lib9c/Model/Arena/ArenaParticipants.cs
Lib9c/Model/Arena/ArenaScore.cs
Lib9c/Model/EnumType/ArenaType.cs
Lib9c/Model/State/ArenaAvatarState.cs
Lib9c/TableCSV/Arena.meta
Lib9c/TableCSV/Arena/ArenaSheet.csv
Lib9c/TableCSV/Arena/ArenaSheet.csv.meta
Lib9c/TableCSV/Item/MaterialItemSheet.csv
Lib9c/TableData/ArenaSheet.cs
Lib9c/TableData/Exceptions.cs
Lib9c/TableData/SimulatorSheets.cs

Only parts related to the Join Arena action were taken from https://github.com/planetarium/lib9c/pull/1006
---
- Create `JoinArena` action 
- Create `ArenaAvatar` state
- This state has the avatar information you need in the arena. (equipment, costumes, avatar level)
- Create `ArenaParticipants` 
- ArenaParticipants has a list of participants for the arena
- Create `ArenaScore`
-  ArenaScore only has a score.
- Create `ArenaInformation` 
- ArenaInformation has win, lose, ticket
- Create  `Arena` Sheet
- This sheet contains arena related information
- Update `RewardGold`
- Add RefillArenaTicket function

Introduce JoinArena action

---

.Lib9c.Tests/Action/HackAndSlashSweepTest.cs
.Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
Lib9c/Action/HackAndSlashSweep.cs

Related to https://github.com/planetarium/lib9c/pull/1017
Add first stage sweep test case & Fix stage check rule
----
And... I'm add below code
```csharp
...
var firstStage = prevStageId == 1;
...
if (!prevStageWorld.IsStageCleared && !firstStage)
...
```
I don't think it's best to do hardcoding like this
Is there any way to get information about the first stage of the first world?

Fix first stage sweep bug

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs

Since one-time rewards were gone, related checks are useless. Current `ClaimStakeReward` doesn't depend on `StakeAchievementRewardSheet`.

Clean up useless check in `ClaimStakeRewardTest`

---

.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
Lib9c/Action/MigrateMonsterCollection.cs

Since #1010, `Stake` and `ClaimStakeReward` became `PolymorphicAction<T>` but `MigrateMonsterCollection` was missed. This pull request does it.

Make `MigrateMonsterCollection` action as polymorphic

---

Lib9c/Miner.cs

This patch adds a nullable `BlockCommit` typed `lastCommit` argument to `Miner.MineBlockAsync()`.

Support lastcommit

---

.Lib9c.Tests/Action/HackAndSlashSweepTest1.cs
.Lib9c.Tests/Action/HackAndSlashSweepTest2.cs
.Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
Lib9c/Action/HackAndSlashSweep1.cs
Lib9c/Action/HackAndSlashSweep2.cs
Lib9c/Action/HackAndSlashSweep3.cs
Lib9c/Helper/AvatarStateExtensions.cs

[[스윕] 스윕으로 EXP를 획득 시 보유 EXP가 100이 될 경우 레벨업을 하지 않는 현상](https://app.asana.com/0/1133453747809944/1202350473096109)

Version up GetLevelAndExp()

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
Lib9c/Action/ClaimStakeReward.cs

This pull request makes `ClaimStakeReward` avoid to add items with zero count.

Avoid to add items with zero count

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
Lib9c/Action/ClaimStakeReward.cs

This pull request is continued from #1073. The #1073 PR will break the chain consistency on the `previewnet` network because it was changed to update states differently. So this pull request makes the action execute like the original action if it's `previewnet` and the block index is under 1,200,000.

Add zero item for chain consistency, in the condition

---

Lib9c/Action/MonsterCollect.cs

Since https://github.com/planetarium/lib9c/commit/3af6407fc02e2f5d7936f131c65a9261046e80f8, the link was introduced but the pull request link has a typo. This pull request fixes it.

Correct link

---

.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
Lib9c/Action/MigrateMonsterCollection.cs
Lib9c/Model/State/StakeState.cs

Originally the action migrated and made halt stake state. This pull request fixes it.

Correct `MigrateMonsterCollection` action

---

.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
Lib9c/Action/MigrateMonsterCollection.cs

This pull request tries to make `MigrateMonsterCollection` action skip `ClaimMonsterCollectionReward` action execution if there is no rewards. It's because it causes an error if there is no rewards to receive yet.
This pull request resolves the issue.

Skip `ClaimMonsterCollectionReward` if there is no rewards

---

.Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs

This pull request assumes it can be trusted in all cases if the case before just one block up to lockup interval is verified.
Originally, the #1124 build failed because the previewnet lockup interval was different from the 2022q2 branch. Because originally it subtracts over 50000 though the previewnet's lockup interval is about 5000. So this pull request resize the domain into only one case.

Trust lockup interval processing

---

.Lib9c.Tests/Action/ClaimMonsterCollectionRewardTest.cs
.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
.Lib9c.Tests/Action/MonsterCollectTest.cs
Lib9c/Action/ClaimMonsterCollectionReward.cs
Lib9c/Action/MonsterCollect.cs
Lib9c/Policy/BlockPolicySource.cs

> I wrote this pull request by the insider request from @jaeho0103. Maybe it is a proposal yet. With these changes, it expects monster collection users to move to the stake because it makes users not able to accumulate more monster collection rewards since specific block index. To understand the full context, you should look `features/stake` branch.
- Obsolete `ClaimMonsterCollectionReward`, `MonsterCollect`.
- Limit monster collection rewards since the `ClaimMonsterCollectionReward.MonsterCollectionEndBlockIndex`. Since the index, rewards will not be accumulated.
- Update `BlockPolicySource.V100220ObsoleteIndex` to 2 weeks later from the v100220 target date, June 15 KST. (calculation formula: `((2 * 7 + 2) * 24 * 60 * 60 / 11) + 4264600`)
- Prevent doing monster …

Obsolete monster collection

---

.Lib9c.Tests/Action/RewardGoldTest.cs
Lib9c/Action/RewardGold.cs

This issue occurs from the state calculated by `BlockChain.MakeGenesisBlock` and the result of actual block evaluation are different. maybe we fix [BlockChain.MakeGenesisBlock](https://github.com/planetarium/libplanet/blob/a3bfb32eaabe31a5c221dcf6918725e6f50e963c/Libplanet/Blockchain/BlockChain.cs#L362) /cc @libplanet

Avoid InvalidStateRootHashException in genesis

---

.Lib9c.Tests/Action/StakeTest.cs
Lib9c/Action/Stake.cs

Originally, it renewed staking with the same amount and set `startedBlockIndex` to 0 again. This pull request restricts a behavior like it since the specific block index, `4611070`.

Prevent renew staking with same amount

---

Lib9c/Action/RankingBattle.cs

- Target version : `v100240`
- Update Rankingbattle : Fix Arena exception handling for InvalidBlockStateRootHashException
- Related link: https://planetariumhq.slack.com/archives/C032BBQTQJY/p1656470290663319

Fix Arena exception handling for InvalidBlockStateRootHashException

---

.Lib9c.Tests/Action/ActionContextExtensionsTest.cs
Lib9c/Action/ActionContextExtensions.cs

This pull request resolves #1087.
This pull request introduces new extension methods of the `IActionContext` interface to help branch bugfixes by chain and block index. The methods are the same as the below list:
- `bool Since(long blockIndex)`
- `bool IsMainNet()`
I expected a use-case like the below code:
```csharp
const long hardforkBlockIndex = 1_000_000;
if (context.IsMainNet() && context.Since(hardforkBlockIndex))
```
I wrote code assuming that the `GoldCurrencyState.Currency` will not be changed. I think the gold currency should be static because everyone will lose their NCG if the gold currency is altered and it becomes a new standard. If you have an opinion about this, feel free to start a discussion about it.
And I wonder your opinions about what is better between using a new …

feat(#1087): introduce useful `IActionContext` extensions

---

Lib9c/Extensions/CombinationSlotStateExtensions.cs

Block [#4372674](https://9cscan.com/blocks/4372674) execution resulted in an `InvalidBlockStateRootHashException` since `v100231`.
The problem was due to `RapidCombination6` action not including the previous `ItemEnhancement9` action in `Lib9c/Extensions/CombinationSlotStateExtensions.cs` which resulted in the following error:
```
Libplanet.Action.UnexpectedlyTerminatedActionException: The action Libplanet.Action.PolymorphicAction<Nekoyume.Action.RapidCombination> (block #4372674, pre-evaluation hash ef0796837568bb6f9f260c9363d5dd690267df0cd394c633415395cf7e000000, tx b977a43e17dffb824d9c649e5239adb9a20f61acf5839a060d0ba626963a4c6a, previous state root hash 0e7cb552dfe8a2a3cad5f7ac07f00e26e7f894e005a1e4d27724f76d00e7c099) threw an exception during execution.  See also this exception's …
```

[Bug Fix] Add case for `ItemEnhancement9`

---

.Lib9c.Tools/SubCommand/Tx.cs

- Call `ISheet.Set` when create `PatchTableSheet` action.
```
yang@yangcheon-ung-ui-MacBookPro .Lib9c.Tools % dotnet run tx patch-table /Users/yang/projects/lib9c/Lib9c/TableCSV/Arena/ArenaSheet.csv
----------------
ArenaSheet
----------------
id,round,arena_type,start_block_index,end_block_index,required_medal_count,entrance_fee,ticket_price,additional_ticket_price
1,1,OffSeason,1,4480000,0,0,5,2
1,2,Season,4480001,4580800,0,1,50,20
1,3,OffSeason,4580801,4631200,0,0,5,2
1,4,Season,4631201,4732000,0,1,50,20
1,5,OffSeason,4732001,4782400,0,0,5,2
1,6,Season,4782401,4883200,0,1,50,20
1,7,OffSeason,4883201,4933600,0,0,5,2
1,8,Championship,4933601,5034400,240,4,50,20
2,1,OffSeason,5034401,5084800,0,0,5,2
2,2,Season,5084801,5185600,0,1,50,20
2,3,OffSeason,5185601,5236000,0,0,5,2 …
```

Validate sheet data in tx command

---

Lib9c/Extensions/CombinationSlotStateExtensions.cs

Newer C# versions require variables with value types to be explicitly initialized.  (The older compiler silently added zero-fill initialization for these uninitialized variables.)
Note that this branch (*migration*) does not catch up the latest *development*, but stick with the *main* is intended, because it shouldn't hard-fork the mainnet so that we can easily test with it.

Explicitly initialize variables with value types

---

.Lib9c.Tests/Model/Event/EventDungeonInfoTest.cs
Lib9c/Model/Event/EventDungeonInfo.cs

The `EventDungeonInfo` class is a model stored at a unique address derived from the address of a specific `AvatarState` and the `Id` of a specific `EventDungeonSheet.Row`.
The `EventDungeonInfo` class stores the number of remaining tickets for a specific event dungeon in a specific `AvatarState`, and the `Id` of the highest cleared `EventDungeonStageSheet.Row` is stored.
Unlike the `WorldInformation` class, the `EventDungeonInfo` class does not validate the game logic deeply. Validation delegates to actions using the `EventDungeonInfo` class, etc.

Introduce `EventDungeonInfo`

---

.Lib9c.Tests/Action/HackAndSlashTest.cs
.Lib9c.Tests/Model/BattleLogTest.cs
.Lib9c.Tests/Model/PlayerTest.cs
.Lib9c.Tests/Model/Skill/NormalAttackTest.cs
.Lib9c.Tests/Model/StageSimulatorTest.cs
.Lib9c.Tests/TableSheets.cs
Lib9c/Action/AccountStateDeltaExtensions.cs
Lib9c/Action/HackAndSlash.cs
Lib9c/Action/MimisbrunnrBattle.cs
Lib9c/Battle/StageSimulator.cs
Lib9c/Extensions/SheetsExtensions.cs
Lib9c/TableData/SimulatorSheets.cs

This pull request contains changes of `HackAndSlash`(15) and `MimisbrunnrBattle`(10). But these actions are not deployed yet. So do not upgrade these actions.
- Inject `StageSheet.Row` and `StageWaveSheet.Row` as arguments of `StageSimulator`'s constructor.
- Update `SimulatorSheets` to not be abstract
- Apply changes of `StageSimulator` to `HackAndSlash`(15) and `MimisbrunnrBattle`(10)
- Use `IAccountStateDelta.GetSheets()` on `MimisbrunnrBattle`(10)

Refactor `StageSimulator` and `MimisbrunnrBattle`

---

.Lib9c.Tests/Action/Stake0Test.cs
Lib9c/Action/Stake.cs
Lib9c/Action/Stake0.cs

- Correct `stake` action.
- Introduce a new action called `stake2` to continue `stake`.
- `stake2` action became `GameAction` now.
You can review it through commits because they have a commit to copy files.

Correct `Stake` action

---

.Lib9c.Tests/Lib9c.Tests.csproj

- Update depedency for avoid version conflict.
https://github.com/planetarium/NineChronicles.Headless/runs/7758859828?check_suite_focus=true

Fix dependecny conflict in headless

---

Lib9c/Action/Buy11.cs
Lib9c/Action/CombinationEquipment11.cs
Lib9c/Action/HackAndSlash13.cs
Lib9c/Action/HackAndSlashSweep4.cs
Lib9c/Action/ItemEnhancement10.cs
Lib9c/Action/RankingBattle.cs
Lib9c/Action/RapidCombination6.cs

When we updated the mainnet version from `v230` to `v240`, there were some deployment errors which ended up causing blocks from `#4374157` and `#4377430` to be evaluated differently compared to the canonical chain. I've narrowed down the specific actions (`Buy11`, `CombinationEquipment11`, `HackAndSlashSweep4`, `ItemEnhancement10`, `RankingBattle`, and `RapidCombination6`) causing these problems and added conditions that would allow the execution results to match the canonical chain.

fix action evaluation results in `v100240`

---

.Lib9c.Tests/Action/ActionContext.cs
.Lib9c.Tools/SubCommand/Account.cs
.Lib9c.Tools/SubCommand/Market.cs
.Lib9c.Tools/SubCommand/State.cs
.Lib9c.Tools/SubCommand/Tx.cs
Lib9c/Policy/BlockPolicySource.Utils.cs
Lib9c/Policy/BlockPolicySource.cs
Lib9c/Policy/DebugPolicy.cs

As [Libplanet recently introduced native tokens and system actions][1], Lib9c also needs to follow up these changes.  It's also a preparation for adopting Libplanet 0.40.0.
[1]: https://github.com/planetarium/libplanet/pull/2175

Upgrade Libplanet and follow up API changes related to native tokens and system actions

---

.Lib9c.Tools/Program.cs
.Lib9c.Tools/SubCommand/Action.cs
.github/workflows/main.yml

This pull request resolves #1279 
- Introduce `Lib9c.Tools action list` command.
- Publish `all_action_type_ids.txt` for every `v` release tag pushed.
- You can see the example at https://github.com/moreal/lib9c/blob/gh-pages/vtt/all_action_type_ids.txt

Introduce `Lib9c.Tools action list`

---

.Lib9c.Tests/Action/RaidTest.cs
Lib9c/Action/Raid.cs
Lib9c/Model/State/RaiderState.cs

- check previous execute block index for prevent spamming action execute.
- `RaiderState` save avatar name instead of NameWithHash

Check preivous execute block index in `Raid` action.

---

.Lib9c.Tests/Action/ExceptionTest.cs
.Lib9c.Tests/Action/RaidTest.cs
Lib9c/Action/Raid.cs
Lib9c/Action/RequiredBlockIntervalException.cs

use `RequiredBlockIntervalException` for client avoid wrong render exception.

Introduce RequiredBlockIntervalException for render client exc

---

.Lib9c.Tests/Model/ItemNotificationTest.cs
Lib9c/Extensions/EquipmentExtensions.cs
Lib9c/Model/Item/Inventory.cs

- Fix inventory notification
The inventory notification(red dot) appears when the player doesn't equip the best equipments.
but, item requirement level check was not included in the best equipment.
- **Fix notification check, add equipment extention** (get requirment level)
- 9c PR : https://github.com/planetarium/NineChronicles/pull/1999
1. Equip all best equipments.
2. Check the inventory icon of header menu has not red dot.
[CP가 높더라도 장착불가 템이면 인디케이터 안보여줘야 하는데, 인벤토리 아이콘에서 인디케이터를 보여주는 문제](https://app.asana.com/0/1141562434100787/1202619716401117/f)

Fix inventory notification

---

Lib9c/Action/ITransferAsset.cs
Lib9c/Action/TransferAsset.cs
Lib9c/Action/TransferAsset0.cs
Lib9c/Action/TransferAsset2.cs

This pull request just do only `transfer_asset*` actions implement common interface, `ITransferAsset`. Fortunately. their variables organizations are all same so it was easy. It is related with #1406.
I requested a review for @ipdae because he made `transfer_asset3` and I want to request a check about it.

Make `transfer_asset*` actions implement common interface

---

.Lib9c.Tools/Program.cs
.Lib9c.Tools/SubCommand/Account.cs
.Lib9c.Tools/SubCommand/Action.cs
.Lib9c.Tools/SubCommand/Market.cs
.Lib9c.Tools/SubCommand/State.cs
.Lib9c.Tools/SubCommand/Tx.cs

Commands in `lib9c.Tools` is bound to NineChronicles and `NineChronicles.Headless` already has several commands.
This PR deprecates `lib9c.Tools` commands and move to `NineChronicles.Headless`. 
Related Issue: https://github.com/planetarium/NineChronicles.Headless/pull/1602

Obsolete Lib9c.tools with warning message

---

Lib9c/Model/State/CrystalRandomSkillState.cs

use `.First()` for avoid `InvalidBlockStateRootHashException`

fix GetHighestRankSkill

---

Lib9c/Model/State/StateExtensions.cs

Use `ByteArray` instead of `ToByteArray()` when appropriate

---

Lib9c.MessagePack/Action/NCActionEvaluation.cs
Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
Lib9c.MessagePack/Formatters/NCActionFormatter.cs
Lib9c.MessagePack/Formatters/NineChroniclesResolver.cs
Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
Lib9c.MessagePack/Lib9c.MessagePack.csproj
Lib9c.Miner/Lib9c.Miner.csproj
Lib9c.Miner/Miner.cs
Lib9c.Miner/ReorgMiner.cs

This pull request turns on `TreatWarningsAsErrors` in the below projects:
- Lib9c.Miner
- Lib9c.MessagePack

Turn on `TreatWarningsAsErrors` feature

---

.github/workflows/main.yml
.github/workflows/publish.yml

See https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

ci(gh-actions): upgrade actiosn used node12

---

.Lib9c.Tests/Action/RewardGoldTest.cs

Fix unit test: RewardGoldTest.Genesis_StateRootHash()
The `https://9c-test.s3.ap-northeast-2.amazonaws.com` url has become private.

Fix url of genesis block in test

---

.Lib9c.Tests/TableSheetsImporter.cs

In commit 551e0b8, we deleted the argument `path` to find TableCSV path with intelligence.
But in another projects, those paths are not enough to get csv files.
To resolve this, accept `path` argument again.

Revert 551e0b8 to accept path from another projects

---

Lib9c.Abstractions/IActivateAccount.cs
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.Miner/Miner.cs
Lib9c.sln
Lib9c/Action/ActivateAccount.cs
Lib9c/Action/ActivateAccount0.cs
Lib9c/Lib9c.csproj
Lib9c/Policy/BlockPolicySource.Utils.cs
Lib9c/Policy/BlockPolicySource.cs

This pull request makes `BlockPolicySource` check actions through `ITransaction.CustomActions`, not been instantiated yet. Also, it makes `Miner` discard (i.e., unstage) transactions not available in the next block when the `IActionTypeLoader` is given.

Check raw custom actions in `BlockPolicySource`

---

Lib9c/Helper/Validator.cs

When you play the `HackAndSlash` with world(1) and stage(7) and if your `AvatarState` has cleared the world(1) and stage(5) yet. The `InvalidStageException` will be occurred with some message.
This pull request fix the message. And separates the conditions for readability.
Before
> conditions: !world.IsStageCleared && stageId != world.StageBegin || world.IsStageCleared && stageId - 1 > world.StageClearedId
> format: {addressesHex}Aborted as the stage ({worldId}/{stageId}) is not cleared; cleared stage: {world.StageClearedId}
> output: Aborted as the stage (1/7) is not cleared; cleared stage: 5
The "(1/7)" part is confusing.
After
> condition: !world.IsStageCleared && stageId != world.StageBegin
> format: {addressesHex}Aborted as the stage ({worldId}/{stageId - 1}) is not cleared; clear …

Fix exception message

---

.Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
.Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
Lib9c/Action/Factory/FaucetFactory.cs
Lib9c/Action/FaucetCurrency.cs
Lib9c/Action/FaucetRune.cs
Lib9c/Action/Interface/IFaucetCurrency.cs
Lib9c/Action/Interface/IFaucetRune.cs
Lib9c/Lib9c.csproj

Add dev/test only actions (Faucet~~~) to Lib9c form Lib9c.DevExtensions.
This is because direct import of Lib9c.DevExtensions causes circular dependency.
Faucet actions are only included in the build if the "TEST_9C" DefineConstants is present.

Add faucet actions to Lib9c

---

Lib9c/Policy/BlockPolicySource.cs

The `NCAction` type is same with `PolymorphicAction<T=ActionBase>` type. The `PolymorphicAction<T>` type is in `Libplanet` assembly. So it doesn't reference `Lib9c` and it fails to find actions.

Correct assebmly's path

---

Lib9c/Policy/BlockPolicySource.cs

Before this pull request, `BlockPolicySource` doesn't load plain value of `activate_account` actions so the actions' `PendingAddress` returns `0x0000000000000000000000000000000000000000` instead to throw errors.

Load plain value when loading `activate_account` actions

---

Lib9c/Lib9c.csproj

This pull request is for *Pluggable Lib9c*. It needs `EnableDynamicLoading` and link `libplanet` in runtimes.

Enable `EnableDynamicLoading`

---

Lib9c/Policy/BlockPolicySource.Utils.cs
Lib9c/Policy/BlockPolicySource.cs

`SetValidator` system action with invalid `validatorAdmin` from policy will be unstaged automatically.

Unstage SetValidator action with invalid validatorAdmin

---

.Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs

- Fix de/serialization bug.
- Add zero arguments constructor.
- Inherit `IAction` on `ICreateOrReplaceAvatar` interface.

[DevEx]Bug fix of `CreateOrReplaceAvatar`

---

.Lib9c.Tests/StagePolicyTest.cs

To prevent test failure, extending tx lifetime to sufficient length is needed.
There are some ways to prevent failure, but I think this way is better, since those tests are assuming to be finished within tx lifetime.

Extend tx lifetime on tests

---

.Lib9c.Tests/StagePolicyTest.cs

The default `StagePolicy`'s `Transaction<T>` lifetime has reduced to 10 minutes. Because of this change, `StagePolicyTest` fails due to `Transaction<T>` fixtures getting expired.

Fixed tests failing occasionally due to long running time

---

Lib9c.Miner/Miner.cs

The `Miner` in the `Lib9c.Miner` project validates staged transactions, and discard(unstage) invalid transactions to exclude them from a new block to mine. But `BlockChain<T>.Unstage` calls `VolatileStagePolicy.Unstage` and it removes it from the staged transactions' set. And another staging request can be accepted.
This pull request makes `Miner` avoid including invalid transactions while mining a new block by ignoring them.

Ignore invalid txs

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
.Lib9c.Tests/Action/ExceptionTest.cs
.Lib9c.Tests/Action/RegisterProductTest.cs
Lib9c/Action/AssetInfo.cs
Lib9c/Action/IRegisterInfo.cs
Lib9c/Action/InvalidCurrencyException.cs
Lib9c/Action/InvalidProductTypeException.cs
Lib9c/Action/ProductInfo.cs
Lib9c/Action/RegisterInfo.cs
Lib9c/Action/RegisterProduct.cs
Lib9c/Addresses.cs
Lib9c/Model/Market/FavProduct.cs
Lib9c/Model/Market/ItemProduct.cs
Lib9c/Model/Market/Product.cs
Lib9c/Model/Market/ProductFactory.cs
Lib9c/Model/Market/ProductReceipt.cs
Lib9c/Model/Market/ProductType.cs
Lib9c/Model/Market/ProductsState.cs
Lib9c/Model/State/MarketState.cs

It has the avatar addresses who registered product in the market. It will used when searching for all `ProductsState`.(corresponding to `ShardedShopState`)
Each AvatarState will have it own a list of registered ProductIds.(corresponding to `OrderDigestListState`)
registered item, FungibleAssetValue information. (corresponding to `Order, ShopItem`)
register item or FungibleAssetValue to market. (corresponding to `Sell`)
It is used for registering item to the market. 
It is used for registering FungibleAssetValue to the market.
It is used for find registered product in the market.
- The difference with the existing Order model is that instead of copying the item, it completely moves the item (or FungibleAssetValue) to product address.
- IRegisterInfo(RegisterInfo, AssetInfo) & ProductInfo …

Introduce market models & register action

---

Lib9c.Policy/Lib9c.Policy.csproj
Lib9c.Renderers/ActionEvaluation.cs
Lib9c.Renderers/Lib9c.Renderers.csproj
Lib9c.Utils/Lib9c.Utils.csproj

Sadly, Unity 2021.3.5f1 doesn't support C# 10 so this pull request disables the `ImplicitUsings` feature.

Disable global usings to support Unity

---

.Lib9c.Tests/Action/SecureMiningRewardTest.cs
Lib9c.Abstractions/ISecureMiningReward.cs
Lib9c/Action/SecureMiningReward.cs

This PR introduces `SecureMiningReward` to retrieve NCG from authorized miners to arbitrary addresses, for [NCIP-10](https://docs.google.com/document/d/1ErZ5JQia03KqXRG6IRZ7SORfnxMLZfJg4patVKFGX5Y/edit).

Introduce SecureMiningReward action

---

Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
Lib9c.Policy/Policy/BlockPolicySource.cs
Lib9c/Action/ActionObsoleteAttribute.cs

Internally, there are two places using `index`, namely `IsObsolete()` (which also internally uses `IActionTypeLoader.Load()`) and `IActionTypeLoader.Load()`. At a glance, seems like this should be fine.
- ~~`IsObsolete()`: If an action is obsoleted at certain index and permanently onwards, passing in a higher index should be fine, as this results in a more lax condition.~~
- ~~Suppose some action $X$ was supposed to be obsoleted at block $n$. Before, with **wrong implementation**, action $X$ would've been banned starting from block $n - 1$. Policy is enforced as long as $X$ is not in block $n$.~~
- As @moreal has pointed out below, this line of reasoning is flawed.
- `IActionTypeLoader.Load()`: This is also used inside `Miner.MineBlockAsync()` with a **proper** block index. So blocks were …

🔧 Fixed index used for policy

---

.Lib9c.Tests/Action/TransferAsset2Test.cs
Lib9c/Action/TransferAsset2.cs

- related with #1718 .
- Even if the set block height (622,000) is reached, crystal transfer with TransferAsset2 is still possible. to avoid this problem, prevent the execution of TransferAsset2 from the set height.

obsolete transfer asset2

---

.github/workflows/main.yml
Lib9c.DevExtensions/Utils.cs

I opened this pull request to check it is compatible with Unity and the `DevEx` environment automatically without a situation to hold developers accountable. 🙄 
The job enforces the `netstandard2.1` target for the `Lib9c*/*.csproj` and `Libplanet*/*.csproj` projects. It became a .net 6 project but the planetarium/NineChronicles project is still using `Lib9c` as a submodule. So it should check Unity(netstandard2.1) compatibility. See #1752 case.
Maybe, since #1734, the `LIb9c` build with the `DevEx` configuration was broken but not caught in CI. This pull request makes CI do it.

Check whether the build passed or failed in several configurations and frameworks

---

.Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
.Lib9c.Tests/Action/AccountStateViewExtensionsTest.cs
.Lib9c.Tests/Action/Coupons/CouponsFixture.cs
.Lib9c.Tests/Action/Coupons/IssueCouponsTest.cs
.Lib9c.Tests/Action/Coupons/RedeemCouponTest.cs
.Lib9c.Tests/Action/Coupons/TransferCouponsTest.cs
.Lib9c.Tests/Action/TransferAsset2Test.cs
.Lib9c.Tests/Model/Coupons/CouponTest.cs
.Lib9c.Tests/Model/Coupons/RewardSetTest.cs
Lib9c/Action/AccountStateDeltaExtensions.cs
Lib9c/Action/AccountStateViewExtensions.cs
Lib9c/Action/Coupons/IssueCoupons.cs
Lib9c/Action/Coupons/RedeemCoupon.cs
Lib9c/Action/Coupons/TransferCoupons.cs
Lib9c/Action/TransferAsset2.cs
Lib9c/Model/Coupons/Coupon.cs
Lib9c/Model/Coupons/RewardSet.cs
Lib9c/SerializeKeys.cs

A `Coupon` is non-fungible (interpretation: having a unique identifier) and consists of `RewardSet`, a list of `ItemId`s with their quantities.
Every `Agent` has their own coupon wallet to store `Coupon`s that are not redeemed yet.  An `IssueCoupon` action, which takes a `RewardSet` and a recipient, creates a new `Coupon` and then places it inside the recipient's wallet.  Once a `Coupon` is redeemed using a `RedeemCoupon` action, it's destroyed in the agent's wallet and then the promised rewards become added in their inventory.
If necessary `Coupon`s can be transferred to another recipient using a `TransferCoupon` action.  However, once redeemed `Coupon`s cannot be transferred of course.
Actions `IssueCoupon` and `TransferCoupon` can deal with multiple `Coupon`s at a time.  However, …

New coupon system to replace existing redeem code

---

.Lib9c.DevExtensions.Tests/Action/Craft/UnlocakCraftActionTest.cs
.Lib9c.DevExtensions.Tests/Action/Craft/UnlockRecipeTest.cs
.Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
.Lib9c.DevExtensions.Tests/Action/Stage/ClearStageTest.cs
.Lib9c.Tests/Util/InitializeUtil.cs
Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
Lib9c.DevExtensions/Action/Craft/UnlockRecipe.cs
Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
Lib9c.DevExtensions/Action/ManipulateState.cs
Lib9c.DevExtensions/Action/Stage/ClearStage.cs
Lib9c/Model/Quest/QuestList.cs
Lib9c/Model/State/StateExtensions.cs

- `ManipulateState` action force sets given state to given address.
- This function assumes given address and state are in pair.
- This function assumes given state is valid.
- Add state editor to unity editor and use this action to save changed state
---
- `InitializeUtil` now can handle and create inits for DevEx tests.
- `UnlockCraftAction` can unlock craft related action by clearing required stage.
- `UnlockRecipe` can unlock Item reipe to craft.
- `UnlockStage` can unlock stages to test specific stage easily.
I wonder I did right thing to set new WorldInformation to clear stage at `ClearStage.cs` workaround.

Introduce `ManipulateState` action for easier test environment setting

---

.github/workflows/main.yml

Since v100370, the `v*/all_action_type_ids.txt` begins to include a .NET command warning message. (I'm not sure why the warning messages are in stdout, not stderr 🙄 ...) This pull request makes the job suppress the warning message by controlling the [`WarningLevel`][warning-level] property as zero.
(I asked for reviews from those who know this context.)
[warning-level]: https://learn.microsoft.com/ko-kr/dotnet/api/microsoft.build.tasks.csc.warninglevel?view=netframework-4.8.1#microsoft-build-tasks-csc-warninglevel

Suppress warnings while collecting action type ids

---

.Lib9c.Tests/Action/SecureMiningRewardTest.cs
Lib9c/Action/SecureMiningReward.cs

Currently, non-minter accounts can't burn FAV (like NCG) due to Libplanet policy, even if they're admin accounts in 9c.  so this PR amends the burning semantic (from `burnAsset` to `transfer` to nil address), on `SecureMiningReward`, introduced by #1720. 
I think it doesn't need a hard fork because no action has been processed on the mainnet by the admin account that would cause state diff.

Fix burn behavior in SecureMiningReward to transferring

---

.Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
.Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
.Lib9c.Tests/Action/ClaimRaidRewardTest.cs
.Lib9c.Tests/Action/ClaimWorldBossKillRewardTest.cs
.Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
.Lib9c.Tests/CurrenciesTest.cs
Lib9c.sln.DotSettings
Lib9c/Currencies.cs
Lib9c/Helper/CrystalCalculator.cs
Lib9c/Helper/PetHelper.cs
Lib9c/Helper/RuneHelper.cs

- The class `Currencies` summarizes all currencies like `Addresses`.
- Use `Currencies.Crystal` from `CrystalCalculator.CRYSTAL`.
- Use `Currencies.StakeRune` and `Currencies.DailyRewardRune` from `RuneHelper.StakeRune` and `RuneHelper.DailyRewardRune`.
- Use `Currencies.GetRune(ticker)` from `RuneHelper.ToCurrency(runeRow)` and `RuneHelper.ToFungibleAssetValue(runeRow, quantity)`.
- Use `Currencies.GetSoulStone(ticker)` from `PetHelper.GetSoulstoneCurrency(ticker)`.
- Remove the `decimalPlaces` and `minters` parameters as they are always `0` and `null`.

feat: Introduce `Currencies`

---

.Lib9c.Tests/Action/ActionBaseExtensionsTest.cs
Lib9c/Action/ActionBaseExtensions.cs

This PR adds `.CalculateUpdatedAddresses()` to `IEnumerable<PolymorphicAction<ActionBase>>` and `IEnumerable<ActionBase>` to get updated addresses handy.
- This feature isn't necessary for Libplanet 1.0.* yet, because [it will be calculated on `Transaction<T>.Create()`](https://github.com/planetarium/libplanet/blob/1.0.0/Libplanet/Tx/Transaction.cs#L431-L432). 
- But also, Libplanet has planned to remove auto calculation since it isn't realistic to compute all through previous states to make a transaction, and complicates the implementation. 
- see also: 
- https://github.com/planetarium/libplanet/issues/368
- https://github.com/planetarium/libplanet/pull/3122
- However even now, 'UpdatedAddresses' are automatically written in transactions on 9c mainnet. 
- This is possible because most …

Calculate UpdatedAddresses on Lib9c side

---

Lib9c/Action/SellCancellation.cs

https://9cscan.com/tx/9f736e20b2ce8dd923898e0be0b95c582defd0a76156368ffe976bdfacf1d1db
This `SellCancellation9` action failed in the mainnet cannonical chain but it actually succeeds when executing it with our current lib9c version and returns an `InvalidStateRootHashException`. This is a fix to manually skip this action and resolve the `InvalidStateRootHashException` error (I've used this to move on to the next block evaluation while doing other work).

fix `SellCancellation9` invalidstateroothashexception from #6166598

---

Lib9c/Model/Buff/BuffFactory.cs
Lib9c/Model/Character/ArenaCharacter.cs
Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
Lib9c/Model/Skill/AttackSkill.cs
Lib9c/Model/Skill/HealSkill.cs
Lib9c/TableCSV/Skill/SkillSheet.csv
Lib9c/TableCSV/Skill/StatBuffSheet.csv
Lib9c/TableData/Skill/SkillSheet.cs
Lib9c/TableData/Skill/StatBuffSheet.cs

[How to apply (internal document)](https://www.notion.so/planetarium/a48947f47bcc4b1093342d81a1c6a9ae)
- `StatBuffSheet.Row.ReferencedStatType` is removed.
- Instead, `SkillSheet.Row.StatPowerRatio` decides the additional power of a skill.
- `SkillSheet.Row.ReferencedStatType` specifies the referenced `StatType` of the value.
- When referenced `StatType` is specified : `Skill.Power = original power + (referenced stat * (StatPowerRatio / 10000))`
- When referenced `StatType` not specified, nothing happens. Skill will be used with original power.

Apply bonus damage on skill based on stat

---

Lib9c/Model/Stat/CharacterStats.cs

Specify minimum stat values on each StatTypes to prevent `DivideByZeroException`.

Specify minimum stat values on each StatTypes.

---

Lib9c/Action/ClaimStakeReward1.cs
Lib9c/Action/Stake0.cs

This pull request is from #1963. The #1963 's purpose was to shift all obsolete indexes became meaningless to the new index. But some actions were obsoleted too, though they weren't obsoleted in the v200020 version, by my mistake. This pull request recovers them.

Repair incorrectly modified indexes

---

Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
Lib9c.Policy/Policy/BlockPolicySource.cs

⬆️ 
`IncompleteBlockStatesException` has been removed from libplanet. I'm not sure the old patchwork made in https://github.com/planetarium/lib9c/pull/151#discussion_r506039478 is still relevant. 🤨

⬆️ Bump libplanet to 2.1.0

---

.Lib9c.Tests/Action/ClaimStakeReward3Test.cs
.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
.Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
.Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
.Lib9c.Tests/Model/State/StakeStateTest.cs
Lib9c/Action/ClaimStakeReward.cs
Lib9c/Action/ClaimStakeReward1.cs
Lib9c/Action/ClaimStakeReward2.cs
Lib9c/Action/ClaimStakeReward3.cs
Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
Lib9c/Model/State/StakeState.cs

- Make `claim_stake_reward3` action obsolete at `ActionObsoleteConfig.V200030ObsoleteIndex`.
- Introduce `claim_stake_reward4` action as `ClaimStakeReward`.

Upgrade ClaimStakeReward action from 3 to 4

---

.Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
.Lib9c.Tests/Action/ActivateAccount0Test.cs
.Lib9c.Tests/Action/AddActivatedAccount0Test.cs
.Lib9c.Tests/Action/AddActivatedAccountTest.cs
.Lib9c.Tests/Action/AddRedeemCodeTest.cs
.Lib9c.Tests/Action/CreatePendingActivationTest.cs
.Lib9c.Tests/Action/CreatePendingActivationsTest.cs
.Lib9c.Tests/Action/MigrationActivatedAccountsStateTest.cs
.Lib9c.Tests/Action/MigrationAvatarStateTest.cs
.Lib9c.Tests/Action/MockState.cs
.Lib9c.Tests/Action/MockStateDelta.cs
.Lib9c.Tests/Action/PatchTableSheetTest.cs
.Lib9c.Tests/Action/RenewAdminStateTest.cs
.Lib9c.Tests/Action/SecureMiningRewardTest.cs
.Lib9c.Tests/Action/TransferAsset2Test.cs
.Lib9c.Tests/Action/TransferAsset3Test.cs
.Lib9c.Tests/Action/TransferAssetTest.cs
.Lib9c.Tests/Action/TransferAssetTest0.cs
.Lib9c.Tests/Action/TransferAssets0Test.cs
.Lib9c.Tests/Action/TransferAssetsTest.cs
.Lib9c.Tests/Action/ValidatorSetOperateTest.cs

- ~~`IAction.Execute()` should now run with clean `IAccountStateDelta`s~~
- It was allowed to add FAVs that didn't make sense. This is no longer the case.
- For example, it was possible to "add" `(addressA, currencyB, favC)` where `favC.Currency` was not `currencyB`.
----
Addemdum: The first point isn't true yet. I'll bring `MockStateDelta` up to date with a separate PR.

✨ Added `MockState` for testing

---

.Lib9c.Tests/TableData/Garages/LoadIntoMyGaragesCostSheetTest.cs
Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
Lib9c/TableData/Garages/LoadIntoMyGaragesCostSheet.cs

fix: delete `CostKind` column

---

.github/workflows/main.yml

- Send `9c` bump PR to upstream (resolve license issue during CI build)
- Also send bump PR to `market-service`

Update submodule updater

---

Lib9c/Action/CreateAvatar8.cs
Lib9c/ActionObsoleteConfig.cs

Set obsolete create_avatar8

---

.github/workflows/lint.yml
Lib9c.Policy/Policy/IVariableSubPolicy.cs
Lib9c/Action/EventMaterialItemCrafts.cs
Lib9c/Action/ValidatorSetOperate.cs
_typos.toml

This pull request is related with https://github.com/planetarium/lib9c/pull/1155.
This pull request introduces a new GitHub Actions workflow to check typos automatically.
You can see the configuration file's spec at [crate-ci/typos@master/docs/reference.md#config-fields](https://github.com/crate-ci/typos/blob/master/docs/reference.md?rgh-link-date=2023-07-25T02%3A20%3A56Z#config-fields).
You can correct typos easily by running `typos . -w`.
- Anyone related to lib9c 👀

ci(gh-actions): check typos in GitHub Actions

---

.github/workflows/push_docker_image.yaml
Dockerfile.amd64
Dockerfile.arm64v8

This pull request continues https://github.com/planetarium/NineChronicles.Headless/pull/2164.

ci(gh-actions): build Docker image

---

.Lib9c.Tests/Action/BuyMultipleTest.cs
.Lib9c.Tests/Model/Item/ArmorTest.cs
.Lib9c.Tests/Model/Item/BeltTest.cs
.Lib9c.Tests/Model/Item/ConsumableTest.cs
.Lib9c.Tests/Model/Item/EquipmentTest.cs
.Lib9c.Tests/Model/Item/InventoryTest.cs
.Lib9c.Tests/Model/Item/NecklaceTest.cs
.Lib9c.Tests/Model/Item/ShopItemTest.cs
.Lib9c.Tests/Model/ItemGradeQuestTest.cs
.Lib9c.Tests/Model/ItemTypeCollectQuestTest.cs
.Lib9c.Tests/Model/QuestRewardTest.cs
Lib9c/Action/AccountStateExtensions.cs
Lib9c/Action/HackAndSlash.cs
Lib9c/Model/Item/ItemBase.cs
Lib9c/Model/Item/ItemUsable.cs
Lib9c/Model/Mail/Mail.cs
Lib9c/Model/Quest/CombinationEquipmentQuest.cs
Lib9c/Model/Quest/CombinationQuest.cs
Lib9c/Model/Quest/GoldQuest.cs
Lib9c/Model/Quest/ItemEnhancementQuest.cs
Lib9c/Model/Quest/Quest.cs
Lib9c/Model/Quest/QuestReward.cs
Lib9c/Model/Quest/TradeQuest.cs
Lib9c/Model/State/AvatarState.cs

AS-IS
TO-BE
---
reduce HackAndSlash.Execute from avg 134.7ms -> 60.5ms(in target block) with AvatarState deserialize / serialize with lazy-load

Optimize HackAndSlash.Execute #2

---

.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/validate-github-actions-workflows.yml

ci(gh-actions): correct GitHub Actions workflow syntax

---

Lib9c/Lib9c.csproj

This pull request specifies the version of Lib9c library as 0.4.0, the next release version 👀

chore: specify version for Lib9c package

---

.Lib9c.Tests/Action/ValidatorSetOperateTest.cs
Lib9c/Action/GameAction.cs
Lib9c/Action/ValidatorSetOperate.cs

Quick notes:
- Changed `GameAction.PlainValue` and `GameAction.LoadPlainValue()` to be `sealed` to prevent future mistakes.
- `ValidatorSetOperator` now inherits directly from `ActionBase` instead of `GameAction`.
- If any `ValidatorSetOperator` has seeped into existing chain since `TypedActionLoader` was introduced, we'll have modify `BlockPolicy` to retroactively comply with policy. This issue becomes substantially more complicated to deal with.

🐛 Fix `ValidatorSetOperate`

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
Lib9c/Action/ClaimStakeReward.cs
Lib9c/Action/ClaimStakeReward7.cs
Lib9c/ActionObsoleteConfig.cs
Lib9c/Currencies.cs

- add summary to `Currencies.GetMinterlessCurrency()` method.
- add comments to "claim_stake_reward8" action.
- rename `ActionObsoleteConfig.V200062ObosleteIndex` to `V200063ObosleteIndex`.
- add unit test cases of "claim_stake_reward8" to check the v3 rewards.

Improve claim stake reward8

---

Dashboard/src/App.tsx

SSIA. It resolves https://github.com/planetarium/lib9c/issues/2140. After this pull request, the `VITE_API_PATH` secret should be updated.

feat(Dashboard): use 9c-headless instead of empty-chronicle

---

.github/workflows/publish.yml

publish Lib9c.Abstractions for fix depedency exception use Lib9c in other projects.

Fix nuget published lib9c dependency

---

.Lib9c.Tests/Action/ClaimItemsTest.cs

Since https://github.com/planetarium/lib9c/pull/2169, `ClaimItems.ClaimData` doesn't sort its `ClaimData` anymore. The pull request didn't apply that change to tests either. This pull request does it.

Do not sort `ClaimItems.ClaimData` in tests

---

Lib9c.Policy/AccessControlService/IAccessControlService.cs
Lib9c.Policy/NCStagePolicy.cs

- Add `GetTxQuota` method to `ACS` to check a signer's individual `txQuotaPerSigner` when staging txs.
Replaces https://github.com/planetarium/lib9c/pull/2191.

add GetTxQuota to ACS

---

.Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
Lib9c.Abstractions/IUnloadFromGaragesV1.cs
Lib9c/Action/Garages/UnloadFromGarages.cs

Add `UnloadFromGarages` action with data structure and serialize/deserialize code.
Implementation of execution will be added following PR.

PDX-19: Add UnloadFromGarages Action

---

.Lib9c.Tests/Action/ClaimItemsTest.cs
Lib9c/Action/ClaimItems.cs

See PDX-37 card and [internal slack conversation](https://planetariumhq.slack.com/archives/C03PJ5CG30C/p1698982821799689). The limitation prevents the `ClaimItems` to take too long evaluation time since 9c network doesn't have a fee model.

Limit ClaimItems.ClaimData's size to 100

---

.Lib9c.Tests/Action/InitializeStatesTest.cs
.Lib9c.Tests/Action/RewardGoldTest.cs
.Lib9c.Tests/Model/State/GoldCurrencyStateTest.cs
Lib9c/Action/InitializeStates.cs
Lib9c/Action/RewardGold.cs
Lib9c/Model/State/GoldCurrencyState.cs

This PR allows empty initial NCG supply, for planets governing under derived tokenomics.

Allow empty NCG vault

---

.Lib9c.Tests/Action/MintAssetsTest.cs
Lib9c/Action/MintAssets.cs

This PR has two changes as below
1. Adds `MintAssets.Memo` for output mails
2. Makes `MintAssets.Execute()` to care about `AvatarState.MailBox` as like `UnloadFromMyGarages` action.
* it reuses `UnloadFromMyGaragesRecipientMail` 😓 .
* I'm not a big fan of current mail system, especially spoiling output states. but on the other hands, I don't know about current client's behavior which relying states. so I decided mimics `UnloadFromMyGarages` as possible.

Fit `MintAssets` to mail system

---

Lib9c.Policy/NCStagePolicy.cs

I made a mistake assuming that `Iterate()` is only used when staging transactions. Placing `_accessControlService?.GetTxQuota(tx.Signer)` inside `Iterate()` caused the headless node to call on ACS in other cases like `GetNextTxNonce` and `BroadcastTxAsync()`.
This prevents the node from unnecessarily calling ACS so that ACS is called only when staging. The custom quota is separately stored in `_quotaPerSignerList` as a reference point during the iteration.

do not call ACS when iterating chain

---

.github/workflows/lib9c_plugin_build_and_push_s3.yaml

`Lib9c.Plugin` is not yet exist but will prepared.

🔀  ci: for plugin upload

---

.Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs

In [this commit](https://github.com/planetarium/lib9c/commit/f64a986cafac7c58d6f8be3e43f3af9268f69ebc#diff-7f5f43e147607066a3205ef1e1faa8a6be1a08d45cf003b7bf50b4c373af0023L44-R47), `RemoteBlockChainStates.GetAccountState(BlockHash?)` was implemented as throwing not implemented exception. But the method seems equal to the `GetBlockState(BlockHash?)` method. So this PR renames `GetBlockState` to `GetAccountState`.

🔨 Correct `RemoteBlockChainStates` implementation

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
Lib9c.MessagePack/Action/NCActionEvaluation.cs
Lib9c.MessagePack/Formatters/TxIdFormatter.cs

So, the `ActionEvaluation` data provided during the `OnRender` call now includes `TxIds`.

add txid to messagepack

---

Lib9c/Model/State/StakeRewardCalculator.cs

Before this pull request, it doesn't support `0.025` as decimal rates in `StakeRegularRewardSheet`. There was an error while parsing it as NCG FAV. But it is not necessary to parse the value as NCG FAV. I think it is just to use `FungibleAssetValue.DivRem` method. I replaced the logic with `new BigInteger(decimal / decimal)` to remove digits.
```
Unhandled exception. System.FormatException: The currency NCG (50778d9d92d8d76b325cc572dceb7d30d9887472) does not allow more than 2 decimal places
at Libplanet.Types.Assets.FungibleAssetValue.Parse(Currency currency, String value) in /path/tolib9c/.Libplanet/Libplanet.Types/Assets/FungibleAssetValue.cs:line 480
at Lib9c.Tools.Program.Main(String[] args) in /path/to/lib9c/.Lib9c.Tools/Program.cs:line 24
```

Support decimal rates of 3 or more digits

---

Lib9c/Lib9c.csproj

Currently, the GitHub Actions workflow deploys NuGet package when a commit is pushed to `development` and `main` branches. The published version is determined as `{VersionPrefix}-dev.{github.sha}`. So previous versions were `1.1.0-dev.somecommithash`. This pull request makes it correct.

Bump VersionPrefix to 1.8.0

---

.Lib9c.Tests/Action/MigrateAgentAvatarTest.cs
Lib9c/Action/MigrateAgentAvatar.cs

Replacement of https://github.com/planetarium/lib9c/pull/2420

Introduce MigrateAgentAvatar action

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
.Lib9c.Tests/Action/RetrieveAvatarAssetsTest.cs
Lib9c.MessagePack/Action/NCActionEvaluation.cs
Lib9c/Action/RetrieveAvatarAssets.cs

Implement NCIP-18

---

Lib9c/Model/BattleStatus/Arena/ArenaDoubleAttack.cs
Lib9c/Model/BattleStatus/Arena/ArenaDoubleAttackWithCombo.cs
Lib9c/Model/BattleStatus/DoubleAttackWithCombo.cs
Lib9c/Model/IArena.cs
Lib9c/Model/IStage.cs
Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
Lib9c/Model/Skill/DoubleAttack.cs

아레나쪽에 신규스킬 트윈어택 연출을위해서 추가한내용입니다.

add skillId in arena double attack

---

.Lib9c.Tests/Action/HackAndSlashTest.cs

See #2424 for context. This is a rather serious issue considering we haven't had a proper test since `release/1.7.0`. Considering the size and scope of changes made in `release/1.8.0` (libplanet 4.0 update), we should consider ourselves lucky that there wasn't a major problem pertaining to this particular issue.
`HackAndSlashTest.cs` in this PR was taken from `release/1.6.0` version of `HackAndSlash21Test.cs` and modified to fit the current `IWorld` API. See 4468a5269db768cdfd552200e2ed1895289f4482 for the actual changes.
I have removed some tests concerning old `AvatarState` model for following reasons:
- It will soon no longer be relevant once the migration process is over.
- Currently, making of an outdated `AvatarState` is not supported by the API.
- Whether an `AvatarState` is …

🦺 Restore `HackAndSlashTest.cs`

---

.Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
Lib9c/Model/Buff/StatBuff.cs

- fix `StatBuff.IsDebuff` check when stat conversion skill case (power is 0. but custom field has value)

Fix stat conversion debuff check

---

Lib9c.MessagePack/Action/NCActionEvaluation.cs

- The removal of '#nullable disable' directives in several projects.
- Backward-incompatible network protocol changes due to some API type alterations.
- The introduction of new `RemoteKeyValueService` and `RemoteKeyValueStore` APIs.
- The optimization of ITrie.IterateNodes() to significantly reduce memory usage.
see more: [Libplanet 4.1.0 Release Note](https://github.com/planetarium/libplanet/releases/tag/4.1.0)

🚀 bump: libplanet 4.1.0

---

.Lib9c.Tests/Action/Common/MockWorldState.cs
.Lib9c.Tests/Policy/BlockPolicyTest.cs
.Lib9c.Tools/SubCommand/Account.cs
.Libplanet.Extensions.RemoteBlockChainStates/RemoteAccount.cs
.Libplanet.Extensions.RemoteBlockChainStates/RemoteAccountState.cs
.Libplanet.Extensions.RemoteBlockChainStates/RemoteWorldState.cs
Lib9c.Policy/Policy/BlockPolicySource.cs
Lib9c/Action/RewardGold.cs
Lib9c/Module/LegacyModule.cs

⬆️ Bump libplanet to 4.2.0

---

.Lib9c.Tests/Action/DailyRewardTest.cs
Lib9c/Action/DailyReward.cs
Lib9c/Addresses.cs
Lib9c/Module/ActionPointModule.cs
Lib9c/Module/DailyRewardModule.cs

- resolve #2478 
- AP충전을 위해 AgentState, AvatarState 상태를 호출하는대신 별도 어카운트에 저장된 값을 사용합니다.
- GameConfigState대신 현재 메인넷기준값들을 상수로 설정합니다.
- 속도향상과 마이그레이션 용이성을 위해 마이그레이션 이전 상태들의 최초 1회는 DailyRewardReceivedBlockIndex값을 0으로 통과시켜줍니다.
---
실행속도 비교(304ms -> 30ms)
AS-IS
TO-BE

DailyReward 실행속도 향상

---

Lib9c/Action/CreateAvatar.cs

👻 Restore unity methods

---

.Lib9c.Tests/Action/DPoS/Control/RedelegateCtrlTest.cs
Lib9c/Action/DPoS/CancelUndelegation.cs
Lib9c/Action/DPoS/Control/Bond.cs
Lib9c/Action/DPoS/Control/DelegateCtrl.cs
Lib9c/Action/DPoS/Control/RedelegateCtrl.cs
Lib9c/Action/DPoS/Control/UnbondingSetCtrl.cs
Lib9c/Action/DPoS/Control/UndelegateCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorDelegationSetCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorPowerIndexCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorRewardsCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorSetCtrl.cs
Lib9c/Action/DPoS/Delegate.cs
Lib9c/Action/DPoS/PromoteValidator.cs
Lib9c/Action/DPoS/Redelegate.cs
Lib9c/Action/DPoS/Sys/AllocateReward.cs
Lib9c/Action/DPoS/Sys/UpdateValidators.cs
Lib9c/Action/DPoS/Undelegate.cs
Lib9c/Action/DPoS/Util/DPoSModule.cs
Lib9c/Action/DPoS/WithdrawDelegator.cs
Lib9c/Action/DPoS/WithdrawValidator.cs

- `DPoSModule` moved to `DPoS/Util`.
- `CancelUndelegation`, `Delegate`, `PromoteValidator`, `Relegate`, `Undelegate`, `WithdrawDelegator`, `WithdrawValidator` moved to `DPoS`.
- `DPoSBeginBlockAction` renamed to `AllocateReward` and moved to `DPoS/Sys`.
- `DPoSEndBlockAction` renamed to `UpdateValidators` and moved to `DPoS/Sys`.

Refactor DPoS actions

---

Lib9c/Action/DPoS/CancelUndelegation.cs
Lib9c/Action/DPoS/Delegate.cs
Lib9c/Action/DPoS/PromoteValidator.cs
Lib9c/Action/DPoS/Redelegate.cs
Lib9c/Action/DPoS/Undelegate.cs
Lib9c/Action/DPoS/WithdrawDelegator.cs
Lib9c/Action/DPoS/WithdrawValidator.cs

* Added the code `UseGas` to all DPoS-related Action.Execute
* The constructor access modifier for some actions is changed from internal to public.

Fix failing test by adding UseGas in DPoS

---

.Lib9c.Tests/Action/DPoS/Control/DelegateCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/RedelegateCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/UndelegateCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorPowerIndexCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorSetCtrlTest.cs
.Lib9c.Tests/Action/DPoS/DistributeTest.cs
.Lib9c.Tests/Action/DPoS/Model/RedelegationEntryTest.cs
.Lib9c.Tests/Action/DPoS/Model/UndelegationEntryTest.cs
.Lib9c.Tests/Action/DPoS/Model/ValidatorPowerTest.cs
.Lib9c.Tests/Action/DPoS/Model/ValidatorTest.cs
.Lib9c.Tests/Action/DPoS/PoSTest.cs
.Lib9c.Tests/Action/DPoS/ValidatorPowerComparerTest.cs
Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
Lib9c/Action/DPoS/Misc/Asset.cs
Lib9c/Action/DPoS/Model/Validator.cs

* Changed decimal places from 18 to 0 for ConsensusToken and Share 
- Therefore 1 NCG == 100 ConsensusToken == 100 Share
* Fixed build errors and test failures casued by refactoring decimal places.

Refactor decimal places of currency used in dpos.

---

.Lib9c.Tests/Action/DPoS/Control/EvidenceCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/SlashCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorDelegationSetCtrlTest.cs
.Lib9c.Tests/Action/DPoS/Control/ValidatorSigningInfoCtrlTest.cs
.Lib9c.Tests/Action/DPoS/PoSTest.cs
Lib9c/Action/DPoS/Control/DelegateCtrl.cs
Lib9c/Action/DPoS/Control/Environment.cs
Lib9c/Action/DPoS/Control/EvidenceCtrl.cs
Lib9c/Action/DPoS/Control/RedelegateCtrl.cs
Lib9c/Action/DPoS/Control/SlashCtrl.cs
Lib9c/Action/DPoS/Control/UnbondingSetCtrl.cs
Lib9c/Action/DPoS/Control/UndelegateCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorDelegationSetCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorPowerIndexCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorRewardsCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorSetCtrl.cs
Lib9c/Action/DPoS/Control/ValidatorSigningInfoCtrl.cs
Lib9c/Action/DPoS/Model/Delegation.cs
Lib9c/Action/DPoS/Model/Evidence.cs
Lib9c/Action/DPoS/Model/Infraction.cs
Lib9c/Action/DPoS/Model/RedelegationEntry.cs
Lib9c/Action/DPoS/Model/UndelegationEntry.cs
Lib9c/Action/DPoS/Model/ValidatorSigningInfo.cs
Lib9c/Action/DPoS/Unjail.cs
Lib9c/Action/DPoS/Util/DPoSModule.cs

* Slashing -> SlashCtrl.Shash
* Jailing -> ValidatorCtrl.Jail
* Unjailing -> ValidatorCtrl.Unjail
* Tombstone -> ValidatorCtrl.Tombstone
* Penalties for double signing -> EvidenceCtrl
* SlashCtrlTest: Unit and senario test
* ValidatorSigningInfoCtrlTest: Unit test
* There is code(from cosmos) for infraction due to network latency, but it has not been tested.
* The code for the case where the slash factor is 100% is not implemented.
* The test code for the case where there is a remainder when dividing by a slash factor is not implemented.
* Very complex test code like delegate->redelegate->adelegate is not implemented.

Introduce slashing/jailing for DPoS

---

.Lib9c.Tests/Action/ActionContext.cs
.Lib9c.Tests/Action/RewardGoldTest.cs
.Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
Lib9c/Action/RewardGold.cs
Lib9c/Module/LegacyModule.cs

⬆️ Bump libplanet to 4.3.0

---

Lib9c/Action/HackAndSlashSweep.cs
Lib9c/Action/Raid.cs
Lib9c/Battle/CPHelper.cs

Stat increase by rune level bonus only affects to stat, not to CP.
This PR calculates stat CP based on rune level bonus.

Fix missing statCP by rune level bonus

---

.github/workflows/publish.yml

```
error: Failed to publish @planetarium/lib9c@0.1.0dev+f83c9e91742439b513d53e62b2b52c12c2fc0587
Caused by:
0: Failed to publish @planetarium/lib9c at 0.1.0dev+f83c9e91742439b513d53e62b2b52c[12](https://github.com/planetarium/lib9c/actions/runs/8928223465/job/24539098222#step:6:13)c2fc0587
1: The provided OIDC token is invalid: failed to parse 'aud': version must be normalized: expected 0.1.0-dev+f83c9e91742439b5[13](https://github.com/planetarium/lib9c/actions/runs/8928223465/job/24539098222#step:6:14)d53e62b2b52c12c2fc0587, got 0.1.0dev+f83c9e91742439b513d53e62b2b52c12c2fc0587 at line 1 column 239 (invalidOidcToken)[x-deno-ray: 75a910283a2d4ff20ad8b81de618cbe7]
```

Correct `@planetarium/lib9c` dev version suffix

---

.github/workflows/publish.yml

You can see https://github.com/planetarium/.github/blob/7da1714cbc9554aa17a19bc6477b8b067f714ea7/.github/workflows/publish_jsr.yaml

ci: publish @planetarium/lib9c with timestamp

---

@planetarium/lib9c/docs/.vitepress/config.ts
@planetarium/lib9c/docs/ko/index.md

Currently, it navigates to English `/docs` page even if you're in Korean page. This pull request fixes it.

Correct i18n nav

---

.Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
.Lib9c.Tests/Helper/AdventureBossHelperTest.cs
Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
Lib9c/Action/AdventureBoss/Wanted.cs
Lib9c/Addresses.cs
Lib9c/Helper/AdventureBossHelper.cs
Lib9c/Model/AdventureBoss/ExploreBoard.cs
Lib9c/Model/AdventureBoss/ExplorerList.cs
Lib9c/Module/AdventureBossModule.cs

- New model : ExplorerList
- In only has `HashSet<(Address, string)>` to store Explorers in this season.
- Move `ExploreBoard.ExplorerList` to `ExplorerList.Explorers`
- Introduce `ExplorerCount` into `ExploreBoard` model.
- This is kind of duplication but for efficiency.

Introduce ExplorerList model

---

Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
Lib9c/Action/AdventureBoss/UnlockFloor.cs
Lib9c/Action/AdventureBoss/Wanted.cs
Lib9c/Action/Exceptions/AdventureBoss/AlreadyClaimedException.cs
Lib9c/Action/Exceptions/AdventureBoss/ClaimExpiredException.cs
Lib9c/Action/Exceptions/AdventureBoss/InsufficientStakingException.cs
Lib9c/Action/Exceptions/AdventureBoss/InvalidAdventureBossSeasonException.cs
Lib9c/Action/Exceptions/AdventureBoss/InvalidBountyException.cs
Lib9c/Action/Exceptions/AdventureBoss/MaxInvestmentCountExceededException.cs
Lib9c/Action/Exceptions/AdventureBoss/PreviousBountyException.cs
Lib9c/Action/Exceptions/AdventureBoss/SeasonInProgressException.cs

- Test to handling exception in client
- All adventure boss exceptions are now Serializable

Move all adventure actions to inherit GameAction

---

Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs

Event floor Ids are in order.
So insert them to right order.

Fix floor order

---

.Lib9c.Tests/Policy/BlockPolicyTest.cs
Lib9c.Policy/Policy/BlockPolicySource.cs

- Fix not to use `GetNextWorldState()` on tx validation
- Reduce cache size of `HashNodeCache`

Fix not to use GetNextWorldState() on tx validation

---

.Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs

New sheet (BuffLinkSheet) is required to run IceSield / FrostBite.

Add missing BuffLinkSheet to AdventureBossSimulator

---

.Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
.Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs

Remove duplicated floor reward.
Remove reward inside simulator to calculate easier.
Also remove useless DropBox event log.

Remove duplicated floor reward

---

Lib9c/Lib9c.csproj

This pull request amends the `Version` property in `Lib9c/Lib9c.csproj` file to prepare the next release, `1.15.0`, because `1.14.0` version is already released.
It resolves #2682

Prepare 1.15.0

---

.github/workflows/main.yml
.github/workflows/publish.yml

Previously, it used the latest packages instead of those in the lockfile because the working directory wasn't specified correctly. This pull request fixes it.

ci(gh-actions): specify working directory

---

.Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
.Lib9c.Tests/Action/ActionContext.cs
.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tests/Policy/BlockPolicyTest.cs
.Lib9c.Tools/Lib9c.Tools.csproj
.Lib9c.Tools/SubCommand/State.cs
.Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
.Libplanet.Extensions.ActionEvaluatorCommonComponents/PreEvaluationBlockMarshaller.cs
.github/workflows/main.yml
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
Lib9c.Policy/Policy/DebugPolicy.cs
Lib9c.Proposer/Lib9c.Proposer.csproj
Lib9c.Proposer/Proposer.cs
Lib9c.sln
Lib9c/Lib9c.csproj
Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj

Evidence 는 합의과정에서 위반사항(대표적으로 이중서명)이 발생하였을때 해당 검증자의 처벌을 목적으로 증거를 남기는 기능입니다.
현재 운영되고 있는 노드 기준으로 위반이 발생할 확률이 없기 때문에 evidence 가 남지는 않습니다.
Evidence 기능에 의해 속성이나 매개변수가 추가되어서 발생하는 lib9c 빌드 오류 및 테스트 코드의 수정 사항이 포함되어 있습니다.
libplanet 의 프로젝트는 기존에 모두 Root 경로에 있었습니다. 유지보수 및 관리 차원에서 프로젝트의 속성별로 src, test, tools 경로로 이동되었습니다. 
따라서 lib9c 에서 참조하고 있는 이들의 경로에 대해서 수정 작업이 포함되어 있습니다.
netstandard2.1 과 net6.0 이 포함되었습니다. netstandard2.0 은 여전히 사용중입니다. 
unity 빌드를 위해 csproj 난 props 파일에 정의되어 있는 TargetFramework 를 netstandard2.1 으로 변경하는 명령어에 대한 수정작업이 포함되어 있습니다.

Bump libplanet to 5.1.2

---

Lib9c/Helper/AdventureBossHelper.cs

When total score is 0, contribution reward calculation logic could be broken.
Set reward to 0 NCG in this case.

Handle divide by zero issue

---

CODEOWNERS

Since @boscohyun doesn't work for this project, NineChronicles actively, I thought that he will receive too many review-requests and those will be too noisy. So this pull request removes him from CODEOWNERS list.
Of course, if @boscohyun wants to receive the notification, please just close this pull request 😉 
-------
In insider chat, we decided to remove all .Libplanet submodule codeowners.

Remove all .Libplanet submodule codeowners

---

Lib9c/Lib9c.csproj

Since [1.15.0](https://github.com/planetarium/lib9c/releases/tag/1.15.0) is released, this pull request bumps Lib9c version to 1.16.0

Prepare 1.16.0

---

.Lib9c.Tests/Action/Guild/AcceptGuildApplicationTest.cs
.Lib9c.Tests/Action/Guild/ApplyGuildTest.cs
.Lib9c.Tests/Action/Guild/BanGuildMemberTest.cs
.Lib9c.Tests/Action/Guild/CancelGuildApplicationTest.cs
.Lib9c.Tests/Action/Guild/MakeGuildTest.cs
.Lib9c.Tests/Action/Guild/QuitGuildTest.cs
.Lib9c.Tests/Action/Guild/RejectGuildApplicationTest.cs
.Lib9c.Tests/Action/Guild/RemoveGuildTest.cs
.Lib9c.Tests/Action/Guild/UnbanGuildMemberTest.cs
Lib9c/Action/Guild/AcceptGuildApplication.cs
Lib9c/Action/Guild/ApplyGuild.cs
Lib9c/Action/Guild/BanGuildMember.cs
Lib9c/Action/Guild/CancelGuildApplication.cs
Lib9c/Action/Guild/MakeGuild.cs
Lib9c/Action/Guild/QuitGuild.cs
Lib9c/Action/Guild/RejectGuildApplication.cs
Lib9c/Action/Guild/RemoveGuild.cs
Lib9c/Action/Guild/UnbanGuildMember.cs

It resolves #2726. When I created the issue, I thought that I should write code to check permission over all guild-related actions. But I turned to disable all guild-related actions except for `MakeGuild` and to make only `MakeGuild` check signer (`context.Signer == MeadConfig.PatronAddress`)

Disable guild operation related actions except for MakeGuild

---

.Lib9c.Tests/Action/Guild/MakeGuildTest.cs
.Lib9c.Tests/Action/Guild/Migration/GuildMigrationCtrlTest.cs
.Lib9c.Tests/Action/Guild/Migration/MigratePledgeToGuildTest.cs
.Lib9c.Tests/PolicyAction/Tx/Begin/AutoJoinGuildTest.cs
Lib9c/Action/Guild/GuildConfig.cs
Lib9c/Action/Guild/MakeGuild.cs
Lib9c/Action/Guild/Migration/Controls/GuildMigrationCtrl.cs
Lib9c/Action/Guild/Migration/MigratePledgeToGuild.cs

This pull request:
- Adjust Planetarium's guild owner address.
- Fix a serialization bug in `MigratePledgeToGuild`	 action (active migration action)

Adjust planetarium guild owner address

---

Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs

To patch table over 500KB, extend block policy to 1M

Extend Tx size limit from 500K to 1M

---

Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs

Heimdall block is rolled back due to snapshot reset.
Apply new policy from rolled back block index.

Apply heimdall internal snapshot reset

---

.Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
.Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
Lib9c/Action/AdventureBoss/Wanted.cs

To pick adventure bosses evenly, see latest 2 seasons and avoid them to pick new boss.

Select adventure boss avoiding latest 2 seasons

---

docs/docfx.json
docs/filter.yml

It excludes elements under `BTAI` namespace from DocFX docs. See https://dotnet.github.io/docfx/docs/dotnet-api-docs.html#filter-by-type for DocFX configuration.

Exclude BTAI from docs

---

.Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
.Lib9c.Tests/Action/Stake0Test.cs
.Lib9c.Tests/Action/Stake2Test.cs
.Lib9c.Tests/Action/StakeTest.cs
.Lib9c.Tests/Model/State/LazyStateTest.cs
Lib9c/Model/State/ActivatedAccountsState.cs
Lib9c/Model/State/AdminState.cs
Lib9c/Model/State/AgentState.cs
Lib9c/Model/State/AuthorizedMinersState.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/CombinationSlotState.cs
Lib9c/Model/State/CreditsState.cs
Lib9c/Model/State/GameConfigState.cs
Lib9c/Model/State/GoldBalanceState.cs
Lib9c/Model/State/GoldCurrencyState.cs
Lib9c/Model/State/MonsterCollectionState.cs
Lib9c/Model/State/MonsterCollectionState0.cs
Lib9c/Model/State/PendingActivationState.cs
Lib9c/Model/State/RankingMapState.cs
Lib9c/Model/State/RankingState.cs
Lib9c/Model/State/RankingState0.cs
Lib9c/Model/State/RankingState1.cs
Lib9c/Model/State/RedeemCodeState.cs
Lib9c/Model/State/ShardedShopState.cs
Lib9c/Model/State/ShardedShopStateV2.cs
Lib9c/Model/State/ShopState.cs
Lib9c/Model/State/StakeState.cs
Lib9c/Model/State/State.cs
Lib9c/Model/State/WeeklyArenaState.cs

This pull request resolves #2812. About details, please see #2812.
Since this pull request, `GoldCurrencyState.SerializeList` cannot be compiled.
Also it caught invalid usage of serialize method in tests. ([db46ae9](https://github.com/planetarium/lib9c/pull/2814/commits/db46ae97243d7aae79b23ad344e835e7f36c420f))
- `State.Serialize` is renamed to `State.SerializeBase`.
- `State.SerailizeV2` is renamed to `State.SerializeV2Base`
- `State.SerializeList` is renamed to `State.SerializeListBase`
Serialization methods of classes inherited `State` class aren't renamed. 
- `State.SerializeBase` (prior `Serialize`) method's access modifier becomes `protected`
- `State.SerializeV2Base` (prior `SerializeV2`) method's access modifier becomes `protected`
- `State.SerializeListBase` (prior …

Prevent usage of unimplemented serialization method

---

.Lib9c.Tests/Action/BattleArenaTest.cs
.Lib9c.Tests/Action/ExceptionTest.cs
.Lib9c.Tests/Action/Garages/BulkUnloadFromGaragesTest.cs
.Lib9c.Tests/Action/JoinArenaTest.cs
.Lib9c.Tests/Action/Scenario/StakeAndClaimScenarioTest.cs
.Lib9c.Tests/AddressesTest.cs
.Lib9c.Tests/Extensions/BencodexTypesExtensionsTest.cs
.Lib9c.Tests/Model/Arena/ArenaParticipantTest.cs
.Lib9c.Tests/Util/InitializeUtil.cs
Lib9c.sln.DotSettings
Lib9c/Action/BattleArena.cs
Lib9c/Action/Exceptions/Arena/AlreadyJoinedArenaException.cs
Lib9c/Action/JoinArena.cs
Lib9c/Addresses.cs
Lib9c/Exceptions/BencodexTypesExtensions.cs
Lib9c/Exceptions/UnsupportedStateException.cs
Lib9c/Model/Arena/ArenaParticipant.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Module/ArenaModule.cs

The `ArenaParticipant` type and its corresponding account (IAccount) were created to address the issue where Arena participant information was split across multiple addresses and too many status queries were made each time, for example, to calculate the CP of an Arena participant.
Arenas are non-stop, so we didn't change any of the states we already created and use, such as `ArenaScore`, `ArenaInformation`, and `ArenaAvatarState`, but we did configure and synchronize the `ArenaParticipant` state to replace them going forward, which will dramatically reduce a lot of the state lookups and operations we used to do to configure Arena information.
First, I'm proposing changes to the `JoinArena` action, followed by changes to the `BattleArena` action.
- Add `Nekoyume.Addresses.ArenaParticipant` …

feat: introduce `ArenaParticipant` and apply to `JoinArena` first

---

.Lib9c.Tests/Action/GrindingTest.cs
Lib9c/Action/Grinding.cs

- fix grinding reward
- add Equipments duplicate check

fix grinding

---

Lib9c/Action/Stake.cs
Lib9c/Module/LegacyModule.cs

This pull request introduces the `public static IWorld LegacyModule.RemoveLegacyState(this IWorld world, Address address)` method, which removes states instead of setting them to `Null`.
I replace `SetLegacyState(_, Null)` in `Stake`, with `RemoveLegacyState` as an example.

Introduce `IWorld.RemoveLegacyState` extension method

---

.Lib9c.Tests/Action/BuyProductTest.cs
Lib9c/Action/BuyProduct.cs
Lib9c/Model/Mail/ProductBuyerMail.cs
Lib9c/Model/Mail/ProductSellerMail.cs

마켓서비스가 체인에서 삭제된 아이템을 db에서 제거하게 되면서 메일 정보를 보여주지 못하는 문제가 발생했습니다. 이 문제를 해결하기 위해 구매자, 판매자 메일에 Product 정보를 남깁니다.
---
- resolve https://github.com/planetarium/NineChronicles/issues/6001

Add product info in mails

---

.Lib9c.Tests/Action/BuyProductTest.cs
Lib9c/Model/Mail/ProductBuyerMail.cs
Lib9c/Model/Mail/ProductSellerMail.cs

메일에서 이전버전에 직렬화를 해둬서 Product가 비어있을 경우 발생하는 문제를 회피합니다.

Avoid Exception when serialize

---

docs/contributing/documentation/deployment.md
docs/contributing/documentation/structure.md
docs/contributing/documentation/toc.yml
docs/contributing/toc.yml
docs/docfx.json
docs/index.md
docs/toc.yml

Homepage has changed
Docs about Docs 👀

Write documents about documentation

---

.Lib9c.Tests/Action/CancelProductRegistrationTest.cs
Lib9c/Action/CancelProductRegistration.cs
Lib9c/Model/Mail/ProductCancelMail.cs

#2854 와 마찬가지로 판매취소메일에도 Product정보를 추가합니다.

판매취소 메일에 Product 추가

---

Lib9c.Policy/Policy/DebugPolicy.cs

It bumps Libplanet submodule to [5.3.1](https://github.com/planetarium/libplanet/releases/tag/5.3.1)

Bump Libplanet to 5.3.1

---

.Lib9c.Tests/TableData/WorldBossRankingRewardSheetTest.cs
Lib9c/TableData/WorldBossRankingRewardSheet.cs

- 0 또는 null같은 빈 데이터가 들어갈 경우 Material List에서 제외되도록 수정

fix try parse WorldBossRankingRewardSheet

---

@planetarium/lib9c/src/actions/join_arena.ts
@planetarium/lib9c/src/index.ts
@planetarium/lib9c/src/models/rune_slot_info.ts
@planetarium/lib9c/tests/actions/join_arena.test.ts

[feat] add new action (JoinArena)

---

.Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
.Lib9c.Tests/Action/RapidCombinationTest.cs
.Lib9c.Tests/Action/Summon/AuraSummonTest.cs
.Lib9c.Tests/Action/Summon/RuneSummonTest.cs
.Lib9c.Tests/Model/Item/InventoryTest.cs
Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
Lib9c/Model/Item/Inventory.cs

fix: Prevent to add item with 0 quantity #1080

---

Lib9c.sln.DotSettings

https://rider-support.jetbrains.com/hc/en-us/community/posts/4583761682066-Have-some-default-C-code-styles-changed-in-Rider-2021
Rider 버전이 올라가며 기존 셋팅이 바뀐 부분이 있는데 해당 이유로 이러한 마이그레이션 관련 옵션이 자동 생성되는 것으로 보인다. 자동 생성되는 옵션이 기존에 진행했던 StyleCop 코드 검사 규칙에 맞게 코드 룰 추가하는거랑 방향성이 일치하는 것으로 보여 자동생성된 내용 그대로 커밋하였다.
Within single-line expression braces (checked)
```
int[] x = new int[] { 0, 1, 2 };
```
After type cast parentheses (unchecked)
```
int a = (int)b;
```
https://github.com/planetarium/lib9c/pull/2912

자동생성된 코드스타일 파일 커밋

---

.Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
.Lib9c.Tests/Lib9c.Tests.csproj
.Lib9c.Tools/Lib9c.Tools.csproj
.Libplanet.Extensions.ActionEvaluatorCommonComponents/Libplanet.Extensions.ActionEvaluatorCommonComponents.csproj
.github/workflows/lib9c_plugin_build_and_push_s3.yaml
.github/workflows/lint.yml
.github/workflows/main.yml
.github/workflows/publish-docs.yml
.github/workflows/publish.yml
.github/workflows/release.yaml
.gitmodules
CONTRIBUTING.md
Directory.Build.props
Directory.build.props
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
Lib9c.Proposer/Lib9c.Proposer.csproj
Lib9c.sln
Lib9c/Lib9c.csproj
Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj
README.md
integrations/javascript/@planetarium/lib9c/CONTRIBUTING.md

It resolves https://github.com/planetarium/lib9c/issues/2955
------
This pull request did:
- Remove `.Libplanet` submodule.
- Remove items related with submodule. (docs, ci)
- Make controllable Libplanet-related dependencies' version by `LibplanetVersion` property in `Directory.Build.props`
- Make testable with local Libplanet by `LibplanetDirectory` property in `Directory.Build.props`
- Guide by `CONTRIBUTING.md`
- Check `LibplanetDirectory` is empty well by `lint.yaml#jobs.local-libplanet` workflow.
----
I requested reviews to @planetarium/libplanet  and @planetarium/9c-dev but if there is someone I missed, please add them too.

Remove libplanet submodule

---

.github/workflows/lib9c_plugin_build_and_push_s3.yaml
.github/workflows/main.yml
.github/workflows/publish.yml
.github/workflows/release.yaml

To resolve CI failure, update outdated github actions to latest version.

Update github actions to latest major version

---

.Lib9c.Tests/Action/Guild/Migration/FixToRefundFromNonValidatorTest.cs
Lib9c/Action/Guild/Migration/FixToRefundFromNonValidator.cs

Fix `FixToRefundFromNonValidator` action to directly use amount of guild gold.
- After 1.19.2, it's impossible to track amount of guild gold to transfer.
- Since so, added `Amounts` property.

Fix Refund admin action

---

Lib9c.sln.DotSettings

- lib9c/headless등에 적용된 StyleCop 코드 규칙에 맞게 코드 변경을 진행 후 추가적으로 수정되는 스타일입니다.
- StyleCop 규칙에서 using문에 namespace를 작성할 때 무조건 namespace의 풀 네임을 적용해야 하는 규칙이 있습니다
- 이를 대비하기 위해 라이더에서 'PreferQualifiedReference' 옵션을 True로 설정해두었는데 이로 인해 필드의 클래스를 지정할때에도 자동적으로 full namespace가 들어가는 케이스가 있고 이게 신경쓰이는 상황이 반복되어 False로 옵션을 변경해두었습니다
```
SA1210: Using directives should be ordered alphabetically by the namespaces.
SA1135: Using directive for namespace 'Lib9c.Tests.Action' should be qualified
```
현재 development를 머지 타겟으로 설정해두었는데, 현재 작업중인 250(클라기준) 패치와 관련된 작업 브랜치에 머지해야겠다 싶으시면 코멘트 남겨주세요!

fix code style for namespace

---

.Lib9c.Plugin/PluginActionEvaluator.cs
Lib9c.Policy/Policy/BlockPolicySource.cs

`BlockActions` has been added to `BlockPolicySource`, but not to `PluginActionEvaluator`.
This PR resolves a state inconsistency on the node following the tip that prevents it from adding the tip.

Fix: Add block actions to PluginActionEvaluator

---

.github/workflows/publish-docs.yml

Fixes #3051
There is already `concurrency.group` field in `publish-docs` but it uses `<workflow-name>-<ref-name>` as lock key. So it didn't work well and this pull request fixed it as `<workflow-name>`
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/planetarium/lib9c/pull/3052?shareId=708632cf-f87d-4546-a117-4f6a4165e57f).

ci(gh-actions): fix `concurrency.group` in `publish-docs` workflow

---

.Lib9c.Tests/Action/Guild/ClaimRewardTest.cs
.Lib9c.Tests/Action/ValidatorDelegation/PromoteValidatorTest.cs
.Lib9c.Tests/Action/ValidatorDelegation/UndelegateValidatorTest.cs
.Lib9c.Tests/Delegation/DelegateeTest.cs
.Lib9c.Tests/Delegation/DelegatorTest.cs
.Lib9c.Tests/Delegation/Migration/LegacyDelegateeMetadata.cs
.Lib9c.Tests/Delegation/Migration/LegacyLumpSumRewardsRecord.cs
.Lib9c.Tests/Delegation/Migration/MigrateLegacyStateTest.cs
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.MessagePack/Lib9c.MessagePack.csproj
Lib9c.Renderers/Lib9c.Renderers.csproj
Lib9c/Delegation/Delegatee.cs
Lib9c/Delegation/DelegateeMetadata.cs
Lib9c/Delegation/Delegator.cs
Lib9c/Delegation/IDelegatee.cs
Lib9c/Delegation/IDelegateeMetadata.cs
Lib9c/Delegation/LumpSumRewardsRecord.cs
Lib9c/Lib9c.csproj

위임 모델 중 사이즈가 비대한 부분에 대한 핫픽스 입니다.
아래 두 모델은 `Delegators` 프로퍼티를 가집니다.
1. `DelegateeMetadata`
2. `LumpSumRewardsRecord`
이 `Delgators` 프로퍼티는 특정 시점에 수임자가 가지고 있는 모든 위임자 목록을 들고 있으며,
보상이 각 유저에게 모두 분배되었을 때, 남은 자투리 보상을 커뮤니티 풀로 이송하는 역할을 담당하기 위한 정보입니다.
하지만, 현재 밸리데이터가 하나뿐이고, 하나의 밸리데이터가 천 명 이상의 위임자를 가지고 있기 때문에
정보가 비대해지며, 이는 I/O및 데이터 변환시 속도의 저하를 초래합니다.
해당 정보는 보상과 관련되어, 매 블록 호출되어 사용되기 때문에, 이는 매 블록마다
치명적인 속도 저하를 수반하게 됩니다.
이러한 문제점을 제거하기 위해, 본 핫픽스를 통하여 해당 프로퍼티를 제거합니다.
이로 인하여, 자투리 보상을 핸들링하기 위해서는 추후 별도의 처리가 필요해집니다.
본 PR은 해당 프로퍼티의 제거를 통한 모델 경량화 및,
패시브 마이그레이션을 통한 모델 수정을 포함합니다.

Hotfix for heavy object related to delegation

---

.Lib9c.Tests/Action/Guild/ClaimRewardTest.cs
.Lib9c.Tests/Action/ValidatorDelegation/PromoteValidatorTest.cs
.Lib9c.Tests/Action/ValidatorDelegation/UndelegateValidatorTest.cs
.Lib9c.Tests/Delegation/DelegateeTest.cs
.Lib9c.Tests/Delegation/DelegatorTest.cs
.Lib9c.Tests/Delegation/Migration/LegacyDelegateeMetadata.cs
.Lib9c.Tests/Delegation/Migration/LegacyLumpSumRewardsRecord.cs
.Lib9c.Tests/Delegation/Migration/MigrateLegacyStateTest.cs
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.MessagePack/Lib9c.MessagePack.csproj
Lib9c.Renderers/Lib9c.Renderers.csproj
Lib9c/Delegation/Delegatee.cs
Lib9c/Delegation/DelegateeMetadata.cs
Lib9c/Delegation/Delegator.cs
Lib9c/Delegation/IDelegatee.cs
Lib9c/Delegation/IDelegateeMetadata.cs
Lib9c/Delegation/LumpSumRewardsRecord.cs
Lib9c/Lib9c.csproj

Hotfix for heavy `Delegators` property
- This PR removes `Delegators` property from `DelegateeMetadata` and `LumpSumRewardsRecord`.
- Above two properties were too heavy to en/decode, I/O.
- Removed those properties, abandoning feature for remainder gathering.

Release 1.20.1

---

integrations/javascript/@planetarium/lib9c/package.json
integrations/javascript/@planetarium/pnpm-lock.yaml

See https://nodejs.org/en/blog/npm/peer-dependencies
It assumes that `@planetarium/account` and `@planetarium/tx` will follow semver semantic (no API breaking-change for same major version)

feat(js): allow to use shared dependency

---

integrations/javascript/@planetarium/lib9c/jsr.json
integrations/javascript/@planetarium/lib9c/package.json
integrations/javascript/@planetarium/pnpm-lock.yaml

JSR may not support `peerDependencies` so the publish CI fails now. So this pull request reverts changes from #3071.
Also, since 0.3.0 version has already released, this pull request updates the version in `package.json` and `jsr.json`.

Revert "Merge pull request #3071 from moreal/feat/js/peer-dependencies"

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/StakeTest.cs
Lib9c/Action/ClaimStakeReward.cs
Lib9c/Action/Stake.cs

* A validator can execute the `Stake` action without claiming rewards. Actions that decrease the amount still need to go through the lockup period.
* A validator cannot execute the `ClaimStakeReward` action. If a validator tries to execute this action, it throws an `InvalidOperationException`.

Fix an issue where a validator cannot stake

---

.github/workflows/publish.yml
integrations/javascript/@planetarium/9c-headless-provider/jsr.json
integrations/javascript/@planetarium/package.json

It fixes `jsr` workflow broken since #3077

ci(gh-actions): correct jsr publish workflow

---

Lib9c/Action/InvalidItemIdException.cs
Lib9c/Action/Synthesize.cs

add InvalidMaterialItemId

---

.Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
.Lib9c.Tests/Action/EventDungeonBattleTest.cs
.Lib9c.Tests/Action/HackAndSlashSweepTest.cs
.Lib9c.Tests/Action/HackAndSlashTest.cs
.Lib9c.Tests/Action/RaidTest.cs
.Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
Lib9c/Action/EventDungeonBattle.cs
Lib9c/Action/HackAndSlash.cs
Lib9c/Action/HackAndSlashSweep.cs
Lib9c/Action/Raid.cs
Lib9c/Model/State/AvatarState.cs
Lib9c/Model/State/RuneSlotState.cs

add check logic for rune slot, equipment slot

Add check slot logic

---

.Lib9c.Tests/Action/ClaimStakeRewardTest.cs
.Lib9c.Tests/Action/Guild/BanGuildMemberTest.cs
.Lib9c.Tests/Action/Guild/GuildTestBase.cs
.Lib9c.Tests/Action/Guild/JoinGuildTest.cs
.Lib9c.Tests/Action/Guild/MakeGuildTest.cs
.Lib9c.Tests/Action/Guild/MoveGuildTest.cs
.Lib9c.Tests/Action/Guild/QuitGuildTest.cs
.Lib9c.Tests/Action/Guild/RemoveGuildTest.cs
.Lib9c.Tests/Action/Guild/UnbanGuildMemberTest.cs
.Lib9c.Tests/Action/ValidatorDelegation/ValidatorDelegationTestBase.cs
.Lib9c.Tests/Util/DelegationUtil.cs
Lib9c/Action/Guild/BanGuildMember.cs
Lib9c/Action/Guild/JoinGuild.cs
Lib9c/Action/Guild/MakeGuild.cs
Lib9c/Action/Guild/MoveGuild.cs
Lib9c/Action/Guild/QuitGuild.cs
Lib9c/Action/Guild/RemoveGuild.cs
Lib9c/Action/Guild/UnbanGuildMember.cs
Lib9c/Action/ValidatorDelegation/ReleaseValidatorUnbondings.cs
Lib9c/Model/Guild/GuildRejoinCooldown.cs
Lib9c/Module/Guild/GuildBanModule.cs
Lib9c/Module/Guild/GuildModule.cs
Lib9c/Module/Guild/GuildParticipantModule.cs

길드 액션 노출
길드내에 멤버 입/출입시 밸리데이터의 Share 가 업데이트 되지 않는 현상 수정
길드 관련 모듈 정리
테스트 코드 추가
밸리데이터 길드 가입 제한
밸리데이터 길드 생성 제한

Expose guild actions and fix bugs

---

.Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
.Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
.Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
Lib9c.Policy/NCStagePolicy.cs
Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
Lib9c.Policy/Policy/DebugPolicy.cs
Lib9c.Policy/Policy/SpannedSubPolicy.cs
Lib9c.Policy/Policy/VariableSubPolicy.cs

nullable 관련된 경고문을 제거하였습니다.
'.....' is obsolete: 와 같은 경고문도 꽤 많이 발생하는데 제가 할 수 있는 영역이 아닌것 같아서 수정하지 않았습니다.

Remove nullable warnings

---

.Lib9c.Tests/Action/Guild/GuildTestBase.cs
Lib9c/Action/ClaimStakeReward.cs
Lib9c/Action/InitializeStates.cs
Lib9c/Action/Stake.cs
Lib9c/Action/ValidatorDelegation/AllocateGuildReward.cs
Lib9c/Action/ValidatorDelegation/AllocateReward.cs
Lib9c/Action/ValidatorDelegation/PromoteValidator.cs
Lib9c/Module/Guild/GuildDelegateeModule.cs
Lib9c/Module/Guild/GuildModule.cs
Lib9c/Module/Guild/GuildParticipantModule.cs
Lib9c/Module/ValidatorDelegation/ValidatorDelegateeModule.cs
Lib9c/Module/ValidatorDelegation/ValidatorDelegatorModule.cs

https://github.com/planetarium/lib9c/pull/3093 에 의해서 변경된 메소드 이름을 같은 형태로 맞추기 위해
확장 메소드의 이름을 변경하였습니다.

chore: Rename delegation-related extension names

---

.Lib9c.ActionEvaluatorCommonComponents/Lib9c.ActionEvaluatorCommonComponents.csproj

Add outputPath for nuget deploy

---

.Lib9c.Tests/Action/Guild/ClaimUnbonded_ValidatorTest.cs
.Lib9c.Tests/Action/StakeTest.cs
.Lib9c.Tests/Delegation/DelegateeTest.cs
Lib9c/Action/Stake.cs

Stake 액션을 통해서 마이그레이션에서 누락된 에이전트들에 위임을 진행합니다.
아래의 두 케이스를 커버합니다.
1. Pledge가 없어 기존 마이그레이션이 실패한 경우
- LegacyStakeState로 스테이킹 상태를 가지고 있음
- GuildGold도 존재하지 않고, 위임도 존재하지 않음
2. 기존 마이그레이션 이후, Stake액션을 통해 StakeStateV3으로 이행하여 GuildGold를 획득하였지만, 위임은 누락된 경우
- StakeStateV3으로 스테이킹 상태를 가지고 있음
- GuildGold는 존재하나, 위임이 존재하지 않음
추가: Validator 대상으로 하는 ClaimUnbonded 테스트 코드 검증방법에 오류가 있어 테스트 코드 수정 커밋을 추가하였습니다.

Soft migration via Stake action for skipped agents

---

.Lib9c.Tests/Action/Guild/QuitGuildTest.cs
.Lib9c.Tests/Action/Guild/RemoveGuildTest.cs
Lib9c/Module/Guild/GuildModule.cs
Lib9c/Module/Guild/GuildParticipantModule.cs

Unbonding중 길드탈퇴는 의도되지 않은 스펙이므로, 수행 불가능하게 막습니다.

Block leaving guild while unbonding

---

.Lib9c.Tests/Action/Guild/Migration/MigrateStakeAndJoinGuildTest.cs
Lib9c/Action/Guild/Migration/LegacyModels/LegacyGuildParticipant.cs
Lib9c/Action/Guild/Migration/MigrateStakeAndJoinGuild.cs

마이그레이션용 어드민 액션을 이슈 해결을 위해 다시 살립니다. 해당 액션은
- StakeState가 마이그레이션되지 않은 경우 V2에서 V3으로 마이그레이션합니다.
- GuildParticipant가 마이그레이션되지 않은 경우 V1에서 V2로 마이그레이션합니다. (위임 포함)
- 길드에 가입되어있지 않은 경우, 길드에 가입합니다. (위임 포함)

Revive migration action for delegation

---

Directory.Build.props
Lib9c.Abstractions/Lib9c.Abstractions.csproj
Lib9c.MessagePack/Lib9c.MessagePack.csproj
Lib9c.Renderers/Lib9c.Renderers.csproj
Lib9c/Lib9c.csproj

- resolve #3149 
```yang@yangcheon-ung-ui-MacBookPro lib9c % dotnet pack
MSBuild version 17.3.2+561848881 for .NET
복원할 프로젝트를 확인하는 중...
복원할 모든 프로젝트가 최신 상태입니다.
Libplanet.Crypto.Secp256k1 -> /Users/yang/projects/lib9c/Libplanet.Crypto.Secp256k1/.bin/net6.0/Libplanet.Crypto.Secp256k1.dll
Lib9c.Abstractions -> /Users/yang/projects/lib9c/Lib9c.Abstractions/.bin/net6.0/Lib9c.Abstractions.dll
Lib9c.ActionEvaluatorCommonComponents -> /Users/yang/projects/lib9c/.Lib9c.ActionEvaluatorCommonComponents/.bin/net6.0/Lib9c.ActionEvaluatorCommonComponents.dll
Lib9c.Plugin.Shared -> /Users/yang/projects/lib9c/.Lib9c.Plugin.Shared/.bin/net6.0/Lib9c.Plugin.Shared.dll
'/Users/yang/projects/lib9c/Lib9c.Abstractions/.bin/Lib9c.Abstractions.1.23.0.nupkg' 패키지를 만들었습니다. …
```

Fix version prefix

---

Lib9c.Policy/Policy/BlockPolicySource.cs

Disables Slashing
- 슬래싱 및 툼스톤 기능을 임시로 끕니다.
- 이후 컨센서스 커밋에서 투표를 하지 못하거나, 이중투표가 발생하는 경우에도 증거만 수집할 뿐, 처벌이 이루어지지 않습니다.

Disable punishment

---

.Lib9c.Tests/Action/ActionEvaluationTest.cs
.Lib9c.Tests/Action/ClaimWorldBossRewardTest.cs
.Lib9c.Tests/Action/RaidTest.cs
.Lib9c.Tests/Action/WorldBossHelperTest.cs
.Lib9c.Tests/TableData/WorldBossContributionRewardSheetTest.cs
.Lib9c.Tests/TableSheets.cs
Lib9c/Action/ClaimWorldBossReward.cs
Lib9c/Action/Raid.cs
Lib9c/Helper/WorldBossHelper.cs
Lib9c/Model/Mail/IMail.cs
Lib9c/Model/Mail/Mail.cs
Lib9c/Model/Mail/WorldBossRewardMail.cs
Lib9c/Model/State/RaiderState.cs
Lib9c/Model/State/WorldBossState.cs
Lib9c/TableCSV/Swap.meta
Lib9c/TableCSV/Swap/SwapRateSheet.csv.meta
Lib9c/TableCSV/WorldBossContributionRewardSheet.csv
Lib9c/TableCSV/WorldBossContributionRewardSheet.csv.meta
Lib9c/TableData/TableExtensions.cs
Lib9c/TableData/WorldBossContributionRewardSheet.cs

Implement NCIP-25

---

Lib9c/Helper/SynthesizeSimulator.cs
Lib9c/Model/EnumType/Grade.cs

This pull request includes changes to the `Lib9c` project, primarily focusing on adding support for a new grade level, `Mythic`. The changes include updates to the `Grade` enumeration and relevant methods to accommodate this new grade.
Updates for new grade level support:
* [`Lib9c/Model/EnumType/Grade.cs`](diffhunk://#diff-b1630ed25f81b227df72f3b86ae0166e451b1117096355640fb7c26514d8a61dR11): Added `Mythic` as a new grade level in the `Grade` enumeration.
* [`Lib9c/Helper/SynthesizeSimulator.cs`](diffhunk://#diff-fa42125eac2e831dc44269bb4480f7be39a088187ddb283ff45e7ac1f39f8cfdR687): Updated the `GetItemGuids` method to handle the new `Mythic` grade.
* [`Lib9c/Helper/SynthesizeSimulator.cs`](diffhunk://#diff-fa42125eac2e831dc44269bb4480f7be39a088187ddb283ff45e7ac1f39f8cfdR708): Modified …

add grade - mythic

---

Lib9c/Action/Arena/Battle.cs

Fixes the issue where GQL Battle Actions get their MEMO loaded into the wrong format. Due to an invalid memo format, all GQL Battle Actions are unreadable by the Arena Endpoints.
Before the change:
Post the change:

Resolve Battle.cs not using ToDotnetString for the memo field.

---

.Lib9c.Tests/TableData/Rune/RuneOptionSheetTest.cs
Lib9c/TableData/Rune/RuneOptionSheet.cs

- allow empty string instead of NONE enum type

Allow empty string when parse rune options
