planetarium/lib9c

- .github/workflows/dotnet-core.yml
> Initialize github action with dotnet-core.yml

- Lib9c/Lib9c.csproj
> Bump libplanet to 0.10.0-dev.20200806084644

- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Model/Quest/CombinationEquipmentQuest.cs
- Lib9c/Model/Quest/Quest.cs
- Lib9c/TableData/Item/EquipmentItemSubRecipeSheet.cs
- Lib9c/TableData/Quest/CombinationEquipmentQuestSheet.cs
https://github.com/planetarium/nekoyume-unity/pull/2656
> 사용되지 않는 서브 레시피 아이디 삭제

- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/Data/TableCSV/WeeklyArenaRewardSheet.csv
- .Lib9c.Tests/Lib9c.Tests.csproj
- .Lib9c.Tests/Model/WeeklyArenaRewardSheetTest.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/TableData/TableSheets.cs
- Lib9c/TableData/WeeklyArenaRewardSheet.cs
- Drop consumable materials when PVP finished.
> Improve ranking battle reward

- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Model/WorldInformation.cs
1. After patching the table related to the world, it is not reflected in the avatar's world information.
> Bug fix/consider table patch when unlock world

- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/Model/BattleLogTest.cs
- .Lib9c.Tests/Model/SimulatorTest.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Battle/RankingSimulator.cs
- Lib9c/Battle/Simulator.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/State/AvatarState.cs
- Refactoring Simulator
- Add GetReward Event in RankingBattle.Simulate (Fix #10)
> Add GetReward Event on RankingBattle

- .Lib9c.Tests/Action/PatchTableSheetsTest.cs
- .Lib9c.Tests/Action/RedeemCodeTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/State.cs
- .Lib9c.Tests/Action/TransferAssetTest.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- .Lib9c.Tests/Model/State/GoldCurrencyStateTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/BalanceDoesNotExistsException.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/OpenChest.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Action/RankingReward.cs
- Lib9c/Action/RedeemCode.cs
- Lib9c/Action/RewardGold.cs
- Lib9c/Action/TransferAsset.cs
- Lib9c/CurrencyExtensions.cs
- Lib9c/Lib9c.csproj
- Lib9c/Model/State/GoldBalanceState.cs
- Lib9c/Model/State/GoldCurrencyState.cs
This PR introduces `FungibleAssetValue` from [libplanet 0.10.0-dev.20200818120248](https://www.nuget.org/packages/Libplanet/0.10.0-dev.20200818120248). (it had been introduced by https://github.com/planetarium/libplanet/pull/954)
> Introduce FungibleAssetValue

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/ActionRenderer.cs
- Lib9c/BlockPolicy.cs
- Lib9c/Lib9c.csproj
As the upstream Libplanet changed the way to render actions (https://github.com/planetarium/libplanet/pull/963), I made a patch for lib9c to follow up these changes.
I am going to send a pull request to catch up the same API changes to NineChronicles.Standalone repository as well.
> Implement IRenderer<T> interface

- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/Character/CharacterBase.cs
- Add BattleLog events in BT.Tick once
> Refactoring Behaviour Tree

- Lib9c/Action/ActionRenderer.cs
> Fix can't rendering block action

- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/ActionRenderer.cs
This PR exposes subjects in `ActionRender` to partial render on RPC mode.
and it modifies some API to receive `Currency` directly.
> Expose subjects in ActionRenderer

- Lib9c/GameConfig.cs
- Update consumable unlock level
> Update consumable slot unlock level

- Lib9c/Action/ActionRenderer.cs
- Lib9c/Action/HackAndSlash.cs
The title says it all.
I believe `InvalidOperationException` isn't enough for cover these all cases, so I'll fix them on the next PR.
> Replace LogError with InvalidOperationException in HackAndSlash.Execute()

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Model/Character/Enemy.cs
> Fix SerializationException on HackAndSlash action

- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- Lib9c/Action/ItemEnhancement.cs
- Fix upgrade item when cost > 0
> Fix item enhancement with cost not work

- Lib9c/BlockHelper.cs
> Move `BlockHelper.cs` from nekoyume unity to lib9c

- .Lib9c.Tests/Action/ChargeActionPointTest.cs
- .Lib9c.Tests/Action/CombinationConsumableTest.cs
- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/CreateAvatarTest.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/Action/RapidCombinationTest.cs
- .Lib9c.Tests/Action/RedeemCodeTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Model/BattleLogTest.cs
- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- .Lib9c.Tests/Model/State/RankingMapStateTest.cs
- .Lib9c.Tests/Model/State/RankingStateTest.cs
- .Lib9c.Tests/Model/State/WeeklyArenaStateTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Action/InvalidAddressException.cs
- Lib9c/Action/RankingExceededException.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/Model/State/RankingMapState.cs
- Lib9c/Model/State/RankingState.cs
- Divide ranking map state from ranking state
> Divide ranking map state from ranking state

- Lib9c/Model/Item/Inventory.cs
- Fix condition of notification in inventory.
- Rings can be equipped more than one, so case is seperated when checking equipments in inventory.
> Fix notification condition on equipment inventory.

- Lib9c/Action/BlockRenderer.cs
> Make reactive subjects in BlockRenderer public

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/BlockHelper.cs
- When you create InitializeState, you must now hand over PendingActivityState[] as well.
> Add pendingActivationState when initializeState execute

- .Lib9c.Tests/Model/PlayerTest.cs
- Lib9c/Model/Character/CharacterBase.cs
- Fix bug when multiple hit skill target already dead.
> Avoid exception when use multiple hit skill

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- .Lib9c.Tests/Model/State/AuthorizedMinersStateTest.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Addresses.cs
- Lib9c/BlockHelper.cs
- Lib9c/BlockPolicy.cs
- Lib9c/BlockPolicySource.cs
- Lib9c/InvalidMinerException.cs
- Lib9c/Model/State/AuthorizedMinersState.cs
This PR allows adding restriction for block miners as `AuthorizedMinersState` on the genesis block.
> Introduce AuthorizedMinersState

- Lib9c/Lib9c.csproj
> Bump libplanet

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
> Fix HackAndSlash.PlainValue

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/EquipmentSlotUnlockException.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/InvalidStageException.cs
- Lib9c/Action/InvalidWorldException.cs
- Lib9c/Action/NotEnoughActionPointException.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Action/RequiredBlockIndexException.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/Model/WorldInformation.cs
- Lib9c/TableData/Exceptions.cs
- Use defined exceptions instead of  `InvalidOperationException`
> Define exceptions in HackAndSlash

- Lib9c/Action/ActionRenderer.cs
- Lib9c/Action/BlockRenderer.cs
- Lib9c/Lib9c.csproj
Upgrade Libplanet to [0.10.0-dev.20200914090409][1] to follow up the API changes made from <https://github.com/planetarium/libplanet/pull/1000>.
[1]: https://www.nuget.org/packages/Libplanet/0.10.0-dev.20200914090409
> Upgrade Libplanet to 0.10.0-dev.20200914090409

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tools.Tests/UtilsTest.cs
- .Lib9c.Tools/SubCommend/Create.cs
- .Lib9c.Tools/Utils.cs
- Lib9c/BlockHelper.cs
- Activate admin address if `isActivateAdminAddress` is true
> Activate admin address if `isActivateAdminAddress` is true

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/TransferAssetTest.cs
- Lib9c/Action/TransferAsset.cs
> Using FAV instead of BigInteger + Currency in TransferAsset

- Lib9c/Lib9c.csproj
See also: <https://github.com/planetarium/libplanet/pull/1009>.
> Upgrade Libplanet to 0.10.0-dev.20200917072856

- .Lib9c.Tests/Model/ItemGradeQuestTest.cs
- .Lib9c.Tests/Model/ItemTypeCollectQuestTest.cs
- .Lib9c.Tests/Model/SimulatorTest.cs
- Lib9c/Battle/Simulator.cs
- Lib9c/Model/Quest/ItemGradeQuest.cs
- Lib9c/Model/Quest/ItemTypeCollectQuest.cs
Sorting `ItemIds` in `ItemGradeQuest, ItemTypeCollectQuest`
> Make Quest.ItemIds deterministic

- Lib9c/Action/ItemEnhancement.cs
- It reflects the need to use 1 block to enhance equipment.
> Fix required block index in ItemEnhancement

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/BlockPolicy.cs
- Lib9c/BlockPolicySource.cs
- Lib9c/DebugPolicy.cs
- Lib9c/Lib9c.csproj
This PR bumps libplanet to [0.10.0-dev.20200921050842](https://www.nuget.org/packages/Libplanet/0.10.0-dev.20200921050842) and apply its modified interface (`IBlockPolicy.DoesTransactionFollowsPolicy()`).
> Bump libplanet to 0.10.0-dev.20200921050842

- .Lib9c.Tests/Model/ItemNotificationTest.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/TableData/UnlockHelper.cs
Reflects unlock state of current avatar in inventory equipment notification condition.
> Fix bug in ring notification condition.

- .Lib9c.Tests/Action/InvalidSignatureExceptionTest.cs
- .Lib9c.Tests/Action/InvalidTransferSiginerExceptionTest.cs
- .Lib9c.Tests/Action/PendingActivationDoesNotExistsExceptionTest.cs
- Lib9c/Action/ActivatedAccountsDoesNotExistsException.cs
- Lib9c/Action/ActivationException.cs
- Lib9c/Action/InvalidSignatureException.cs
- Lib9c/Action/InvalidTransferSignerException.cs
- Lib9c/Action/PendingActivationDoesNotExistsException.cs
> Make exceptions serializable

- Lib9c/Lib9c.csproj
> Bump libplanet to 0.10.0-dev.20200923051913

- .Lib9c.Tests/Model/StageSimulatorTest.cs
- Lib9c/Battle/StageSimulator.cs
> Fix simulator turn number

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
sort `List<T>` in `HackAndSlash.PlainValue`
> Make HackAndSlash plain value determinisitic

- Lib9c/Lib9c.csproj
> Bump libplanet to 0.10.0-dev.20200924025621

- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Battle/ArenaScoreHelper.cs
- Lib9c/Battle/RankingSimulator.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Quest/Quest.cs
This PR fixes some orders of iteration in Lib9c to guarantee the deterministic results.
> Fix iteration order for deterministic result

- .Lib9c.Tests/Model/State/CollectionMapTest.cs
- .Lib9c.Tests/Model/State/RankingMapStateTest.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/PatchTableSheet.cs
- Lib9c/Model/CollectionMap.cs
> sorting dictionary for deterministic

- .Lib9c.Tests/Action/CombinationConsumableTest.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/RapidCombinationTest.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Model/State/StateExtensions.cs
- Sorting material, material ids in `CombinationConsumable.PlainValue, ResultModel`
> Sorting material items for deterministic

- .Lib9c.Tests/Types/BencodexTypesListTest.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/TableData/Sheet.cs
- Add little unit test for `Bencodex.Types.List`.
- Use `Sheet.OrderedList` when use any `Sheet` in `foreach`.
- Sort materiali ids In `ItemEnhancement.Execute()`.
- Sort some lists in `RankingBattle` action.
- Sort `AvatarState.combinationSlotAddresses` once in `AvatarState` constructor.
> Bug fix/make list deterministic

- .Lib9c.Tests/Model/QuestListTest.cs
- .Lib9c.Tests/Model/QuestRewardTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Model/Quest/Quest.cs
- Lib9c/Model/Quest/QuestReward.cs
- Lib9c/Model/State/AvatarState.cs
- Sort quest list, quest reward for deterministic
> Sort quest args for deterministic

- Lib9c/ReorgMiner.cs
Adds `ReorgMiner.cs` for artificial periodic reorg.
> Add ReorgMiner for dev mode

- .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
- Lib9c/Model/Skill/AttackSkill.cs
- Improved the skill damage formula to improve the part where the power of the multi-hit skill decreases more than intended by the target's defense.
> Improve skill damage formula

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/Model/State/CreditsStateTest.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Addresses.cs
- Lib9c/Model/State/CreditsState.cs
This PR introduces `CreditsState` to store contributors' names to genesis state as game credit.
> Introduce CreditsState

- .github/workflows/main.yml
- .github/workflows/publish.yml
- .gitmodules
- Lib9c/Lib9c.csproj
> Reference Libplanet as ProjectReference w/ submodules instead of PackageReference

- Lib9c.sln
Continued from the PR <https://github.com/planetarium/lib9c/pull/126>.
> Add Libplanet & Libplanet.Stun projects to the Lib9c.sln

- .Lib9c.Tests/Action/CreateAvatarTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- Lib9c/Action/AvatarIndexAlreadyUsedException.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/InvalidNamePatternException.cs
throw specified exception instead of logError in `CreateAvatar`
> throw exception in create avatar

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Data/TableCSV/GameConfigSheet.csv
- Lib9c/Action/DailyReward.cs
- Lib9c/Action/RewardGold.cs
- Lib9c/GameConfig.cs
- Lib9c/Model/State/GameConfigState.cs
Migrates constant variables of AP refill/daily/weekly arena reward interval to `GameConfigState`.
> Migrate AP/Arena reward interval to GameConfigState.

- .gitmodules
- Lib9c.sln
- Lib9c/Lib9c.csproj
> Rename Libplanet to .Libplanet to hide on Unity

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/SellTest.cs
- .Lib9c.Tests/Model/State/ShopStateTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationSlotUnlockException.cs
- Lib9c/Action/InvalidPriceException.cs
- Lib9c/Action/ItemDoesNotExistException.cs
- Lib9c/Action/NotEnoughMaterialException.cs
- Lib9c/Action/Sell.cs
- Lib9c/Model/State/ShopState.cs
- Throw exception instead of logError
- Prevent register duplicate productId shop item
> Refactoring Sell action

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationSlotUnlockException.cs
- Lib9c/Action/NotEnoughMaterialException.cs
- #133 follow up.
- skip `NotEnoughActionPoint` case. because every equipment recipes required action point is 0.
> Throw exception instead of logError in CombinationEquipment

- .Lib9c.Tests/Action/BuyTest.cs
- Lib9c/Action/Buy.cs
> Throw exception in buy

- .Lib9c.Tests/Renderer/RendererTest.cs
- Lib9c/Renderer/ValidatingActionRenderer.cs
Validate function must be passed to `ValidatingActionRenderer`.
> Validate when reorg ends

- Lib9c/Action/BalanceDoesNotExistsException.cs
- Lib9c/InvalidMinerException.cs
Removed FIXME comment from `InvalidMinerException.cs` and `BalanceDoesNotExistsException.cs`.
> Make some exceptions serializable

- .Lib9c.Tests/Action/ItemEnhancement2Test.cs
- Lib9c/Action/ItemEnhancement2.cs
> Implement item enhancement2

- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/RapidCombinationTest.cs
- Lib9c/Action/CombinationSlotResultNullException.cs
- Lib9c/Action/RapidCombination.cs
- Set minimum cost of RapidCombination action.
- Replace all of logs to throwing exceptions.
- Add unit tests.
> Improve RapidCombination action

- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/ConsumableSlotOutOfRangeException.cs
- Lib9c/Action/ConsumableSlotUnlockException.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/GameConfig.cs
- Lib9c/Model/State/AvatarState.cs
> Validate consumable use

- Lib9c/Miner.cs
- Lib9c/ReorgMiner.cs
> Restrict size of transaction batch at mining

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/BlockPolicySource.cs
> Restrict only one action in single tx

- .Lib9c.Tests/Action/HackAndSlash2Test.cs
- .Lib9c.Tests/Action/RankingBattle2Test.cs
- Lib9c/Action/HackAndSlash2.cs
- Lib9c/Action/RankingBattle2.cs
> Avoid RPCException when deserialize action

- .Lib9c.Tests/Action/RapidCombination2Test.cs
- Lib9c/Action/RapidCombination2.cs
> Implement new RapidCombination

- .Lib9c.Tests/Action/AddRedeemCodeTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c/Action/AddRedeemCode.cs
- Lib9c/Action/PermissionDeniedException.cs
- Lib9c/Action/PermissionException.cs
- Lib9c/Action/PolicyExpiredException.cs
- Lib9c/Model/State/RedeemCodeState.cs
- Lib9c/TableData/Exceptions.cs
- `AddRedeemCode` for update `RedeemCodeState`
- add `tx add-redeem-code` command
> Implement update redeem code state

- .Lib9c.Tools/SubCommand/Tx.cs
- Use stderr instead of stdout for printing debug messages
- Add line ending to hex output
P.S. this code is cheap too.
> Fix tx patchtable sub-command

- .Lib9c.Tests/Action/RedeemCodeTest.cs
- .Lib9c.Tests/Model/CostumeTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Model/Item/Costume.cs
- Lib9c/Model/Item/ItemFactory.cs
- Add ItemId on Costume
- Set ItemId in RedeemCode
> Add ItemId on Costume

- .Lib9c.Tests/Action/Buy2Test.cs
- .Lib9c.Tests/Action/CombinationConsumable2Test.cs
- .Lib9c.Tests/Action/CombinationEquipment2Test.cs
- .Lib9c.Tests/Action/HackAndSlash3Test.cs
- .Lib9c.Tests/Action/ItemEnhancement3Test.cs
- .Lib9c.Tests/Action/SellCancellation2Test.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/Buy2.cs
- Lib9c/Action/CombinationConsumable2.cs
- Lib9c/Action/CombinationEquipment2.cs
- Lib9c/Action/HackAndSlash3.cs
- Lib9c/Action/ItemEnhancement3.cs
- Lib9c/Action/SellCancellation2.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/State/AvatarState.cs
- limit `AvatarState.MailBox` size for reduce `IAction.Execute` time.
---
For the sake of reviewers' convenience:
- [Diff Buy.cs vs Buy2.cs](https://linediff.com/?id=5facc974687f4bac4f8b4567)
- [Diff CombinationConsumable.cs vs CombinationConsumable2.cs](https://linediff.com/?id=5facc956687f4b80508b4569)
- [Diff CombinationEquipment.cs vs CombinationEquipment2.cs](https://linediff.com/?id=5facc99b687f4bcc4f8b4568)
- [Diff HackAndSlash2.cs vs HackAndSlash3.cs](https://linediff.com/?id=5facc9cb687f4b80508b456a)
- [Diff ItemEnhancement2.cs vs ItemEnhancement3.cs](https://linediff.com/?id=5facc9f5687f4b5b508b4567)
- [Diff SellCancellation.cs vs SellCancellation2.cs](https://linediff.com/?id=5facca2f687f4b5b508b4568)
> Cut off AvatarState.MailBox

- Lib9c/Action/RewardGold.cs
- Lib9c/Model/State/WeeklyArenaState.cs
> Remove hard coding in `WeeklyArenaState`

- Lib9c/Action/AccountStateDeltaExtensions.cs
In `GetSheet<T>()`, the slowest part `sheet.Set(csv)`. So I applied LRU cache for it.
---
Before:
```
[12:29:02 DBG] HAS Total Executed Time: 00:00:00.1531800
[12:29:03 DBG] HAS Total Executed Time: 00:00:00.1023740
[12:29:03 DBG] HAS Total Executed Time: 00:00:00.1592980
...
```
After
```
[12:31:21 DBG] HAS Total Executed Time: 00:00:00.0874910
[12:31:21 DBG] HAS Total Executed Time: 00:00:00.0447470
[12:31:21 DBG] HAS Total Executed Time: 00:00:00.0879520
...
```
> Apply cache for GetSheet<T>

- .Lib9c.Tests/Action/ItemEnhancement4Test.cs
- Lib9c/Action/ItemEnhancement4.cs
Assignment of `ItemEnhancement.ResultModel.gold` was missing, so implemented new `ItemEnhancement` action that covers.
> Implement ItemEnhancement4.

- .Lib9c.Tests/Action/Buy3Test.cs
- .Lib9c.Tests/Action/Sell2Test.cs
- .Lib9c.Tests/Action/Sell3Test.cs
- .Lib9c.Tests/Action/SellCancellation3Test.cs
- Lib9c/Action/Sell3.cs
- Lib9c/Model/Item/Inventory.cs
> Bug fix/make consumables can be tradable

- Lib9c/Model/Item/Costume.cs
> Add `Equals()` method to `Costume`

- Lib9c/Model/Item/Costume.cs
- This reverts commit 53ced3a3b2e1f71a470ef2de3bf9ae54300683e0.
> Revert "Add `Equals()` method to `Costume`"

- .Lib9c.Tests/Action/MimisbrunnrBttleTest.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Model/WorldInformation.cs
- Add AddAndUnlockMimisbrunnrWorld method.
- Add mimisbrunnrBattle testcode.
> Bug fix and add unit tests for `MimisbrunnrBattle` action

- .Lib9c.Tests/Action/MimisbrunnrBttleTest.cs
- Lib9c/Action/InvalidEquipmentException.cs
- Lib9c/Action/MimisbrunnrBattle.cs
Fix the problem of stripping the costume when it first entered the Mimisbrunnr
> Fix mimisbrunnr battle action

- .Lib9c.Tests/Action/TransferAssetTest.cs
- Lib9c/Action/InvalidTransferRecipientException.cs
- Lib9c/Action/TransferAsset.cs
This is applied after block 380000 (now 374631 at 2020.12.17 14:10 KST)
> Make TransferAsset cannot have same sender and recipient

- .Lib9c.Tests/Action/CombinationEquipment3Test.cs
- .Lib9c.Tests/Action/RankingBattle2Test.cs
- Lib9c/Action/RankingBattle2.cs
```
2020-12-23 17:12:14 [Debug] RankingBattle exec started. costume: ("40100000"), equipment: ("")
2020-12-23 17:12:14 [Debug] RankingBattle Get AgentAvatarStates: 00:00:00.0197333
2020-12-23 17:12:14 [Debug] RankingBattle Validate Equipments: 00:00:00.0008070
2020-12-23 17:12:14 [Debug] RankingBattle Equip Equipments: 00:00:00.0103885
2020-12-23 17:12:14 [Debug] RankingBattle Get Enemy AvatarState: 00:00:00.0046852
2020-12-23 17:12:14 [Debug] RankingBattle Get WeeklyArenaState ("0x32E60B98C48BaEb4390b986880300C94cb08F381"): 00:00:00.0000831
2020-12-23 17:12:14 [Debug] RankingBattle Validate ArenaInfo: 00:00:00.0001553
2020-12-23 17:12:14 [Debug] RankingBattle Get CostumeStatSheet: 00:00:00.0319663
2020-12-23 17:12:14 [Debug] RankingBattle Simulate() with equipment:(""), …
```
> Logging RankingBattle Execute

- .Lib9c.Tests/Battle/SimplePriorityQueueTest.cs
> Add unit tests for `SimplePriorityQueue`

- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- .Lib9c.Tests/Model/WeightedSelectorTest.cs
- Lib9c/Action/CombinationEquipment3.cs
- Lib9c/Battle/Simulator.cs
- Lib9c/Battle/WeightedSelector.cs
- Added Select method version 3
- Modified to properly receive Ranked Arena reward items
> Add SelectV3() and  testcode

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c.Benchmarks/Program.cs
Bump Libplanet into c95af20f1a3a2d2221830e7f5b8550647908ef70
> chore: bump Libplanet

- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- Lib9c/Action/HackAndSlash4.cs
- Lib9c/Action/MimisbrunnrBattle2.cs
- Lib9c/Action/RankingBattle3.cs
- Lib9c/Battle/RankingSimulator.cs
- Lib9c/Battle/Simulator.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Battle/Wave.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Character/EnemyPlayer.cs
- Lib9c/Model/Character/Player.cs
> Add `Skills.PostSelectV2()` and apply this in all of related logics

- Lib9c/Battle/StageSimulator.cs
> Apply `Player.SpawnV2()` in `StageSimulator.SimulateV2()`

- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- .Lib9c.Tests/Model/WeightedSelectorTest.cs
- Lib9c/Battle/RankingSimulator.cs
- Lib9c/Battle/Simulator.cs
- Lib9c/Battle/StageSimulator.cs
- Divide SetReward, SetRewardV2 for backward compatibility
> Divide SetRewardV2 for Backward compatibility

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/Action/RewardGold.cs
- Lib9c/BlockHelper.cs
> Do not include block action at transaction

- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/Quest/Quest.cs
> Add exception handling for reward item

- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CreateAvatar.cs
You can add options by adding item option rows in the constructor of `optionRows` variable.
> Implement crafting custom equipment for test.

- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c.Benchmarks/Program.cs
Bump Libplanet submodule to [`1b58a2b49d04f310186ea907044b221e1092b064`](https://github.com/planetarium/libplanet/commit/1b58a2b49d04f310186ea907044b221e1092b064).
> Bump Libplanet submodule

- .Lib9c.Tests/Action/Common/TestRandom.cs
- .Lib9c.Tests/Action/HackAndSlash4Test.cs
- .Lib9c.Tests/Action/Sell2Test.cs
- .Lib9c.Tests/Action/Sell3Test.cs
- .Lib9c.Tests/Action/SellTest.cs
- .Lib9c.Tests/Model/Item/ShopItemTest.cs
- .Lib9c.Tests/Model/WeightedSelectorTest.cs
- Lib9c/Model/Item/ShopItem.cs
Add `ExpiredBlockIndex` on `ShopItem`. It will be used in Buy and Sell actions.
> Introduce ShopItem.ExpiredBlockIndex

- .Lib9c.Tests/Action/Sell4Test.cs
- .Lib9c.Tests/Model/Item/ConsumableTest.cs
- .Lib9c.Tests/Model/Item/CostumeTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/Sell4.cs
- Lib9c/Model/Item/Costume.cs
- Lib9c/Model/Item/INonFungibleItem.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/State/AvatarState.cs
- Introduce new sell action for auto expiration
- #322 in sell (Other actions work on follow up PR)
> Introduce new Sell & mail cutoff

- Lib9c.Benchmarks/Program.cs
> Release v100036

- .Lib9c.Tests/Model/State/SheetStateTest.cs
- Lib9c/Addresses.cs
SSIA
- You can run this unit test.
- And you can get test output here.
```
Lib9c.Tests.Model.State.SheetStateTest.PrintSheetAddresses
CharacterLevelSheet: 00daFaa4414D63bE46965F442619406f692e2690
CharacterSheet: 68b1cC1Edc7D84477C6679eA7828c2A4B2dA7fef
EnhancementCostSheet: fAA2511e4193D1C16dAeDF67210a64250c8dAA8B
GameConfigSheet: 46Bedb51Dab9b41243b0372940586E051c308769
ConsumableItemRecipeSheet: 0378B6baDc177892f6392623ce8818Ac6e679b23
ConsumableItemSheet: d800F70fb5A292670048daFD77727ce28b44Cae0
CostumeItemSheet: c89b9ABd57E03195E428C1d179e1bc7fBad0Bb09
CostumeStatSheet: FA6432782A75F1daF12447f44a1D8aB9fEE04337
EquipmentItemOptionSheet: 134c3Be37B33857A32ceF2D60b72f881168A1db6
EquipmentItemRecipeSheet: 72D60d63F4440C36080a532958d9a5f48d7DB1A0
EquipmentItemSetEffectSheet: …
```
> Add SheetStateTest to get address of SheetState

- .Lib9c.Tests/Action/BuyMultipleTest.cs
- Lib9c/Action/BuyMultiple.cs
delete use case from new sell(sell4).
> Delete new sell error case in buy multiple

- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/Sell2Test.cs
- .Lib9c.Tests/Action/Sell3Test.cs
- .Lib9c.Tests/Action/SellCancellationTest.cs
- .Lib9c.Tests/Action/SellTest.cs
- .Lib9c.Tests/Model/State/ShardedShopStateTest.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/State/ShardedShopState.cs
- Lib9c/SerializeKeys.cs
- based on #357 
- resolve #342
> Introduce ShardedShopState

- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/CombinationConsumableTest.cs
- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
- .Lib9c.Tests/Action/SellCancellationTest.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/BuyMultiple.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/DailyReward.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/SellCancellation.cs
Please check if this is the right way to merge rc into development 🙇  @planetarium/9c-backend @planetarium/9c-dev
> Release v100040

- .Lib9c.Tests/Action/BuyTest.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/BuyMultiple.cs
- Lib9c/Action/PurchaseInfo.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/State/StateExtensions.cs
- Lib9c/SerializeKeys.cs
- based on #357 , #359 
- resolve #360
> Introduce buy bulk products.

- .Lib9c.Tests/Model/Item/CostumeTest.cs
- .Lib9c.Tests/Model/Item/EquipmentTest.cs
- .Lib9c.Tests/Model/Item/ShopItemTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/Item/Consumable.cs
- Lib9c/Model/Item/Costume.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Item/ItemBase.cs
- Lib9c/Model/Item/ItemFactory.cs
- Lib9c/Model/Item/ItemUsable.cs
- Lib9c/Model/Item/ShopItem.cs
- Lib9c/Model/Skill/Skill.cs
- Lib9c/Model/Skill/SkillFactory.cs
- Lib9c/Model/Stat/StatMap.cs
- Lib9c/Model/Stat/StatMapEx.cs
This PR reverts 9a56234f8f376def8365601a1e59fa91ab0de902 to resolve state inconsistency.
> Revert of 9a56234f8f376def8365601a1e59fa91ab0de902

- .Lib9c.Tests/Action/SellCancellationTest.cs
- .Lib9c.Tests/Action/SellTest.cs
- .Lib9c.Tests/Model/Item/InventoryTest.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/Item/TradableMaterial.cs
- Register same material
- Update Inventory Tradable API
- Update TradableMaterial.Equals
> Fix Material sell

- .Lib9c.Tests/Model/State/MonsterCollectStateTest.cs
- Lib9c/Model/State/MonsterCollectionState.cs
> Fix GetRewardLevel bug

- Lib9c/GameConfig.cs
Add stage condition field for ranking button in bottom menu.
> Add Bottommenu Ranking condition.

- Lib9c/Action/SellCancellation.cs
> Add tradableFungibleItem info in sell cancellation mail result

- Lib9c/Action/Buy.cs
> Add tradableFungibleItem info in seller result

- .Lib9c.Tests/Action/SellCancellationTest.cs
- .Lib9c.Tests/Model/Item/InventoryTest.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/Item/Inventory.cs
- #416
- Select same required block index & item count from inventory when sell cancel.
- Check required block index when remove tradable item.
> fix inventory tradable item methods

- .Lib9c.Tests/Action/ChargeActionPoint0Test.cs
- .Lib9c.Tests/Action/ChargeActionPointTest.cs
- .Lib9c.Tests/Action/RapidCombination0Test.cs
- .Lib9c.Tests/Action/RapidCombinationTest.cs
- .Lib9c.Tests/Model/Item/InventoryTest.cs
- Lib9c/Action/AttachmentActionResult.cs
- Lib9c/Action/ChargeActionPoint0.cs
- Lib9c/Action/RapidCombination0.cs
- Lib9c/Action/RapidCombination2.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/State/CombinationSlotState.cs
> Check RequiredBlockIndex in ChargeActionPoint, RapidCombination

- Lib9c/Action/CombinationEquipment.cs
> Update selector version in CombinationEquipment class

- .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
- .Lib9c.Benchmarks/Program.cs
> Enable console logging in Lib9c.Benchmarks

- .Lib9c.Tests/Action/Buy5Test.cs
- .Lib9c.Tests/Action/Buy6Test.cs
- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/Sell0Test.cs
- .Lib9c.Tests/Action/Sell4Test.cs
- .Lib9c.Tests/Action/Sell5Test.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/Buy6.cs
- Lib9c/Action/PurchaseInfo.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/Sell0.cs
- Lib9c/Action/Sell4.cs
- Lib9c/Action/Sell5.cs
- sanity check in Sell, Buy actions
> Sanity check in shop actions

- Lib9c/BlockPolicy.cs
> Pass 0tx block validate when block is less then 1,711,631

- Lib9c/BlockPolicy.cs
This PR adjusts outdateAfter value for the comparator.
> Adjust outdateAfter

- .Lib9c.Tests/Action/ChargeActionPointTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- Lib9c/Action/ActionPointExceededException.cs
- Lib9c/Action/ChargeActionPoint.cs
> Validate AP in ChargeActionpoint

- .Lib9c.Tests/Action/SellCancellationTest.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/Order/Order.cs
- fix missing plain value
- fix error msg
> fix sell cancel

- .Lib9c.Tests/Model/Order/NonFungibleOrderTest.cs
- Lib9c/Model/Order/NonFungibleOrder.cs
> Consider `IEquippableItem` not `Equipment` in `NonFungibleOrder`

- .Lib9c.Tests/Action/ActivateAccount0Test.cs
- .Lib9c.Tests/Action/ActivateAccountTest.cs
- .Lib9c.Tests/Action/AddActivatedAccount0Test.cs
- .Lib9c.Tests/Action/AddActivatedAccountTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/MigrationActivatedAccountsStateTest.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c/Action/ActivateAccount.cs
- Lib9c/Action/ActivateAccount0.cs
- Lib9c/Action/AddActivatedAccount.cs
- Lib9c/Action/AddActivatedAccount0.cs
- Lib9c/Action/AlreadyActivatedException.cs
- Lib9c/Action/MigrationActivatedAccountsState.cs
- Lib9c/BlockPolicySource.cs
- Lib9c/Model/ActivationKey.cs
- Lib9c/Model/State/ActivatedAccountsState.cs
- Lib9c/Model/State/PendingActivationState.cs
- Lib9c/Model/State/RedeemCodeState.cs
> Reduce CheckSigner execution time.

- .Lib9c.Tests/Model/Item/EquipmentTest.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/SerializeKeys.cs
- Add the `optionCountFromCombination` field which is determined at combine action.
- Add the `RequiredCharacterLevel` field which is determined at several actions.
> Add some fields to `Equipment`

- Lib9c/BlockPolicySource.cs
> Fix missing reference in unity editor

- Lib9c/Battle/CPHelper.cs
- Fix access modifiers of `CPHelper`
- Add `CPHelper.GetStatCP(statType, statValue, characterLevel = 1)` method
> Fix access modifiers of `CPHelper`

- .github/workflows/benchmark.yml
- Lib9c/Action/Buy0.cs
- Lib9c/Action/CombinationEquipment0.cs
- Lib9c/Action/HackAndSlash2.cs
- Fix broken bench gh action
- Fix InvalidBlockStateRootHashException <= 50000 blocks.
> Fix InvalidBlockStateRootHashException 50000 blocks

- Lib9c/Action/ItemEnhancement.cs
Remove `RequiredAppraiseBlock` from Blocks Required for Item Enhancement
> Remove RequiredAppraiseBlock

- .Lib9c.Tests/Action/CombinationConsumableTest.cs
- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationEquipment.cs
- Fix `CombinationConsumable` and `CombinationEquipment`
- Improve unit tests for above
> Bug fix/combination add two result items

- Lib9c/Model/Item/Equipment.cs
Modified to check the minimum value only when the result value is not zero.
> Fix enhancement action result value

- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash4.cs
- Lib9c/Action/HackAndSlash5.cs
- Lib9c/Action/HackAndSlash6.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Action/MimisbrunnrBattle2.cs
- Lib9c/Action/MimisbrunnrBattle3.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/BlockPolicy.cs
This PR removes the tx limitation per block (1 or 3).
> Remove Tx limit

- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/Model/State/CombinationSlotState.cs
- Rename argument
- Change update version for AvatarState in combination actions
- Remove useless methods
> Bug fix/mail disapear

- Lib9c/Action/ItemEnhancement.cs
> Fix TryGetRow method

- Lib9c/BlockPolicy.cs
Decrease index from 2,175,000 to 2,173,700
> decrease tx limit index

- .Lib9c.Tests/Action/Buy5Test.cs
- .Lib9c.Tests/Action/Buy6Test.cs
- .Lib9c.Tests/Action/Buy7Test.cs
- .Lib9c.Tests/Action/Buy8Test.cs
- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/DailyReward2Test.cs
- .Lib9c.Tests/Action/DailyReward3Test.cs
- .Lib9c.Tests/Action/DailyReward4Test.cs
- .Lib9c.Tests/Action/DailyRewardTest.cs
- .Lib9c.Tests/Action/SellCancellation5Test.cs
- .Lib9c.Tests/Action/SellCancellation6Test.cs
- .Lib9c.Tests/Action/SellCancellation7Test.cs
- .Lib9c.Tests/Action/SellCancellationTest.cs
- Lib9c/Action/AttachmentActionResult.cs
- Lib9c/Action/DailyReward.cs
- Lib9c/Action/DailyReward3.cs
- Lib9c/Action/DailyReward4.cs
- Lib9c/BlockPolicySource.cs
- Archive "daily_reward4" as `DailyReward4`
- Remove `DailyRewardResult` of `DailyReward3` and `DailyReward4`
- Introduce "daily_reward5" as `DailyReward`
> Bug fix/no more hourglass in `DailyReward`

- .Lib9c.Tests/Action/DailyRewardTest.cs
- Lib9c/Action/DailyReward.cs
> Fix bug of `DailyReward` and test

- Lib9c/DebugPolicy.cs
> Change check target from the tip of blocks to the count of blocks in `DebugPolicy`

- .Lib9c.Tests/Action/HackAndSlash7Test.cs
- .Lib9c.Tests/Action/MimisbrunnrBattle4Test.cs
- .Lib9c.Tests/Action/MimisbrunnrBattleTest.cs
- .Lib9c.Tests/Action/RankingBattle5Test.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash7.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Action/MimisbrunnrBattle4.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Action/RankingBattle5.cs
- Lib9c/BlockPolicySource.cs
- Lib9c/Model/Quest/QuestList.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/Model/State/WeeklyArenaState.cs
- No more weekly arena updates (HackAndSlash, MimisbrunnrBattle)
- Fixed ranking update condition (HackAndSlash, MimisbrunnrBattle)
- Added exception handling that throws an exception when executing an action with `MimisbrunnrWorldId`.
- Active `ArenaInfo` of enemy in `RankingBattle`
> Improve action speed

- .Lib9c.Tests/StagePolicyTest.cs
- Lib9c/StagePolicy.cs
This PR introduces a new stage policy for transactions to restrict transaction count per user.
> Add new StagePolicy to restrict tx count per user

- Lib9c/Model/Item/Inventory.cs
- check item count before reconfigure.
- logging reconfigre info
```
[12:03:34 INF] [UnlockInvalidSlot] agentAddress : 0xDcB9EB5A77b761e46DbE8d73C375782b082fB4c2 / avatarAddress : 0x89210CE8d4F5D1D6e750D4Cd2CA342e5D4ad037A /OrderId : d54624d8-236e-4fbe-83b6-6b6708d1b727 / itemId : 400000 / itemCount : 4
[12:03:36 INF] [UnlockInvalidSlot] agentAddress : 0xCbfC996ad185c61a031f40CeeE80a055e6D83005 / avatarAddress : 0x558eA927b9449C69577ED1E28a7C14aE0ce550DF /OrderId : 5abcd160-65b9-4074-bafc-5de52066ec54 / itemId : 400000 / itemCount : 1000
[12:03:36 INF] [UnlockInvalidSlot] agentAddress : 0xCbfC996ad185c61a031f40CeeE80a055e6D83005 / avatarAddress : 0x558eA927b9449C69577ED1E28a7C14aE0ce550DF /OrderId : 49905200-89bc-46ba-82cb-8ac176f8116f / itemId : 400000 / itemCount : 2000
[12:03:47 INF] …
```
> Logging reconfigure fungible item

- .Lib9c.Tools/SubCommand/Tx.cs
> Encode signed tx as base64 instead of hex

- .Lib9c.Tests/Action/BuyTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Model/Item/Inventory.cs
- Fix migration method (Inventory.UnlockInvalidSlot, Inventory.ReconfigureFungibleItem)
- Bugfix
> Fix migration method

- .Lib9c.Tests/Action/DailyReward5Test.cs
- .Lib9c.Tests/Action/DailyRewardTest.cs
- Lib9c/Action/DailyReward.cs
- Lib9c/Action/DailyReward5.cs
- Lib9c/BlockPolicySource.cs
> Introduce `daily_reward6` as `DailyReward`

- Lib9c/Action/Buy.cs
- Lib9c/Action/SellCancellation.cs
- Lib9c/Action/UpdateSell.cs
- Lib9c/Model/Item/Inventory.cs
> Add migration method (LockByReferringToDigestList)

- Lib9c/Model/Character/Player.cs
- Lib9c/Model/State/CombinationSlotState.cs
> Null check for a broken `AvatarState`

- .Lib9c.Tests/Action/CombinationConsumable7Test.cs
- .Lib9c.Tests/Action/CombinationEquipment7Test.cs
- .Lib9c.Tests/Action/ItemEnhancement8Test.cs
- Lib9c/Action/AttachmentActionResult.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationConsumable7.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationEquipment7.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/ItemEnhancement8.cs
- Archive `CombinationConsumable7`
- Version up `CombinationConsumable`
- Archive `CombinationEquipment7`
- Version up `CombinationEquipment`
- Archive `ItemEnhancement8`
- Version up `ItemEnhancement`
> Bug fix/action versions

- .Lib9c.Tests/Action/TransferAssetTest.cs
- .Lib9c.Tests/Action/TransferAssetTest0.cs
- Lib9c/Action/InvalidTransferUnactivatedRecipientException.cs
- Lib9c/Action/TransferAsset.cs
- Lib9c/Action/TransferAsset0.cs
> TrasnferAsset2

- .Lib9c.Tests/Action/RankingBattle5Test.cs
- .Lib9c.Tests/Lib9c.Tests.csproj
> Bug fix/reinclude excluded files

- .Lib9c.Tests/Action/CombinationConsumable7Test.cs
- .Lib9c.Tests/Action/CombinationEquipment7Test.cs
- .Lib9c.Tests/Action/ItemEnhancement8Test.cs
- Lib9c/Action/AttachmentActionResult.cs
- Lib9c/Action/CombinationConsumable.cs
- Lib9c/Action/CombinationConsumable7.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationEquipment7.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/ItemEnhancement8.cs
> Merge `rc-v100079` into `development`

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/BlockPolicyTest.cs
- .Lib9c.Tests/MemoryKeyValueStore.cs
- .Lib9c.Tests/MinerTest.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Genesis.cs
- .Lib9c.Tools/SubCommand/Store.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- .Lib9c.Tools/Utils.cs
This PR tries to catch up Libplanet's recent API changes made by the PR <https://github.com/planetarium/libplanet/pull/1492>.
> Catch up Libplanet upstream's API changes

- .Lib9c.Tests/StagePolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- Lib9c/BlockHelper.cs
> Test: following the #685

- Lib9c/TableData/Sheet.cs
> Add some logs

- Lib9c/Policy/BlockPolicySource.cs
> BlockPolicySource.GetInternalPolicy() added

- Lib9c/Renderer/ActionRenderer.cs
- Lib9c/Renderer/BlockRenderer.cs
- Clean up `BlockRenderer` and `ActionRenderer`
> Clean up renderers

- .Lib9c.Tests/Action/CombinationEquipment8Test.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Market.cs
- .Lib9c.Tools/SubCommand/Store.cs
- .Lib9c.Tools/Utils.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationEquipment8.cs
- Lib9c/Policy/BlockPolicySource.cs
- Related issue: https://github.com/planetarium/lib9c/issues/717
> Bug fix/determinism of combination equipment

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/MaxBlockBytesPolicy.cs
- Lib9c/Policy/MaxTransactionsPerSignerPerBlockPolicy.cs
- Lib9c/Policy/MinTransactionsPerBlockPolicy.cs
Closes #721. For v100086 9c-main deployment.
> Policy crafting

- Lib9c/Renderer/ActionRenderer.cs
- Lib9c/Renderer/BlockRenderer.cs
> Merge `v100085` from `main`

- .Lib9c.Tests/Model/QuestListTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash7.cs
- Lib9c/Action/HackAndSlash8.cs
- Lib9c/Action/HackAndSlash9.cs
- Lib9c/Model/Quest/QuestList.cs
> Bug fix/upate quest list with specific version

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/ActionSerializer.cs
- Lib9c.DevExtensions/TestbedHelper.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/NCActionEvaluation.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Formatters/AccountStateDeltaFormatter.cs
- Lib9c/Formatters/AddressFormatter.cs
- Lib9c/Formatters/BencodexFormatter.cs
- Lib9c/Formatters/ExceptionFormatter.cs
- Lib9c/Formatters/FungibleAssetValueFormatter.cs
- Lib9c/Formatters/NCActionFormatter.cs
- Lib9c/Formatters/NineChroniclesResolver.cs
- Lib9c/Formatters/NineChroniclesResolverGetFormatterHelper.cs
- Lib9c/Formatters/PublicKeyFormatter.cs
- Lib9c/Lib9c.csproj
- Lib9c/Renderer/ActionRenderer.cs
- resolve https://github.com/planetarium/NineChronicles.Headless/issues/860
- Use MessagePack-Chsarp for grpc serialize formatter.
- Implement NCActionEvaluation for grpc communicate.
- Use PolyMorphicAction
- Extra field for action result state(use case in RankingBattle, Buy)
> Introduce MessagePack-Csharp

- Lib9c.DevExtensions/Action/CreateTestbed.cs
- Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
- Lib9c.DevExtensions/Model/BaseTestbedModel.cs
- Lib9c.DevExtensions/Model/TestbedCreateAvatar.cs
- Lib9c.DevExtensions/Model/TestbedSell.cs
- Lib9c.DevExtensions/TestbedHelper.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/CreateAvatar0.cs
- Lib9c/GameConfig.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
1. Add testbed for customizable  create avatar
- [에디터에서 코드 수정 없이 체인의 초기 상태를 커스터마이징 가능하도록 하기](https://app.asana.com/0/958521740385861/1201200786778981/f)
- [QA 빌드 메뉴화](https://app.asana.com/0/958521740385861/1201329313121251/f)
- https://github.com/planetarium/NineChronicles/pull/992
@planetarium/9c-dev
> Add testbed for customizable  create avatar

- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- Lib9c.DevExtensions/Action/CreateTestbed.cs
- Lib9c.DevExtensions/Data/TestbedWeeklyArena.json
- Lib9c.DevExtensions/Model/TestbedSell.cs
- Lib9c.DevExtensions/Model/TestbedWeeklyArena.cs
> Introduce `TestbedWeeklyArena`

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/CreatePendingActivationsTest.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c/Action/CreatePendingActivations.cs
- Lib9c/Formatters/NCActionFormatter.cs
- Lib9c/Model/State/PendingActivationState.cs
This PR adds a new `CreatePendingActivations` action for bulk inserting many `PendingActivationState`s at once.
> Introduce CreatePendingActivations action

- Lib9c/Policy/MaxBlockBytesPolicy.cs
> Max block bytes temporary relaxation

- Lib9c/Policy/MaxBlockBytesPolicy.cs
> Policy relaxation index update

- .Lib9c.Tests/Model/State/RankingStateTest.cs
- Lib9c/Model/State/RankingState.cs
> Bug fix/deterministic of ranking state

- Lib9c/Policy/BlockPolicySource.cs
> [Bot] Merge rc-v100090 to development

- .Lib9c.Tests/StagePolicyTest.cs
- Lib9c/StagePolicy.cs
Bumps [libplanet] with new `IStagePolicy` API.
[libplanet]: https://github.com/planetarium/libplanet
> Bump libplanet and accommodate `IStagePolicy` API change

- Lib9c/Model/State/WeeklyArenaState.cs
See also:
- https://canary.discord.com/channels/539405872346955788/613670425729171456/920464205319123024
- https://canary.discord.com/channels/539405872346955788/613670425729171456/920494074476257310
- https://github.com/planetarium/lib9c/blob/v100090/Lib9c/Model/State/WeeklyArenaState.cs#L200-L218
- https://github.com/planetarium/lib9c/blob/v100092/Lib9c/Model/State/ArenaInfo.cs#L99-L111
- (planetarium internal) https://planetariumhq.slack.com/archives/C01D7N32V55/p1639524157031900
- (planetarium internal) https://www.notion.so/planetarium/2021-12-15-1-470a0216e2b44495974e68bab8f51d2d
> Fix a bug where `WeeklyArenaState` had not been reset

- Lib9c/Model/State/WeeklyArenaState.cs
> [Bot] Merge rc-v100093 to main

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/CreateAvatar0.cs
- Lib9c/Action/CreateAvatar2.cs
- Lib9c/Action/CreateAvatar3.cs
- Lib9c/Action/CreateAvatar4.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/BlockHelper.cs
- Lib9c/Model/State/RankingState.cs
- Lib9c/Model/State/RankingState0.cs
- Lib9c/Policy/BlockPolicySource.cs
This PR bumps `RankingState` model and `CreateAvatar` action to increase `RankingState.RankingMapCapacity` from 100 to 150.
> Increase capacity of ranking map state

- Lib9c/Policy/BlockPolicySource.cs
> [Bot] Merge rc-v100095 to development

- Lib9c/Policy/MaxBlockBytesPolicy.cs
> Max block bytes increased

- .Lib9c.Tests/Action/RenewAdminStateTest.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- .gitmodules
- Lib9c/Action/RenewAdminState.cs
- Lib9c/Policy/MaxBlockBytesPolicy.cs
> [Bot] Merge rc-v100098 to development

- .Lib9c.Tests/Action/RenewAdminStateTest.cs
- Lib9c/Action/RenewAdminState.cs
> [Bot] Merge rc-v100099 to main

- Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
- fix headless build. https://github.com/planetarium/NineChronicles.Headless/runs/4864425562?check_suite_focus=true
> [RC-v100100]Fix headless self contained build

- Lib9c.DevExtensions/Lib9c.DevExtensions.csproj
https://github.com/planetarium/NineChronicles.Headless/runs/4864425562?check_suite_focus=true
> [Development]Fix headless self contained build

- Lib9c/BlockHelper.cs
- Add additional actions for https://github.com/planetarium/NineChronicles.Headless/issues/1042
> Add additional actions

- Lib9c/Model/Elemental/ElementalType.cs
- Lib9c/Model/Stat/CharacterStats.cs
> Added functions for item level system

- .Lib9c.Tools/Lib9c.Tools.csproj
- Lib9c.sln
- Lib9c/Lib9c.csproj
> Downgrade `libplanet` to 0.26.4

- Lib9c/Lib9c.csproj
> update Secp256k1 to support arm64

- Lib9c/Model/Elemental/ElementalType.cs
- Lib9c/Model/Stat/CharacterStats.cs
> Revert 842

- Lib9c/Action/AccountStateDeltaExtensions.cs
> Use `IAccountStateDelta.GetStates(addresses)` in action

- Lib9c/Extensions/EquipmentExtensions.cs
> Change specification of `IsMadeWithMimisbrunnrRecipe`

- Lib9c.sln
- Lib9c/Lib9c.csproj
> Prepare v100120

- Lib9c/Action/RankingBattle.cs
tested tx: https://9cscan.com/tx/7f93dd53261fd02d31e9ca2788713beaf8fda5bba3b42a0270d3b935c46b63e0
AS-IS
```
RankingBattle Get WeeklyArenaState : 00:00:00.4665510
[16:37:56 VRB]RankingBattle Serialize WeeklyArenaState: 00:00:00.1875427
```
TO-BE
```
[18:20:39 VRB]RankingBattle Get WeeklyArenaState: 00:00:00.3497177
[18:20:39 VRB]RankingBattle Serialize WeeklyArenaState: 00:00:00.0555615
```
> Weekly arena raw dict

- Lib9c/Action/RankingBattle.cs
> Revert "Weekly arena raw dict"

- Lib9c.sln
- Lib9c/Lib9c.csproj
> downgrade libplanet

- Lib9c.sln
- Lib9c/Lib9c.csproj
> [Bot] Merge rc-v100120 to main

- Lib9c.sln
- Lib9c/Lib9c.csproj
> [Bot] Merge rc-v100120 to development

- .Lib9c.Tests/Action/RankingBattleTest.cs
- Lib9c/Action/RankingBattle.cs
Delete `Result` field for reduce memory usage.
> Delete unused Result field

- Lib9c/Action/RankingBattle.cs
- delay target index for avoid v100160 release.
> Update target index by v100160 release date

- .Lib9c.Tests/Extensions/EquipmentExtensionsTest.cs
- Lib9c/Extensions/EquipmentExtensions.cs
This pull request close [[Previewnet] Thin Ring(불) 획득 시 착용 제한 레벨이 높게 설정된 현상](https://app.asana.com/0/1133453747809944/1202023403020018/f).
> Bug fix/check equipment is mimisbrunnr

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Extensions/EquipmentExtensions.cs
- Lib9c/Model/State/AvatarState.cs
- [[전투] 전투 진행 불가 현상 (99에러 발생)](https://app.asana.com/0/1133453747809944/1202097882556709/f)
- [불속성 장비만 미미르 검사하기](https://app.asana.com/0/1133453747809944/1202097850125809/f)
> Fix rc bugs

- .github/workflows/main.yml
Besides _v\*_ tag pushes, now every push to _rc-v\*_ branches also trigger Submodule Updater.
> Trigger Submodule Updater on every push to rc-v* branches

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Extensions/EquipmentExtensions.cs
- [(구)미미르 반지 레벨 제한 표시 문제](https://app.asana.com/0/1133453747809944/1202091111966600/f)
> improve mimisbrunnr check logic

- .Lib9c.Tests/Action/RankingBattleTest.cs
- Lib9c/Action/HackAndSlash10.cs
- Lib9c/Action/MimisbrunnrBattle7.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Policy/BlockPolicySource.cs
> Merge the `rc-v100171` branch into the `main` branch

- .Lib9c.Tests/Action/GrindingTest.cs
- .Lib9c.Tests/Model/Mail/GrindingMailTest.cs
- Lib9c/Action/Grinding.cs
> Update CRYSTAL decimalPlaces

- .Lib9c.Tests/Action/GrindingTest.cs
- Lib9c/Action/Grinding.cs
- Check grinding equipment count
> Check grinding equipment count

- .Lib9c.Tests/Action/CombinationEquipment10Test.cs
- Lib9c/Action/CombinationEquipment10.cs
> backup CombinationEquipment10

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
- Lib9c/Action/AlreadyRecipeUnlockedException.cs
- Lib9c/Action/InvalidRecipeIdException.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Unlock equipment recipe pay with CRYSTAL
> Introduce UnlockEquipmentRecipe MVP

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/Scenario/CombinationAndRapidCombinationTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Add CombinationEquipment.Execute test case
- Check CRYSTAL unlock in CombinationEquipment
> CombinationEquipment Check CRYSTAL unlock

- .Lib9c.Tests/Action/RankingBattleTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Model/State/ArenaInfo.cs
- Fix the extra fields of the `RankingBattle` action.
- Minor refactor.
- Add summary to the `RankingBattle` action.
- Introduce the `ArenaInfo.Clone()` function.
> Fix extra fields of `RankingBattle`

- .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
> Add empty recipe id case

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/UnlockWorldTest.cs
- .Lib9c.Tests/CrystalCalculatorTest.cs
- .Lib9c.Tests/TableData/WorldAndStage/WorldUnlockSheetTest.cs
- Lib9c/Action/AlreadyWorldUnlockedException.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Lib9c/Action/UnlockWorld.cs
- Lib9c/Helper/CrystalCalculator.cs
- Lib9c/TableCSV/WorldAndStage/WorldUnlockSheet.csv
- Lib9c/TableData/WorldAndStage/WorldUnlockSheet.cs
- Add `WorldUnlockSheet.CRYSTAL` cost info
- unlock world by using CRYSTAL
> Introduce UnlockWorld

- .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Check recipe by ItemSubType(Weapon, Armor, etc.)
> Check previous recipe id by ItemSubType

- .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
- .Lib9c.Tests/Action/UnlockWorldTest.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Lib9c/Action/UnlockWorld.cs
- Lib9c/Addresses.cs
- transfer CRYSTAL for tracking.
> Transfer CRYSTAL instead of burn

- .Lib9c.Tests/Action/GrindingTest.cs
- .Lib9c.Tests/Action/UnlockEquipmentRecipeTest.cs
- .Lib9c.Tests/Action/UnlockWorldTest.cs
- Lib9c/Action/Grinding.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Lib9c/Action/UnlockWorld.cs
- Lib9c/Addresses.cs
- Check agent balance instead of avatar
> Change CRYSTAL per agent instead of avatar

- Lib9c/Action/HackAndSlash.cs
> Fix summary of `HackAndSlash`

- Lib9c/Model/Mail/GrindingMail.cs
- Lib9c/Model/Mail/Mail.cs
> Add MailType.Grinding

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Model/State/StakeState.cs
- Lib9c/TableData/StakeAchievementRewardSheet.cs
- Lib9c/TableData/StakeRegularRewardSheet.cs
This pull request continues from #952.
> Implement `ClaimStakeReward` action

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Model/State/StakeState.cs
- Lib9c/TableData/StakeAchievementRewardSheet.cs
- Lib9c/TableData/StakeRegularRewardSheet.cs
Reverts planetarium/lib9c#977.
> Restore `moreal/claim-stake-reward`

- .Lib9c.Tests/Action/GrindingTest.cs
- Lib9c/Action/Grinding.cs
- Lib9c/Model/Item/Inventory.cs
- Add option for charge ActionPoint in `Grinding`
> charge ap in Grinding action

- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
> Merge rc-v100192 to main

- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest1.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/HackAndSlashSweep1.cs
- Lib9c/Action/StageClearedException.cs
- Lib9c/Policy/BlockPolicySource.cs
- bugfix
- ActionObsolete : `3,975,929`
> update sweep version

- .Lib9c.Tests/Action/HackAndSlash12Test.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash12.cs
- Check world unlock with CRYSTAL
> Check CRYSTAL unlock in HackAndSlash

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/StakeTest.cs
- Lib9c/Action/ClaimMonsterCollectionReward.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/MonsterCollect.cs
- Lib9c/Action/Stake.cs
> Make stake actions polymorphic

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/Buy5Test.cs
- .Lib9c.Tests/Action/Buy6Test.cs
- .Lib9c.Tests/Action/Buy7Test.cs
- .Lib9c.Tests/Action/Buy8Test.cs
- .Lib9c.Tests/Action/Buy9Test.cs
- .Lib9c.Tests/Action/BuyMultipleTest.cs
- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/Common/Doomfist.cs
- .Lib9c.Tests/Action/DailyReward5Test.cs
- .Lib9c.Tests/Action/RankingBattle0Test.cs
- .Lib9c.Tests/Action/RankingBattle10Test.cs
- .Lib9c.Tests/Action/RankingBattle11Test.cs
- .Lib9c.Tests/Action/RankingBattle4Test.cs
- .Lib9c.Tests/Action/RankingBattle5Test.cs
- .Lib9c.Tests/Action/RankingBattle6Test.cs
- .Lib9c.Tests/Action/RankingBattle7Test.cs
- .Lib9c.Tests/Action/RankingBattle8Test.cs
- .Lib9c.Tests/Action/RankingBattle9Test.cs
- .Lib9c.Tests/Action/RankingBattleTest.cs
- .Lib9c.Tests/Action/State.cs
Fix SonarAnalyzer warning in test project
> Fix sonar warning

- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest2.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/HackAndSlashSweep2.cs
- Lib9c/Action/HackAndSlashSweep3.cs
- Lib9c/Action/StageClearedException.cs
- Lib9c/Policy/BlockPolicySource.cs
> Support challenge stage sweep

- .Lib9c.Tests/TableData/StakeAchievementRewardSheetTest.cs
- Lib9c/TableData/StakeAchievementRewardSheet.cs
> Fix StakeAchievementRewardSheet.FindLevel minimum required gold case

- .Lib9c.Tests/Action/FaucetAssetTest.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/FaucetAsset.cs
- Lib9c/Action/TransferAsset.cs
- Extract transferAsset validation for reuse.
- `FaucetAsset` from admin balance.
> Introduce FaucetAsset

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/FaucetAssetTest.cs
- Lib9c/Action/FaucetAsset.cs
- Avoid `MissingMethodException`
> Fix FaucetAsset LoadPlainValue

- Lib9c/Policy/PermanentBlockPolicySource.cs
Adding new miner addresses of players that want to participate mining in the `Previewnet`.
> Add new permissioned miners in `Previewnet`

- .Lib9c.Tests/Action/BattleArenaTest.cs
- .Lib9c.Tests/Model/Arena/ArenaPlayerDigestTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Model/Arena/ArenaInformation.cs
- Lib9c/Model/Arena/ArenaPlayerDigest.cs
- Lib9c/Model/Character/EnemyPlayer.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/SerializeKeys.cs
- Lib9c/TableData/ArenaSheet.cs
Only parts related to the Join Arena action were taken from https://github.com/planetarium/lib9c/pull/1006
---
- Create `BattleArena` action
- This is the action that replaces `RankingBattle`
> Introduce BattleArena action

- Lib9c/Action/Stake.cs
> Do not fetch unused sheet

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
- Lib9c/Action/MigrateMonsterCollection.cs
> Make `MigrateMonsterCollection` action as polymorphic

- Lib9c/Action/BattleArena.cs
> Update arena avatar state level in BattleArena action

- .Lib9c.Tests/Action/BattleArenaTest.cs
- .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/Battle/HitHelper.cs
- Lib9c/TableCSV/Arena/ArenaSheet.csv
- Lib9c/TableCSV/Item/MaterialItemSheet.csv
> Added reboot arena scenario test

- .Lib9c.Tests/Action/BattleArenaTest.cs
- .Lib9c.Tests/Action/JoinArenaTest.cs
- .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
- .Lib9c.Tests/TableData/ArenaSheetTest.cs
- .Lib9c.Tests/TableSheetsImporter.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/JoinArena.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/TableCSV/Arena/ArenaSheet.csv
- Lib9c/TableData/ArenaSheet.cs
- Rename ArenaSheet.Row.Id to ChampionshipId
- Add ArenaSheet.GetRowByBlockIndex()
- Add ArenaSheet.GetRoundByBlockIndex()
- Add ArenaSheet.Row.ChampionshipNumber
- Add ArenaSheet.RoundData.ChampionshipNumber
> Improve ArenaSheet

- Lib9c/TableCSV/Crystal/CrystalFluctuationSheet.csv.meta
> Add meta file of CrystalFluctuationSheet.csv

- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Policy/BlockPolicySource.cs
> chore: remove policies not required in PBFT

- Lib9c/Helper/CrystalCalculator.cs
remove agentAddress and balance and stakeRegularRewardSheet, replace to staking level
> Introduce oveloading of `CaculateCrystal()`

- .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
- Lib9c/Action/MigrateMonsterCollection.cs
- Lib9c/Model/State/StakeState.cs
This commit was already applied by #1110 but I opened a new pull request for a hotfix.
> hotfix: Correct `MigrateMonsterCollection` action

- Lib9c/Policy/PermanentBlockPolicySource.cs
Adding new miners for the next update.
> add miner addresses

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Action/CombinationEquipment.cs
> Fixed crystal cost

- Lib9c/TableCSV/StakeRegularFixedRewardSheet.csv.meta
> Add meta file of StakeRegularFixedRewardSheet.csv

- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
> Trust lockup interval processing

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Update CombinationEquipment for previewnet chain consistency
> CombinationEquipment chain consistency in previewnet

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
- .Lib9c.Tests/Action/StakeTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/MigrateMonsterCollection.cs
- Lib9c/Action/Stake.cs
- Lib9c/Model/State/MonsterCollectionState.cs
- Correct chain consistency
- Hardfork `MonsterCollectionState` for internal reason.
> Correct chain consistency & Hardfork for internal reason

- .Lib9c.Tests/Action/HackAndSlashSweep2Test.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest3.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlashSweep.cs
- sweep validate crystal unlock.
> Check crystal unlock in sweep action

- Lib9c/Policy/PermanentBlockPolicySource.cs
> Add new miner address

- Lib9c/Action/HackAndSlash.cs
> Cherry-pick #1149 to 2022q2

- .Lib9c.Tests/Action/GrindingTest.cs
- Lib9c/Action/Grinding.cs
> Remove throwing InvalidEquipmentException in Grinding

- Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
Fix attack log parameter (elemental type)
> Fix attack log parameter

- .Lib9c.Tests/Action/RewardGoldTest.cs
- Lib9c/Action/RewardGold.cs
Fix `InvalidStateRootHashException` before patch table.
> Fix InvalidStateRootHashException in mainnet

- Lib9c/Arena/ArenaHelper.cs
> Update arena score limits

- Lib9c/Arena/ArenaHelper.cs
> Fix cost formula of joining arena

- .Lib9c.Tests/Action/BattleArenaTest.cs
- .Lib9c.Tests/Action/JoinArenaTest.cs
- Lib9c/Action/JoinArena.cs
> Added level limit to 'JoinArena' action

- Lib9c/Action/BattleArena.cs
> Add variable to BattleArena action

- .Lib9c.Tests/Model/Arena/ArenaInformationTest.cs
- Lib9c/Model/Arena/ArenaInformation.cs
- Lib9c/Model/Arena/ArenaScore.cs
- Add `PurchasedTicketCount` in ArenaInformation
- Update constructor parameter in ArenaScore
> Update arena states

- .Lib9c.Tests/Action/ArenahelperTest.cs
- .Lib9c.Tests/Action/BattleArena1Test.cs
- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena1.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/Model/Arena/ArenaExceptions.cs
- Lib9c/Model/Arena/ArenaInformation.cs
- Lib9c/Policy/BlockPolicySource.cs
- Target version : `v100240`
- Add ticket purchase function
- Fixed to only allow a single battle during the season
- Related link:
-  https://www.notion.so/planetarium/4-d41f04d0afdf44f8b51e9250c5fa4528
-  https://planetariumhq.slack.com/archives/C03BU3JTKAN/p1656466364090499
- ![image](https://user-images.githubusercontent.com/40553495/176136470-3cc27044-09d5-408d-ba97-6dc8070ec3a4.png)
> Update BattleArena Action

- .Lib9c.Tests/Model/ArenaSimulatorTest.cs
- Lib9c/Action/BattleArena1.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Skill/Arena/ArenaAreaAttack.cs
- Lib9c/Model/Skill/Arena/ArenaBlowAttack.cs
- Lib9c/Model/Skill/Arena/ArenaBuffSkill.cs
- Lib9c/Model/Skill/Arena/ArenaDoubleAttack.cs
- Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
- Lib9c/Model/Skill/Arena/ArenaNormalAttack.cs
- Lib9c/Model/Skill/Arena/ArenaSkill.cs
- Target version : `v100240`
- Related links 
- [[아레나] 전투가 체력에 상관없이 종료되는 현상](https://app.asana.com/0/1133453747809944/1202522590392809/f)
- [Slack](https://planetariumhq.slack.com/archives/CBU2JFAF3/p1656411409690619)
> Fixed to update arena HP*2 when buff stats change

- .Lib9c.Tests/Action/RapidCombination6Test.cs
- .Lib9c.Tests/Action/RapidCombinationTest.cs
- Lib9c/Action/ItemEnhancement10.cs
- Lib9c/Action/ItemEnhancement9.cs
- Lib9c/Action/RapidCombination.cs
- Lib9c/Action/RapidCombination6.cs
- Lib9c/Extensions/CombinationSlotStateExtensions.cs
- Hard fork extensions for `CombinationSlotState`
- Hard fork `RapidCombination`
> Hard fork extensions for `CombinationSlotState` and others

- .Lib9c.Tests/Action/RaidTest.cs
- .Lib9c.Tests/TableSheets.cs
- Lib9c/Action/Raid.cs
- Lib9c/Addresses.cs
- Lib9c/Model/State/RaiderState.cs
- Lib9c/Model/State/WorldBossState.cs
- Lib9c/TableCSV/WorldBoss.meta
- Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
- Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv.meta
- Lib9c/TableData/WorldBossListSheet.cs
- Join boss raid
- use & refill ticket
- Get score(hardcoded)
- Change boss level
> Introduce Raid MVP

- .Lib9c.Tests/Model/Arena/PlayerDigestTest.cs
- .Lib9c.Tests/Model/ArenaSimulatorTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena1.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Arena/ArenaSimulator2.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/EnemyPlayer.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/Character/PlayerDigest.cs
> Rename `ArenaPlayerDigest` to `PlayerDigest`.

- .Lib9c.Tests/Action/HackAndSlashTest14.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash14.cs
- Lib9c/Model/State/CrystalRandomSkillState.cs
- Upgrade HAS version to 15
- Disable reset of star count on stage failure.
[스테이지 1회성 버프 개선 - Star수 Reset 타이밍 변경](https://app.asana.com/0/0/1202620018752886/f)
> keeping star count

- Lib9c/Action/HackAndSlash.cs
SSIA
I thought it would be nice if I could get the execution result with no IActionContext, just the states.
So I made it.
```cs
public IAccountStateDelta Execute(IAccountStateDelta states,
Address signer,
long blockIndex,
IRandom random)
```
> Introduce `HackAndSlash.Execute()` with `IActionContext` argument

- Lib9c/Action/HackAndSlash12.cs
- Lib9c/Policy/BlockPolicySource.cs
> add actionObsolete to `HackAndSlash12`

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/RaidTest.cs
- .Lib9c.Tests/Action/WorldBossHelperTest.cs
- Lib9c/Action/Raid.cs
- Lib9c/Helper/InventoryExtensions.cs
- Lib9c/Helper/WorldBossHelper.cs
- Lib9c/Model/State/RaiderState.cs
- Fix raid bug.
- Update `RaiderState` for DP table
> Improve RaiderState for DataProvider

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
- .Lib9c.Tests/Action/RaidTest.cs
- .Lib9c.Tests/Action/WorldBossHelperTest.cs
- Lib9c/Action/ClaimRaidReward.cs
- Lib9c/Action/Raid.cs
- Lib9c/Helper/InventoryExtensions.cs
- Lib9c/Helper/WorldBossHelper.cs
- Lib9c/Model/State/RaiderState.cs
- Change rune mint address form agent to avatar.
> Change rune address from agent to avatar

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/HackAndSlash15Test.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash15.cs
- Lib9c/Helper/Validator.cs
SSIA
The `PlayCount` field controls loop count of `StageSimulator.Simulate(1)`.
> Add PlayCount:int field to HackAndSlash and Version up

- Lib9c/TableCSV/WorldBoss/WorldBossKillRewardSheet.csv.meta
> Add WorldBossKillRewardSheet meta file

- Lib9c/Battle/RaidBoss.cs
- Lib9c/Battle/RaidSimulator.cs
> [bugfix] Clone enemy model on spawn event in simulator.

- .Lib9c.Tests/Action/RaidTest.cs
- Lib9c/Action/Raid.cs
- Lib9c/Helper/WorldBossHelper.cs
- Lib9c/Model/State/RaiderState.cs
- Lib9c/Model/State/WorldBossKillRewardRecord.cs
- Update raiderState model
- Implement missing `IDictionary.Add()`
- change refill ticket logic
- claim kill reward in raid action
> claim kill reward in Raid action

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- .Lib9c.Tests/Model/BattleLogTest.cs
- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Battle/StageSimulator.cs
- [Remove playCount argument in StageSimulator.Simulate()](https://github.com/planetarium/lib9c/commit/357f2080754952ae97243f44d40e94bc2bd0679f)
- [Change playCount argument to waveRewards in new StageSimulator()](https://github.com/planetarium/lib9c/commit/c541bfe11267e40af2759a40a69def94dcd6d95d)
> Refactor StageSimulator

- .Lib9c.Tests/Action/BattleArenaTest2.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena2.cs
- Lib9c/Arena/ArenaHelper.cs
- Hard fork arena helper - Add limit to offseason user by score.
[아레나 오프시즌에도 validatation 추가 체크](https://app.asana.com/0/958521740385861/1202695992585401/f)
> Add validatation to Arena OffSeason

- Lib9c/TableCSV/WorldBoss/WorldBossRankingRewardSheet.csv.meta
> Add sheet meta file (WorldBossRankingRewardSheet)

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/EventConsumableItemCraftsTest.cs
- .Lib9c.Tests/Action/EventDungeonBattleTest.cs
- .Lib9c.Tests/TableData/Event/EventConsumableItemRecipeSheetTest.cs
- .Lib9c.Tests/TableSheets.cs
- Lib9c/Action/EventConsumableItemCrafts.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/NotEnoughClearedStageLevelException.cs
- Lib9c/Extensions/CombinationSlotStateExtensions.cs
- Lib9c/Extensions/EventRecipeExtensions.cs
- Lib9c/Extensions/EventScheduleExtensions.cs
- Lib9c/Extensions/MaterialItemSheetExtensions.cs
- Lib9c/Extensions/WorldInformationExtensions.cs
- Lib9c/Model/State/CombinationSlotState.cs
- Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv
- Lib9c/TableCSV/Event/EventConsumableItemRecipeSheet.csv.meta
- Lib9c/TableData/Event/EventConsumableItemRecipeSheet.cs
- based on #1218  
- Introduce `EventConsumableItemRecipeSheet` based on `ConsumableItemRecipeSheet`
- Introduce `EventConsumableItemCrafts` action
> Introduce `EventConsumableItemCrafts` action

- .Lib9c.Tests/Model/State/HammerPointStateTest.cs
- Lib9c/Addresses.cs
- Lib9c/Model/State/HammerPointState.cs
SSIA
```
public class HammerPointState : IState
{
public Address Address { get; }
public int RecipeId { get; }
public int HammerPoint { get; private set; }
}
```
> Introduce `HammerPointState` for new feature of combination

- Lib9c.DevExtensions/Data/TestbedCreateAvatar.json
- Lib9c.DevExtensions/Model/TestbedCreateAvatar.cs
- Lib9c/Action/CreateAvatar0.cs
How to use
1. Input food count
2. Click `Export` button
3. Make Genesis block
> Add food in testbed

- .Lib9c.Tests/Action/TransferAsset2Test.cs
- .Lib9c.Tests/Action/TransferAssetTest.cs
- Lib9c/Action/TransferAsset.cs
- Lib9c/Action/TransferAsset2.cs
> TransferAsset allow send avatar

- Lib9c/Action/Raid.cs
- Lib9c/GameConfig.cs
> Update game config

- .Lib9c.Tests/Action/RaidTest.cs
- Lib9c/Action/Raid.cs
- Fix indent by incorrectly merge conflict.
> Fix simulate call without level check

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- Lib9c/Action/Raid.cs
- Fix missing serialize `payNcg`
> Fix Raid action serialize

- Lib9c/Action/Raid.cs
> Apply equipments on raid battle simulation.

- .Lib9c.Tests/Lib9c.Tests.csproj
This pull request cherry-picks #1280 #1278
> Cherry pick commits related to dependencies

- .Lib9c.Tests/Action/CreateAvatarTest.cs
- Lib9c/Action/CreateAvatar.cs
- Delete mint NCG in `CreateAvatar`
> Delete mint NCG

- .Lib9c.Tests/Lib9c.Tests.csproj
- Lib9c/Action/Raid.cs
> 20220810 merge worldboss into internal test

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- Lib9c/Action/ClaimRaidReward.cs
- Lib9c/Action/ClaimWordBossKillReward.cs
fix serialize / deserialize world boss actions
> Fix deserialize action

- .Lib9c.Tests/Action/PrepareRewardAssetsTest.cs
- Lib9c/Action/PrepareRewardAssets.cs
- mint assets for reward pool(e.g world boss)
- prevent mint NCG
> Introduce PrepareRewardAssets

- .Lib9c.Tests/Action/UnlockWorld1Test.cs
- Lib9c/Action/UnlockWorld.cs
- Lib9c/Action/UnlockWorld1.cs
> Add checking `worldInformation.IsStageCleared` in `UnlockWorld` action

- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Action/CombinationEquipment.cs
> Block super craft with mimis recipe 

- .Lib9c.Tests/Action/HackAndSlash16Test.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash15.cs
- Lib9c/Action/HackAndSlash16.cs
- Lib9c/Helper/Validator.cs
- Fix bug in `Validator.ValidateForHackAndSlash` about not updating new-world.
> Version up HAS16 to 17

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- Lib9c/Action/PrepareRewardAssets.cs
> Fix serialize, deserialize PrepareRewardAssets

- .Lib9c.Tests/Action/EventDungeonBattleTest.cs
- .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
- .Lib9c.Tests/Extensions/EventScheduleExtensionsTest.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/EventDungeonBattleV1.cs
- Lib9c/Extensions/EventScheduleExtensions.cs
- Lib9c/TableCSV/Event/EventScheduleSheet.csv
- Lib9c/TableData/Event/EventScheduleSheet.cs
Resolve [[이벤트 던전] 추가 티켓 가격 공식이 의도와 다르게 되어있는 현상](https://app.asana.com/0/1133453747809944/1202845469995714/f)
> Bug fix/event dungeon tickets price

- README.md
> Add Discord invitation buttons

- .Lib9c.Tests/Action/BattleArena2Test.cs
- .Lib9c.Tests/Action/BattleArena3Test.cs
- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena1.cs
- Lib9c/Action/BattleArena2.cs
- Lib9c/Action/BattleArena3.cs
- Lib9c/Model/Arena/ArenaExceptions.cs
- Lib9c/Model/State/ArenaAvatarState.cs
- Lib9c/Policy/BlockPolicySource.cs
- Add new validation to battle arena action
- Exception occurs if the last completed Arena Battle is more than 2 blocks different from the current one.
[아레나 validation 추가](https://app.asana.com/0/958521740385861/1202852976182381/f)
> Add new validation to battle arena action

- .Lib9c.Tests/Action/CombinationEquipment13Test.cs
- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/CombinationEquipment13.cs
- Lib9c/Action/NotEnoughHammerPointException.cs
- Lib9c/Policy/BlockPolicySource.cs
> Hotfix super craft

- .Lib9c.Tests/Action/CombinationEquipment13Test.cs
> Fix compile error in CombinationEquipment13Test

- .Lib9c.Tests/Action/RawState.cs
- .Lib9c.Tests/Action/State.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/Action/Buy0.cs
- Lib9c/Action/Buy2.cs
- Lib9c/Action/Buy3.cs
- Lib9c/Action/Buy4.cs
- Lib9c/Action/CombinationEquipment3.cs
- Lib9c/Action/CombinationEquipment4.cs
- Lib9c/Action/CombinationEquipment5.cs
- Lib9c/Action/CombinationEquipment6.cs
- Lib9c/Action/CombinationEquipment7.cs
- Lib9c/Action/MonsterCollect.cs
- Lib9c/Action/MonsterCollect0.cs
- Lib9c/Action/MonsterCollect2.cs
- Lib9c/Extensions/SheetsExtensions.cs
- Lib9c/Policy/BlockPolicySource.cs
⬆️ 
Related: planetarium/NineChronicles.Headless#1518, planetarium/NineChronicles#1838
> ⬆️ Bump libplanet to 0.41.0

- .Lib9c.Tests/Model/State/StakeStateTest.cs
- Lib9c/Model/State/StakeState.cs
This pull request tries to fix https://github.com/planetarium/lib9c/issues/1251.
> Make staking able to claim stake reward at static reward interval

- Lib9c/Battle/RaidBoss.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Model/Character/CharacterBase.cs
> Fix `OnPostSkill` order

- .Lib9c.Tests/Action/HackAndSlashTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash17.cs
- Lib9c/Helper/Validator.cs
> Update Validator.ValidateForHackAndSlash to using costAp argument

- Lib9c/Action/AccountStateDeltaExtensions.cs
> Fix 99 error

- .Lib9c.Tests/Action/WorldBossHelperTest.cs
- Lib9c/Helper/WorldBossHelper.cs
> Fixed World Boss ticket refill logic

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/State.cs
- Lib9c/BlockHelper.cs
- Lib9c/Miner.cs
- Lib9c/Policy/BlockPolicy.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
- Lib9c/ReorgMiner.cs
> [PBFT] Bump Libplanet 

- Lib9c/Action/HackAndSlashSweep4.cs
Resolves https://github.com/planetarium/lib9c/issues/1357.
> fix exception handling in Block `#4374126`

- .Lib9c.Tests/Action/BattleArena4Test.cs
- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena4.cs
Resolve https://github.com/planetarium/NineChronicles/issues/1933
> Hard fork `BattleArena` from 4 to 5

- Lib9c/Action/Raid.cs
- Lib9c/Battle/RaidSimulator.cs
- Apply used consumable on states.
- Calculate battle reward based on dealt damage instead of wave number.
> Bug fixes in raid

- .Lib9c.Tests/Action/Sell10Test.cs
- Lib9c/Action/Sell10.cs
Resolve https://github.com/planetarium/lib9c/issues/1369
> Hard fork `Sell` from 10 to 11

- Lib9c/Action/Buy5.cs
- Lib9c/Action/Buy6.cs
- Lib9c/Action/Buy7.cs
- Lib9c/Action/Sell4.cs
- Lib9c/Action/Sell5.cs
- Lib9c/Action/Sell6.cs
- Lib9c/Action/SellCancellation5.cs
- Lib9c/Action/SellCancellation6.cs
- Lib9c/Policy/BlockPolicy.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
- Lib9c/Secp256K1CryptoBackend.cs
> [PBFT] Bump/libplanet

- .Lib9c.Tests/Action/ClaimRaidRewardTest.cs
- .Lib9c.Tests/Action/RaidTest.cs
> Resolving test code errors

- Lib9c/Model/Character/CharacterBase.cs
> Prevent adding duplicated dead log in battle.

- .Lib9c.Tests/Action/WorldBossHelperTest.cs
- Lib9c/Helper/WorldBossHelper.cs
> Fix world boss challenge refill interval

- .Lib9c.Tests/Action/Raid0Test.cs
- .Lib9c.Tests/Action/RaidTest.cs
- Lib9c/Action/Raid.cs
- Lib9c/Action/Raid0.cs
- Lib9c/Addresses.cs
- Obsolete `Raid` from next season(gte 2)
- Save raiderState address list for migration and find total raider information
> Hard fork raid action

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Action/Buy5.cs
- Lib9c/Action/Buy6.cs
- Lib9c/Action/Buy7.cs
- Lib9c/Action/PrepareRewardAssets.cs
- Lib9c/Action/Sell4.cs
- Lib9c/Action/Sell5.cs
- Lib9c/Action/Sell6.cs
- Lib9c/Action/SellCancellation5.cs
- Lib9c/Action/SellCancellation6.cs
- Lib9c/Policy/BlockPolicy.cs
- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
- Lib9c/Policy/MaxBlockBytesPolicy.cs
> ⬆️ Bump libplanet to 0.42.2

- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tools/SubCommand/State.cs
> Bump libplanet to 0.43.0

- Lib9c/TableCSV/Skill/BuffSheet.csv.meta
> Add BuffSheet.csv.meta

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorsPolicy.cs
Pretty lousy solution for testing. 😥
> Test validator key and policy added

- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Policy/BlockPolicySource.cs
> Handling v100302~v100310/Simulator

- LICENSE
SSIA.
If more reviewers are required, please request them also 🙏🏻
> Use GPL v3.0 LICENSE

- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Policy/BlockPolicySource.cs
> Merge rc-v100311 to main

- .Lib9c.Tests/Action/EquipRuneTest.cs
- .Lib9c.Tests/Action/RuneEnhancementTest.cs
- .Lib9c.Tests/Model/Rune/RuneSlotTest.cs
- .Lib9c.Tests/Model/RuneSlotStateTest.cs
- Lib9c/Action/EquipRune.cs
- Lib9c/Action/RuneSlotInfo.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Model/EnumType/BattleType.cs
- Lib9c/Model/EnumType/RuneSlotType.cs
- Lib9c/Model/Rune/RuneExceptions.cs
- Lib9c/Model/Rune/RuneSlot.cs
- Lib9c/Model/State/RuneSlotState.cs
- State
- **RuneSlotState**
- **RuneSlot**
- Action
- **EquipRune**
- Data Transfer Object
- **RuneSlotInfo**
- Enum
- **RuneSlotType**
- **BattleType**
> Introduce rune slot content

- .Lib9c.Tests/Action/BattleArena5Test.cs
- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena5.cs
- Lib9c/Model/State/GameConfigState.cs
- Lib9c/TableCSV/GameConfigSheet.csv
- Edit BattleArena interval
- Add `battle_arena_interval` row to GameConfigSheet
[아레나 배틀 인터벌 수정](https://app.asana.com/0/958521740385861/1203264848476239/f)
> Edit BattleArena interval

- Lib9c/TableCSV/Rune/RuneStatSheet.csv
- Lib9c/TableCSV/Skill/ActionBuffSheet.csv
- Lib9c/TableCSV/Skill/SkillSheet.csv
- Lib9c/TableData/Rune/RuneStatSheet.cs
> add Rune Skill Stat Buff

- .Lib9c.Tests/Action/UpdateSell3Test.cs
- .Lib9c.Tests/Action/UpdateSellTest.cs
- Lib9c/Action/UpdateSell.cs
- Lib9c/Action/UpdateSell3.cs
- set updateSellInfos capacity
> Set UpdateSell.updateSellInfos capacity

- Lib9c/Model/Character/Player.cs
- Lib9c/TableCSV/Rune/RuneOptionSheet.csv
- Lib9c/TableData/Rune/RuneOptionSheet.cs
> Add value type for rune skill power

- Lib9c.MessagePack/Action/NCActionEvaluation.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Lib9c.csproj
- Lib9c/Model/BattleStatus/Arena/ArenaSkill.cs
- Lib9c/Model/BattleStatus/Skill.cs
- Lib9c/Model/State/ArenaAvatarState.cs
- Lib9c/Model/State/CrystalCostState.cs
- Lib9c/TableData/Sheet.cs
This pull request replaces `JetBrains.Annotations`' `CanBeNull` with .NET nullable reference check.
It requires merging previous pull requests.
> Replace `JetBrains.Annotations` with .NET nullable refernce check

- Lib9c/Helper/RuneHelper.cs
> Remove `Jetbrains.Annotations` using

- Lib9c/TableCSV/RuneListSheet.csv
Rune Data Update
RuneList Grade Change
> Update Rune List Grade Change

- Lib9c.MessagePack/Action/NCActionEvaluation.cs
> Fix argument type of `NCActionEvaluation`

- Lib9c/Battle/HitHelper.cs
- Lib9c/Battle/RaidBoss.cs
- Lib9c/Battle/RaidSimulator.cs
- Lib9c/Battle/RaidSimulatorV1.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/CharacterBase.cs
- Apply new hit correction method(same with arena) on raid battle.
> Apply new hit correction method on raid

- .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
- Lib9c/Action/RuneEnhancement.cs
- Lib9c/Model/EnumType/BattleType.cs
- Lib9c/Model/State/RuneSlotState.cs
Rune slot status updates when upgrading runes
> Update rune slot states

- .Lib9c.Tests/Action/BattleGrandFinaleTest.cs
- .Lib9c.Tests/Model/GrandFinale/GrandFinaleInformationTest.cs
- Lib9c/Action/BattleGrandFinale.cs
- Lib9c/Model/GrandFinale/GrandFinaleInformation.cs
> Seperate Score from `GrandFinaleInformation`

- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/ClaimStakeReward1.cs
- Lib9c/Action/ClaimStakeReward3.cs
- Lib9c/Action/IClaimStakeReward.cs
> Introduce `IClaimStakeReward` interface and apply to actions

- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/ClaimStakeReward1.cs
- Lib9c/Action/ClaimStakeReward3.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
- Lib9c/Action/IClaimStakeReward.cs
The action factories provides two methods to create an action.
1. `CreateByBlockIndex()`
2. `CreateByVersion()`
This pull request is based on #1530.
> Introduce `ClaimStakeRewardFactory`

- .Lib9c.Tests/Action/TransferAssetsTest.cs
- Lib9c/Action/ITransferAssets.cs
- Lib9c/Action/TransferAssets.cs
Introduce `TransferAssets` action for bulk transfer asset.
> Introduce TransferAssets

- .Lib9c.Tests/Action/RuneSlotInfoTest.cs
- .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
- .Lib9c.Tests/Model/Arena/PlayerDigestTest.cs
- .Lib9c.Tests/Model/Rune/RuneSlotTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/JoinArena.cs
- Lib9c/Action/MimisbrunnrBattle.cs
- Lib9c/Action/Raid.cs
- Lib9c/Action/RuneEnhancement.cs
- Lib9c/Action/RuneSlotInfo.cs
- Lib9c/Battle/RaidSimulator.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/ArenaPlayerDigest.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/Rune/RuneExceptions.cs
- Lib9c/Model/Rune/RuneSlot.cs
- Lib9c/Model/State/RuneSlotState.cs
> Fix state related to rune

- .Lib9c.Tests/Action/TransferAssetsTest.cs
- Lib9c/Action/TransferAssets.cs
Set recipients capacity for execution time.
1958(season 1 total)
```
[18:47:09 DBG] [CFCd6565287314FF70e4C4CF309dB701C43eA5bD, CFCd6565287314FF70e4C4CF309dB701C43eA5bD]TransferAsset4 Total Executed Time: 00:00:13.8864230
```
season1 top 200 with 1tx
```
[20:09:24 DBG] [CFCd6565287314FF70e4C4CF309dB701C43eA5bD, CFCd6565287314FF70e4C4CF309dB701C43eA5bD]TransferAsset4 Total Executed Time: 00:00:01.6131090
```
season1 top 200 with 2 tx
```
[20:12:29 DBG] [CFCd6565287314FF70e4C4CF309dB701C43eA5bD, CFCd6565287314FF70e4C4CF309dB701C43eA5bD]TransferAsset4 Total Executed Time: 00:00:00.2464440
[20:14:46 DBG] [CFCd6565287314FF70e4C4CF309dB701C43eA5bD, CFCd6565287314FF70e4C4CF309dB701C43eA5bD]TransferAsset3 exec started
[20:14:46 DBG] [CFCd6565287314FF70e4C4CF309dB701C43eA5bD, …
```
> TransferAssets set recipients capacity

- .Lib9c.Tests/Action/DailyRewardTest.cs
- Lib9c/Action/DailyReward.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Model/State/GameConfigState.cs
- Lib9c/TableCSV/GameConfigSheet.csv
> Add daily rune reward

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorsPolicy.cs
> 🗃️ [PBFT] Updated policy for testing

- Lib9c/Policy/BlockPolicySource.cs
> 🗃️ [PBFT] Changed to use smaller set of validators

- Lib9c/Policy/MinBlockProtocolVersionPolicy.cs
> 🗃️ [PBFT] Updated policy for pbft-pow

- Lib9c/Policy/ValidatorsPolicy.cs
> 🗃️ [PBFT] Updated policy for pbft

- Lib9c.Miner/Miner.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
> ♻️ [PBFT] Changes to allow Unity client development

- Lib9c.Miner/Miner.cs
- Lib9c/Policy/DebugPolicy.cs
> 🧹 [PBFT] Policy cleanup

- Lib9c/Policy/BlockPolicySource.cs
> 🧹 [PBFT] Fixed unity editor code under directive

- Lib9c/TableCSV/Skill/StatBuffSheet.csv
SSIA
- No need to be considered for internal test.
> Fix icon resource column

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Policy/BlockPolicy.cs
- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/DebugPolicy.cs
- Lib9c/Policy/MinBlockProtocolVersionPolicy.cs
It consists of these cherry-picks
- 623fa547cfcd5475c66af0049c8a89c6bf22c531
- e36166ba088db48993943b6c8bd6f487d6c13410
> Bump Libplanet to 0.45.0

- Lib9c/Model/Skill/AttackSkill.cs
- Lib9c/Model/Stat/Stats.cs
> Apply damage reduction rate in permyriad

- .Lib9c.Tests/Action/BattleArena6Test.cs
- .Lib9c.Tests/Action/BattleArena7Test.cs
- .Lib9c.Tests/Action/JoinArena0Test.cs
- Lib9c/Action/BattleArena6.cs
- Lib9c/Action/JoinArena0.cs
- Lib9c/Policy/BlockPolicySource.cs
> Exception handling for arena actions

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorsPolicy.cs
Also adds additional external validators.
> ⬆️ [PBFT] Bump libplanet

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorsPolicy.cs
> 🔧 [PBFT] Updated validators policy

- .Lib9c.Tests/Action/RewardGoldTest.cs
- Lib9c/Policy/BlockPolicySource.cs
> fix: update validator admin

- Lib9c/Renderer/ActionRenderer.cs
> Fix ActionRenderer not to cast SystemAction

- .Lib9c.DevExtensions.Tests/Action/FaucetCurrencyTest.cs
- .Lib9c.DevExtensions.Tests/Action/FaucetRuneTest.cs
- .Lib9c.DevExtensions.Tests/TableSheetsImporter.cs
- .Lib9c.Tests/TableSheetsImporter.cs
> Fix `TableSheetsImporter`

- .Lib9c.Tests/Model/State/StateExtensionsTest.cs
- Lib9c/Model/State/StateExtensions.cs
> Fix `ToLong()` extension method

- Lib9c/Model/Item/Inventory.cs
SSIA
So far, we've been blocking malfunctions in the action.
> Add handling about negative count at `Inventory.RemoveFungibleItem()`

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorsPolicy.cs
> ⬆️ [PBFT] Updated policy to include additional external validatros

- .Lib9c.Tests/Action/Raid0Test.cs
- .Lib9c.Tests/Action/Raid1Test.cs
- .Lib9c.Tests/Action/Raid2Test.cs
- .Lib9c.Tests/Action/Raid3Test.cs
- Lib9c/TableCSV/WorldBoss/WorldBossListSheet.csv
Fix raid test to handle various data
> Improve raid test

- Lib9c.DevExtensions/Action/FaucetRune.cs
- Lib9c.DevExtensions/Action/Interface/IFaucetCurrency.cs
- Lib9c.DevExtensions/Action/Interface/IFaucetRune.cs
> Fix syntax to make compilable in 9c client.

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Action/RawState.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/State.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Action/ActionBase.cs
- Lib9c/BlockHelper.cs
- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorAdminPolicy.cs
- Lib9c/Renderer/ActionRenderer.cs
- Add validator admin policy
- Add proper test for validator admin
> Add validator admin

- .Lib9c.Tests/Action/RewardGoldTest.cs
> Bump libplanet-pow-dynamic-validator

- .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
- .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
- .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
- .Lib9c.DevExtensions.Tests/TableSheetsImporter.cs
- .Lib9c.Tests/TableSheetsImporter.cs
- Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
- Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
- Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
- Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- CreateOrReplaceAvatar: Only for dev extensions.
- Create or replace specific AvatarState with many properties(e.g., level, equipments with enhancement)
- CreateOrReplaceAvatarFactory: Only for dev extensions.
- Factory for CreateOrReplaceAvatar.
- Lib9c.MessagePack.csproj edit: Add `Debug DevEx` configuration.
> [DevExtensions]CreateOrReplaceAvatar

- Lib9c.Abstractions/IActivateAccount.cs
- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.Miner/Miner.cs
- Lib9c.sln
- Lib9c/Action/ActivateAccount.cs
- Lib9c/Action/ActivateAccount0.cs
- Lib9c/Lib9c.csproj
- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
This reverts commit 1c339c6fed30d52ea110c2477bca9e861b66acc3, reversing changes made to ef41792c15193fc47fceec22d08b98a4fdf25ae3.
> Revert "Merge pull request #1618 from moreal/revert-1580"

- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/CreateAvatar0.cs
- Lib9c/TableCSV/Skill/StatBuffSheet.csv
> Add runes on `CreateAvatar` when executing on editor mode.

- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Formatters/NineChroniclesResolverGetFormatterHelper.cs
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Miner/Lib9c.Miner.csproj
- Libplanet.Crypto.Secp256k1/Libplanet.Crypto.Secp256k1.csproj
- Remove `ImplicitUsings` property.
- Set `OutputPath` and `IntermediateOutputPath` properties.
> Edit project settings

- .Lib9c.Tests/Action/HackAndSlash19Test.cs
- .Lib9c.Tests/Action/HackAndSlash20Test.cs
- .Lib9c.Tests/Action/Scenario/RuneScenarioTest.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlash19.cs
- Lib9c/Helper/Validator.cs
- Add field: `ApStoneCount:int`
- Add throwing Exception `InvalidRepeatPlayException`, `NotEnoughMaterialException`, `UsageLimitExceedException`
- Remove throwing Exception `PlayCountIsZeroException`
> Introduce hack_and_slash20

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Scenario/SellAndCancellationAndSellTest.cs
- .Lib9c.Tests/Action/Sell11Test.cs
- .Lib9c.Tests/Action/UpdateSell4Test.cs
- Lib9c.Miner/Miner.cs
- Lib9c/Action/Buy6.cs
- Lib9c/Action/Buy7.cs
- Lib9c/Action/Sell.cs
- Lib9c/Action/Sell10.cs
- Lib9c/Action/Sell11.cs
- Lib9c/Action/UpdateSell.cs
- Lib9c/Action/UpdateSell2.cs
- Lib9c/Action/UpdateSell3.cs
- Lib9c/Action/UpdateSell4.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/Order/FungibleOrder.cs
- Lib9c/Model/Order/NonFungibleOrder.cs
- Lib9c/Model/Order/Order.cs
- Lib9c/Policy/BlockPolicySource.cs
> Hot fix `Sell` and `UpdateSell`

- .Lib9c.Tests/Action/HackAndSlash20Test.cs
- Lib9c/Action/HackAndSlash.cs
- Add handling about invalid `TotalPlayCount` & `ApStoneCount`
> bug fix about HAS20

- Lib9c/StagePolicy.cs
Cherry-picked from https://github.com/planetarium/lib9c/commit/e42ddb9ab6d1dcb1e0d16b770a7ed960475fbc77.
> Ban account in stage policy level

- Lib9c/TableCSV/Skill/SkillSheet.csv
> Update multistrike hitcount

- .Lib9c.Tests/Action/BattleArena7Test.cs
- .Lib9c.Tests/Action/BattleArena8Test.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena3.cs
- Lib9c/Action/BattleArena4.cs
- Lib9c/Action/BattleArena5.cs
- Lib9c/Action/BattleArena6.cs
- Lib9c/Action/BattleArena7.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/Model/Arena/ArenaExceptions.cs
- Hard fork BattleArena from 7 to 8, ArenaHelper
- Delete BattleArena validation(block interval, score difference) in off season
- Edit ticket use
- Update BattleArenaTest
> Edit arena off season

- .Lib9c.Tests/Action/RawState.cs
- .Lib9c.Tests/Action/State.cs
- Lib9c/Action/ActionBase.cs
> ⬆️ Bump libplanet to 0.46.0

- .Lib9c.Tests/Action/BattleArena8Test.cs
- .Lib9c.Tests/Action/EventDungeonBattleV4Test.cs
- .Lib9c.Tests/Action/HackAndSlash20Test.cs
- .Lib9c.Tests/Action/HackAndSlashSweep9Test.cs
- .Lib9c.Tests/Action/JoinArena3Test.cs
- .Lib9c.Tests/Action/MimisbrunnrBattle12Test.cs
- .Lib9c.Tests/Action/Raid4Test.cs
- Lib9c/Model/State/RuneSlotState.cs
> Fix rune slot state

- Lib9c.DevExtensions/TestbedHelper.cs
> Consider `macOS` in `TestbedHelper`

- .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
> No warn `xUnit1026` in test project

- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorAdminPolicy.cs
> clean up BlockPolicySource

- .Lib9c.Tests/Action/BattleGrandFinale1Test.cs
- .Lib9c.Tests/Action/BattleGrandFinale2Test.cs
- .Lib9c.Tests/Action/BattleGrandFinaleTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena7.cs
- Lib9c/Action/BattleGrandFinale.cs
- Lib9c/Action/BattleGrandFinale1.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Arena/ArenaSimulatorV2.cs
- Lib9c/Model/Character/ArenaCharacter.cs
> Fix bleed being applied one turn in arena.

- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
> Fix drr formula in arena

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Policy/BlockPolicySource.Utils.cs
- Lib9c/Policy/BlockPolicySource.cs
- Lib9c/Policy/ValidatorAdminPolicy.cs
- Lib9c/Renderer/ActionRenderer.cs
> 🔀 Add changes made to pow-dynamic-validators

- Lib9c.Miner/Miner.cs
Remove check that exclude action which has no any action.
> Remove check in Miner.cs

- Lib9c.Abstractions/IClaimRaidRewardV1.cs
- Lib9c/Action/BattleArena5.cs
- Lib9c/Action/ClaimRaidReward.cs
I'm sorry for opening pull requests and requesting reviews multiple times. But I believe it can reduce the review burden.
> Implement interfaces missing

- Lib9c.DevExtensions/TestbedHelper.cs
- Lib9c.MessagePack/Action/NCActionEvaluation.cs
- Lib9c.MessagePack/Formatters/AddressFormatter.cs
- Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
- Lib9c/Action/GoldDistribution.cs
This PR adjusts codes in Lib9c.MessagePack to keep compat [MessagePack.Generator][] for IL2CPP env.
[MessagePack.Generator]: https://www.nuget.org/packages/MessagePack.Generator/
> Compat with mpc for IL2CPP

- Lib9c/Action/CreateAvatar.cs
> handle FailedLoadStateException at test create avatar

- Lib9c/Action/ItemEnhancement.cs
> Update pet id on `ItemEnhancement`

- .Lib9c.Tests/Util/CraftUtil.cs
- .Lib9c.Tests/Util/CsvUtil.cs
- .Lib9c.Tests/Util/CurrencyUtil.cs
- .Lib9c.Tests/Util/InitializeUtil.cs
- .Lib9c.Tests/Util/QuestUtil.cs
- Lib9c/Addresses.cs
- CraftUtil
- CsvUtil
- CurrencyUtil
- InitializeUtil
- QuestUtil
> feat: Introduce test utils

- .Lib9c.Tests/Action/Raid4Test.cs
- Lib9c/Action/Raid.cs
- Transfer fee only when fee is positive value.
> Support zero crystal fee on `Raid`.

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/BuyProductTest.cs
- .Lib9c.Tests/Action/ExceptionTest.cs
- Lib9c/Action/BuyProduct.cs
- Lib9c/Action/ProductNotFoundException.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Model/Mail/IMail.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/Mail/ProductBuyerMail.cs
- Lib9c/Model/Mail/ProductSellerMail.cs
- Add BuyProduct(correspond action Buy) action
- Support new product model & backward compatibility for order model
- Divided from #1672 into stages for review convenience.
> Introduce BuyProduct action

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ReRegisterProductTest.cs
- .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/UpdateSell.cs
- re-register product using `CancelProductRegistration.Cancel & RegisterProduct.Register`.
- previous registered order in shop state can move to market using `UpdateSell.Cancel & RegisterProduct.Register`.
> Introduce re-register product

- Lib9c.sln
- Add `Lib9c.Utils` project to solution.
> fix: build errors

- .Lib9c.Tests/Action/BattleArena1Test.cs
- .Lib9c.Tests/Action/BattleArena2Test.cs
- .Lib9c.Tests/Action/BattleArena3Test.cs
- .Lib9c.Tests/Action/BattleArena4Test.cs
- .Lib9c.Tests/Action/BattleArena5Test.cs
- .Lib9c.Tests/Action/BattleArena6Test.cs
- .Lib9c.Tests/Action/BattleArena7Test.cs
- .Lib9c.Tests/Action/BattleArena8Test.cs
- .Lib9c.Tests/Action/BattleArena9Test.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Battle/ArenaScoreHelperTest.cs
- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena1.cs
- Lib9c/Action/BattleArena2.cs
- Lib9c/Action/BattleArena3.cs
- Lib9c/Action/BattleArena4.cs
- Lib9c/Action/BattleArena5.cs
- Lib9c/Action/BattleArena6.cs
- Lib9c/Action/BattleArena7.cs
- Lib9c/Action/BattleArena8.cs
- Lib9c/Action/RankingBattle.cs
- Lib9c/Arena/ArenaHelper.cs
- Lib9c/Battle/ArenaScoreHelper.cs
- Edit arena battle score limits : (100, -100) -> (200, -100)
- Edit winning score data (ArenaScoreHelper.CachedScore)
- Hardfork BattleArena, methods about arena battle
[23년도 1Q 아레나 개선](https://app.asana.com/0/958521740385861/1204010697296681/f)
> Edit arena score data

- Lib9c/Action/TransferAsset.cs
> fix: `IReadOnlySet<T>` to `IReadOnlyList<T>` for Unity

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/BuyProductTest.cs
- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
- .Lib9c.Tests/Action/MarketValidationTest.cs
- .Lib9c.Tests/Action/ReRegisterProductTest.cs
- .Lib9c.Tests/Action/RegisterProductTest.cs
- .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
- .Lib9c.Tests/Action/SellCancellationTest.cs
- Lib9c/Action/AssetInfo.cs
- Lib9c/Action/BuyProduct.cs
- Lib9c/Action/CancelProductRegistration.cs
- Lib9c/Action/FavProductInfo.cs
- Lib9c/Action/IProductInfo.cs
- Lib9c/Action/IRegisterInfo.cs
- Lib9c/Action/ItemProductInfo.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/RegisterInfo.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Model/Market/ItemProduct.cs
- Lib9c/Model/Market/Product.cs
- Lib9c/Model/Market/ProductFactory.cs
- Divide ProductInfo to ItemProductInfo, FavProductInfo by ProductType.
- Add sanity check for market actions.
> refactoring market actions plain values

- .github/workflows/main.yml
> ci: Remove `DevEx` configuration in build-and-test workflow

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/ValidatorAdminPolicy.cs
- Lib9c.Renderers/Renderer/ActionRenderer.cs
Add validator admin policy by merging from `pow-pbft` branch
> Add validator admin policy

- Lib9c/Action/Sell.cs
- Lib9c/Action/UpdateSell.cs
- obsolete sell, update sell action for prevent register legacy shop instead of market
> Prevent register shop item

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/ValidatorAdminPolicy.cs
- Lib9c.Renderers/Renderer/ActionRenderer.cs
Cherry-pick of 63653437d0c1f49d71441d40910c2595fdee07c4.
> Add changes made to pow-dynamic-validators

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
- .Lib9c.Tests/Action/ReRegisterProductTest.cs
- .Lib9c.Tests/Action/RegisterProductTest.cs
- .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
- .Lib9c.Tests/Action/SellCancellationTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Action/CancelProductRegistration.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Model/State/AvatarState.cs
- add ap cost to market actions
> Add ap cost new market action

- .Lib9c.Tests/Helper/PetHelperTest.cs
- .Lib9c.Tests/TableData/Pet/PetCostSheetTest.cs
- .Lib9c.Tests/TableData/Pet/PetSheetTest.cs
- Lib9c/Action/PetEnhancement.cs
- Lib9c/Helper/PetHelper.cs
- Lib9c/TableData/Pet/PetCostSheet.cs
- Lib9c/TableData/Pet/PetSheet.cs
> Bug fix on calculating pet effect

- Lib9c.Policy/Policy/BlockPolicySource.cs
> chore: fix API mismatch

- Lib9c/Action/DelayAction.cs
> introduce: delay action

- .Lib9c.DevExtensions.Tests/Action/Craft/UnlocakCraftActionTest.cs
- .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
- .Lib9c.Tests/Util/InitializeUtil.cs
- Lib9c.DevExtensions/Action/ManipulateState.cs
> [DevEx] feat: Apply balance list to ManipulateState action

- .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
- Lib9c.DevExtensions/Action/ManipulateState.cs
> [DevEx] fix: `PlaneValue` of `ManipulateState`

- .Lib9c.Tests/Action/BuyProductTest.cs
- .Lib9c.Tests/Action/CancelProductRegistrationTest.cs
- .Lib9c.Tests/Action/ReRegisterProductTest.cs
- .Lib9c.Tests/Action/RegisterProductTest.cs
- Lib9c/Action/BuyProduct.cs
- Lib9c/Action/CancelProductRegistration.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/RegisterProduct.cs
set market actions capcaity for execution time.
> Set market actions capacity

- .Lib9c.Tests/Action/CombinationEquipment15Test.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- Lib9c/Action/CombinationEquipment15.cs
- Lib9c/Action/ItemEnhancement.cs
> Version up `CombinationEquipment`

- Lib9c/Action/HackAndSlash.cs
Especially added special log on `AvatarState` serialization because it seems to be the biggest one.
> Separate `SetState` duration measurement with serialization duration measurement

- Lib9c/Action/AccountStateViewExtensions.cs
- Use parallel loops instead of states.GetStates
> Parallel loop instead of getStates

- .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
- .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
- .Lib9c.DevExtensions.Tests/Lib9c.DevExtensions.Tests.csproj
- Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
- Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
- Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
- Lib9c.DevExtensions/RandomImpl.cs
> [DevEx] Extend `CreateOrReplaceAvatar`

- .Lib9c.Tests/Action/DailyReward6Test.cs
- .Lib9c.Tests/Action/DailyRewardTest.cs
- Lib9c/Action/DailyReward.cs
- Lib9c/Action/DailyReward6.cs
reduce execution `DailyReward` execution time by reduce `GetState` call. it only update avatarAddress
- test case tx https://9cscan.com/tx/aef88da04e2a77441a1f5a2ad021d1fcb8f219e04cb19af2247f5672fb58a7ca
AS-IS
```
[17:21:58 DBG] [52944F82dFfD11ad20108D9695d5F42cF1b766B3, 95f437DfE90b80CF24d3fF3E36CDF69681Ee9BC7]DailyReward exec started
[17:21:58 DBG] Took 0 ms to fetch values for GetStates() via state store (total count: 1, cache count: 0)
[17:21:58 DBG] Took 0 ms to fetch values for GetStates() via state store (total count: 1, cache count: 0)
[17:21:58 DBG] Took 4 ms to fetch values for GetStates() via state store (total count: 1, cache count: 0)
[17:21:58 DBG] Took 8 ms to fetch values for GetStates() via state store (total count: 1, cache count: 0)
[17:21:58 DBG] Took 9 ms to fetch …
```
> Hard-fork daily reward

- Lib9c/Model/Item/Consumable.cs
- Lib9c/Model/Item/Costume.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/Item/ItemUsable.cs
- Lib9c/Model/Item/Material.cs
- Lib9c/Model/Item/ShopItem.cs
- Lib9c/Model/Mail/AttachmentMail.cs
- Lib9c/Model/Mail/CancelOrderMail.cs
- Lib9c/Model/Mail/GrindingMail.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/Mail/MaterialCraftMail.cs
- Lib9c/Model/Mail/OrderBuyerMail.cs
- Lib9c/Model/Mail/OrderExpirationMail.cs
- Lib9c/Model/Mail/OrderSellerMail.cs
- Lib9c/Model/Mail/ProductBuyerMail.cs
- Lib9c/Model/Mail/ProductCancelMail.cs
- Lib9c/Model/Mail/ProductSellerMail.cs
In general, chaining `Add()`s is faster than passing a `Dictionary<IKey, IValue>`. 🙄
> ♻️ Refactor optimize mail and item encoding

- Lib9c.DevExtensions/Action/ManipulateState.cs
- Separate `override IAccountStateDelta Execute(IActionContext)`.
> [DevEx]Refactor `ManipulateState`

- .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
- .Lib9c.DevExtensions.Tests/Action/Factory/CreateOrReplaceAvatarFactoryTest.cs
- Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
- Lib9c.DevExtensions/Action/Factory/CreateOrReplaceAvatarFactory.cs
- Lib9c.DevExtensions/Action/Interface/ICreateOrReplaceAvatar.cs
- Lib9c.sln.DotSettings
- Lib9c/Addresses.cs
> [DevEx]Extend `CreateOrReplaceAvatar`

- Lib9c.Policy/Policy/BlockPolicySource.cs
> fix: for unity editor

- .Lib9c.Tests/Action/State.cs
- .Lib9c.Tests/Action/ValidatorSetOperateTest.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/MinBlockProtocolVersionPolicy.cs
- Lib9c/Action/ValidatorSetOperate.cs
- Lib9c/Action/ValidatorSetOperatorType.cs
- Lib9c/Action/ValidatorSetOperatorTypeExtension.cs
> 🔀 Merge rc-v100381-1 to main

- .Lib9c.Tests/Action/Raid1Test.cs
- .Lib9c.Tests/Action/Raid2Test.cs
- .Lib9c.Tests/Action/Raid3Test.cs
- .Lib9c.Tests/Action/Raid4Test.cs
- .Lib9c.Tests/Action/Raid5Test.cs
- .Lib9c.Tests/Action/WorldBossHelperTest.cs
- Lib9c/Action/Raid.cs
- Lib9c/Action/Raid1.cs
- Lib9c/Action/Raid2.cs
- Lib9c/Action/Raid3.cs
- Lib9c/Action/Raid4.cs
- Lib9c/ActionObsoleteConfig.cs
- Lib9c/Helper/WorldBossHelper.cs
- Lib9c/Model/State/GameConfigState.cs
- Lib9c/TableCSV/GameConfigSheet.csv
- Hardfork CanRefillTicket (in WorldBossHelper) 1->2, Raid 4->5
- Add daily worldboss interval, worldboss required interval to gameconfigsheet
> Add daily worldboss interval to gameconfigsheet

- Lib9c/Model/State/StakeState.cs
> Stake reward update target is fixed

- .Lib9c.Tests/TableData/WorldBossRankingRewardSheetTest.cs
- Lib9c/TableData/WorldBossRankingRewardSheet.cs
- fix world boss reward find row with boss id
> Fix invalid world boss reward

- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Model/State/StakeState.cs
This values should be used in NineChronicles.Headless GQL response.
To bump lib9c, this PR goes to development branch. I'll make another PR to RC branch.
> Make old stake reward data to public

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
- .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
- .Lib9c.Tools/SubCommand/Action.cs
- .Lib9c.Tools/SubCommand/State.cs
- Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
- Lib9c.MessagePack/Formatters/NCActionFormatter.cs
> Bump Libplanet to main

- .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/BringEinheriTest.cs
- .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
- .Lib9c.Tests/Action/TakeSidesTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/BringEinheri.cs
- Lib9c/Action/ReleaseEinheri.cs
- Lib9c/Action/TakeSides.cs
- Lib9c/Currencies.cs
Introduce mead contract skeleton actions
> Introduce mead contract

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .gitmodules
- Lib9c.DevExtensions/Utils.cs
This PR should be revised after Libplanet release containing planetarium/libplanet#3149
> Bump libplanet (for planetarium/libplanet#3149)

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
- .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Action.cs
- .Lib9c.Tools/SubCommand/Market.cs
- .Lib9c.Tools/SubCommand/State.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.MessagePack/Formatters/NCActionFormatter.cs
- Lib9c.Policy/Policy/BlockPolicy.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Policy/StagePolicy.cs
- Lib9c.Proposer/CustomActionsDeserializableValidator.cs
- Lib9c.Proposer/Proposer.cs
- Lib9c.Renderers/Renderers/ActionRenderer.cs
- Lib9c.Renderers/Renderers/BlockRenderer.cs
- Lib9c.Utils/BlockHelper.cs
- Lib9c/Model/State/StateExtensions.cs
> bump libplanet to 1.1.1 and introduce fee collect by gas usage.

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Action/PrepareRewardAssetsTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
- .Lib9c.Tests/Action/Snapshot/TransferAsset0SnapshotTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Action.cs
- .Lib9c.Tools/SubCommand/Market.cs
- .Lib9c.Tools/SubCommand/State.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c.DevExtensions/Action/Craft/UnlockCraftAction.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.MessagePack/Formatters/NCActionFormatter.cs
- Lib9c.Policy/Policy/BlockPolicy.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Policy/StagePolicy.cs
- Lib9c.Proposer/CustomActionsDeserializableValidator.cs
- Lib9c.Proposer/Proposer.cs
- Lib9c.Renderers/Renderers/ActionRenderer.cs
- Lib9c.Renderers/Renderers/BlockRenderer.cs
- Lib9c.Utils/BlockHelper.cs
- Lib9c/Action/PrepareRewardAssets.cs
- Lib9c/Model/State/StateExtensions.cs
SSIA
note: 361d6bad1674cb1d9472220dd23e969e65ed1058
> Merge into `feature/prepare-fee` from `test/mead`

- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/State.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Proposer/CustomActionsDeserializableValidator.cs
- Lib9c/Action/ActionBaseExtensions.cs
> ⬆️ Bump libplanet

- Lib9c.Policy/Policy/BlockPolicySource.cs
> 🔧 Fixed activation check

- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/State.cs
- .Lib9c.Tools/SubCommand/Tx.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Proposer/CustomActionsDeserializableValidator.cs
- Lib9c.Renderers/Renderers/ActionRenderer.cs
- Lib9c.Renderers/Renderers/BlockRenderer.cs
- Lib9c.Utils/BlockHelper.cs
> ⬆️ Bump libplanet for mead

- Lib9c/TableCSV/Item/MaterialItemSheet.csv
Staking Reward Item Date Add
- golden meat
- golden dust
> Update Staking Item Add

- Lib9c/Action/CombinationEquipment.cs
> Prevent state mismatch occured with random

- .Lib9c.Tests/Action/BattleArena10Test.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena8.cs
- Lib9c/Action/BattleArena9.cs
- Lib9c/Action/BattleGrandFinale.cs
- Lib9c/Action/BattleGrandFinale1.cs
- Lib9c/Action/Raid4.cs
- Lib9c/ActionObsoleteConfig.cs
- HardFork BattleArena 9->10
- Delete Extra Field
- Add Obsolete Actions
> Delete Extra Field in BattleArena

- .Lib9c.DevExtensions.Tests/Action/CreateOrReplaceAvatarTest.cs
- Lib9c.DevExtensions/Action/CreateOrReplaceAvatar.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Stat/StatsMap.cs
> Fix state mismatch on Equipment Enhancement

- .Lib9c.Tests/Action/AccountStateDeltaExtensionsTest.cs
- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/ApprovePledgeTest.cs
- .Lib9c.Tests/Action/RequestPledgeTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
- .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
- .Lib9c.Tests/Action/TransferAssetTest.cs
- .Lib9c.Tests/Action/TransferAssetsTest.cs
- Lib9c/Action/AccountStateDeltaExtensions.cs
- Lib9c/Action/AddressExtension.cs
- Lib9c/Action/ApprovePledge.cs
- Lib9c/Action/EndPledge.cs
- Lib9c/Action/RequestPledge.cs
- Lib9c/Action/RewardGold.cs
- BringEinehri -> RequestPledge
- TakeSides -> ApprovePledge
- ReleaseEinheri -> EndPledge
- Einheri -> Agent
- Valkyrie -> Patron
> Rename mead actions

- .github/bin/constants.sh
- .github/bin/dist-github-release.sh
- .github/bin/dist-pack.sh
- .github/bin/github-release.sh
- .github/workflows/release.yaml
> Release tagged lib9c to github

- .gitignore
> [test] fix github ci

- .Lib9c.Tests/Action/BattleArena12Test.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena11.cs
- Lib9c/Action/BattleGrandFinale.cs
- Lib9c/Arena/ArenaSimulatorV4.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Stat/CharacterStats.cs
HP was not doubled when a player is equipping runes, and this PR fixes it.
`BattleGrandFinale` is not hard-forked because it's not actually executed at all.
> Bug fix on doubling HP in arena.

- .Lib9c.Tests/Action/BuyProduct0Test.cs
- .Lib9c.Tests/Action/ReRegisterProduct0Test.cs
- .Lib9c.Tests/Action/RegisterProduct0Test.cs
- .Lib9c.Tests/Action/RegisterProductTest.cs
- .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
- Lib9c/Action/BuyProduct.cs
- Lib9c/Action/BuyProduct0.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/ReRegisterProduct0.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Action/RegisterProduct0.cs
- Check requiredBlockIndex in Register for blocking register unavailable equipments
- Update requiredBlockIndex in BuyProduct from invalid registered equipments
- Cancel don't update requiredBlockindex to prevent cheating.
> Fix market actions

- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Utils/BlockHelper.cs
- Lib9c/MeadConfig.cs
- stage policy check patron balance instead of block index
> stage tx check patron balance instead of block index

- Lib9c/Action/TransferAsset.cs
- Lib9c/Action/TransferAssets.cs
set gas fee 4 for prevent transfer mead
> Update TransferAsset gas fee

- .Lib9c.Tests/Action/ExceptionTest.cs
- .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
- .Lib9c.Tests/CurrenciesTest.cs
- .Lib9c.Tests/Model/Garages/FungibleItemGarageTest.cs
- .Lib9c.Tests/TableData/Garages/LoadIntoMyGaragesCostSheetTest.cs
- .Lib9c.Tests/TableSheets.cs
- Lib9c.Abstractions/ILoadIntoMyGarages.cs
- Lib9c.sln.DotSettings
- Lib9c/Action/AccountStateViewExtensions.cs
- Lib9c/Action/Garages/GarageUtils.cs
- Lib9c/Action/Garages/LoadIntoMyGarages.cs
- Lib9c/Action/PetEnhancement.cs
- Lib9c/Addresses.cs
- Lib9c/Currencies.cs
- Lib9c/Exceptions/InvalidActionFieldException.cs
- Lib9c/Exceptions/ItemNotFoundException.cs
- Lib9c/Exceptions/NotEnoughItemException.cs
- Lib9c/Exceptions/StateNullException.cs
- Lib9c/Model/Garages/FungibleItemGarage.cs
- Lib9c/Model/Garages/IFungibleItemGarage.cs
- Lib9c/Model/Garages/IGarage.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/Item/ItemBase.cs
- Lib9c/Model/Item/Material.cs
- Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
- Lib9c/TableData/Garages/LoadIntoMyGaragesCostSheet.cs
- Introduce `LoadIntoMyGaragesCostSheet`.
- Introduce `FungibleItemGarage`.
- Introduce `LoadIntoMyGarages` action.
> Introduce `LoadIntoMyGarages` action

- .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
- Lib9c.Abstractions/IDeliverToOthersGarages.cs
- Lib9c/Action/Garages/DeliverToOthersGarages.cs
> Introduce `DeliverToOthersGarages` action

- .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
- Lib9c.Abstractions/IUnloadFromMyGarages.cs
- Lib9c/Action/Garages/UnloadFromMyGarages.cs
This pull request base on #1961.
> Introduce `UnloadFromMyGarages` action

- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
> Apply "claim_stake_reward4" to `ClaimStakeRewardFactory`

- .github/workflows/main.yml
> update submodule-updater to bump `release/*` branches

- .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
- .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
- .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
- .Lib9c.Tests/Model/Mail/UnloadFromMyGaragesRecipientMailTest.cs
- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c.Abstractions/IDeliverToOthersGaragesV1.cs
- Lib9c.Abstractions/ILoadIntoMyGaragesV1.cs
- Lib9c.Abstractions/IUnloadFromMyGaragesV1.cs
- Lib9c/Action/Garages/DeliverToOthersGarages.cs
- Lib9c/Action/Garages/GarageUtils.cs
- Lib9c/Action/Garages/LoadIntoMyGarages.cs
- Lib9c/Action/Garages/UnloadFromMyGarages.cs
- Lib9c/Action/HackAndSlash3.cs
- Lib9c/Action/MimisbrunnrBattle0.cs
- Lib9c/Model/Mail/IMail.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/Model/Mail/UnloadFromMyGaragesRecipientMail.cs
- Lib9c/Model/State/AvatarState.cs
- Introduce `UnloadFromMyGaragesRecipientMail`.
- Send `UnloadFromMyGaragesRecipientMail` to recipient avatar's mail box in `UnloadFromMyGarages` action.
- Rename garage action interfaces.
- Use gas in garage actions.
- Rename `Mail.CleanUp2()` to `CleanUpV1()`.
> Introduce `UnloadFromMyGaragesRecipientMail`

- Lib9c.Renderers/Renderers/ActionRenderer.cs
- Lib9c.Renderers/Renderers/BlockRenderer.cs
Libplanet no longer supports reorg/unrender. 😗
> 🧹 Removed unsupported render methods.

- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
- .Lib9c.Tests/Action/Snapshot/ActionUtils.cs
- .Lib9c.Tools/SubCommand/Action.cs
- Lib9c/Action/ActionObsoleteAttribute.cs
🧹 Having `AttributeUsage` with `AllowMultiple` set to `false`, things should be fine? 😗
> 🧹 Rewrite attribute checking logic

- .Lib9c.Tests/Action/CreateAvatar8Test.cs
- .Lib9c.Tests/Action/CreateAvatarTest.cs
- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/CreateAvatar8.cs
Increase mint crystal 50 to 600000
> Increase mint crystal

- .Lib9c.Tests/Action/AddActivatedAccount0Test.cs
- .Lib9c.Tests/Action/AddActivatedAccountTest.cs
- .Lib9c.Tests/Action/MockStateDelta.cs
- .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferCrystal.summary.verified.txt
- .Lib9c.Tests/Action/Snapshot/transfer_asset.TransferWithMemo.summary.verified.txt
Many safety features have been turned off for test compatibility reasons. See the description for `MockStateDelta` for more detail.
> ♻️ Modernize `MockStateDelta`

- .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
- .Lib9c.Tests/Action/Garages/UnloadFromMyGaragesTest.cs
- .Lib9c.Tests/Model/Garages/FungibleItemGarageTest.cs
- Lib9c/Model/Garages/FungibleItemGarage.cs
0 is not null.
To check exact condition of garage, remain FungibleItemGarage and just set count to 0.
> Do not wipe out empty garage to null

- Lib9c/Action/CreateAvatar8.cs
> fix: apply `Libplanet` changes inside of `UNITY_EDITOR` constants

- .github/workflows/main.yml
> [CI] Apply auto find options

- .Lib9c.Tests/Action/ClaimStakeReward4Test.cs
- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- .Lib9c.Tests/Model/State/StakeStateTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/ClaimStakeReward4.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
- Lib9c/ActionObsoleteConfig.cs
- Lib9c/Model/State/StakeState.cs
- Fixes a bug in the logic that calculates rewards.
- Obsolete `claim_stake_reward4` at 7,205,000 block index.
- Introduce `claim_stake_reward5` as `ClaimStakeReward`
> release: fix bug on "claim_stake_reward4"

- .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
- .Lib9c.Tests/Action/CombinationEquipment10Test.cs
- .Lib9c.Tests/Action/CombinationEquipment11Test.cs
- .Lib9c.Tests/Action/CombinationEquipment12Test.cs
- .Lib9c.Tests/Action/CombinationEquipment13Test.cs
- .Lib9c.Tests/Action/CombinationEquipment14Test.cs
- .Lib9c.Tests/Action/CombinationEquipment15Test.cs
- .Lib9c.Tests/Action/CombinationEquipment8Test.cs
- .Lib9c.Tests/Action/CombinationEquipment9Test.cs
- .Lib9c.Tests/Action/CombinationEquipmentTest.cs
- .Lib9c.Tests/Action/EventDungeonBattleV1Test.cs
- .Lib9c.Tests/Action/EventDungeonBattleV2Test.cs
- .Lib9c.Tests/Action/EventDungeonBattleV3Test.cs
- .Lib9c.Tests/Action/EventDungeonBattleV4Test.cs
- .Lib9c.Tests/Action/EventDungeonBattleV5Test.cs
- .Lib9c.Tests/Action/GrindingTest.cs
- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/Action/JoinArena1Test.cs
- .Lib9c.Tests/Action/JoinArena2Test.cs
- .Lib9c.Tests/Action/JoinArena3Test.cs
- .Lib9c.Tests/Action/MockStateDelta.cs
- .Lib9c.Tests/Action/PetEnhancement0Test.cs
- .Lib9c.Tests/Action/RuneEnhancement0Test.cs
- .Lib9c.Tests/Action/RuneEnhancementTest.cs
- .Lib9c.Tests/Action/UnlockWorld1Test.cs
- .Lib9c.Tests/Action/UnlockWorldTest.cs
- .Lib9c.Tests/Util/InitializeUtil.cs
I've made various attempt to use `MockState` to no avail. 😥
Might as well merge this first.
> ♻️ Use valid `MockStateDelta`

- Lib9c.MessagePack/AccountStateDelta.cs
> 🔧 Implement valid `Delta` for `Lib9c.Formatters.AccountStatedelta`

- Lib9c/Action/HackAndSlash.cs
> Add unequip & slot state elapsed

- .Lib9c.Tests/Action/CreateAvatarTest.cs
- Lib9c/Action/CreateAvatar.cs
> Fix invalid crystal mint 600000 -> 200000

- Lib9c/Model/Mail/UnloadFromMyGaragesRecipientMail.cs
- SSIA
- It does not affect the state of blockchain.
> fix: mail type of `UnloadFromMyGaragesRecipientMail` to `Auction`

- Lib9c/Action/AccountStateExtensions.cs
- Lib9c/Action/HackAndSlash.cs
> Log HAS Playcount, Remove Debug log

- Lib9c/Action/HackAndSlash.cs
> Add blockindex to has total log

- .Lib9c.Benchmarks/Program.cs
> ⬆️ Bump libplanet to 3.1.0

- .github/workflows/publish.yml
> ci(gh-actions): run publish workflow in development branch

- .github/workflows/publish.yml
> ci(gh-actions): specify AWS region

- .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
- .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
> fix(action-evaluator-common-components): link action evaluation states

- Lib9c/Lib9c.csproj
It is related with NuGet deployment process.
> Prepare 0.5.0

- Lib9c/Battle/CPHelper.cs
- Lib9c/Model/Buff/ActionBuff.cs
- Lib9c/Model/Buff/Bleed.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Stat/Stats.cs
- Use for loop instead of Linq.Sum
- Avoid CharacterBase.Clone on Bleed
> Optimize HackAndSlash.Execute #3

- .Lib9c.StateService/Lib9c.StateService.csproj
- .Lib9c.StateService/Program.cs
> feat: add `Serilog` logger in `StateService`

- Lib9c.Policy/NCStagePolicy.cs
Add validator addresses before preparing a new hotfix.
> add new addresses

- .Lib9c.Tests/Action/ItemEnhancement11Test.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Model/Item/EquipmentTest.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/ItemEnhancement11.cs
- Lib9c/Model/Item/Equipment.cs
- Refactor Equipment model: rename from `exp` to `Exp`
- Obsolete `ItemEnhancement11` when `EquipmentCostSheetV3` found.
- Fix tests
> Obsolete old ItemEnhancement action

- Lib9c/Action/ItemEnhancement.cs
> Update all avatar related states

- .Lib9c.Tests/Action/BattleArena12Test.cs
- .Lib9c.Tests/Action/BattleArena13Test.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/BattleArena12.cs
- Lib9c/ActionObsoleteConfig.cs
- oboslete BattleArena12 next season
- fix invalid avatar address when equip rune
> Fix arena rune equip

- Lib9c/TableCSV/Cost/EnhancementCostSheetV3.csv.meta
> add EnhancementCostSheetV3.csv.meta file

- .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/ClaimStakeReward7.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
- Lib9c/ActionObsoleteConfig.cs
- deprecate "claim_stake_reward7"
- introduce "claim_stake_reward8"
- make `Currency` with `CurrencyTicker` first.
- make `Uncapped Currency` with `CurrencyTicker` and `CurrencyDecimalPlaces` last.
> fix: currency type of crystal in "claim_stake_reward7"

- .github/bin/dist-pack.sh
- .github/workflows/publish.yml
- .github/workflows/release.yaml
- https://github.com/planetarium/lib9c/commit/90f8dc45a9fc5df09c341a16169cc1e0a6b8c977 fixes https://github.com/planetarium/lib9c/actions/runs/5996957418/job/16262426753#step:4:16.
- https://github.com/planetarium/lib9c/commit/4b526fc3278a37e694384f23e91d2e9f38e77f6c fixes https://github.com/planetarium/lib9c/actions/runs/5958008686/job/16161621054#step:5:42.
> Fix GitHub ci

- .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/ClaimStakeReward7.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
- Lib9c/ActionObsoleteConfig.cs
- Lib9c/Currencies.cs
> merge release/0.5.3 into main

- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Model/Item/EquipmentTest.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/TableCSV/Item/EquipmentItemSheet.csv
- Handle level 0 to 0 case
- Equipment model always returns Exp field when serialize
> Handle enhancement of level 0 to 0 case

- .github/workflows/main.yml
(cherry picked from commit 258d2f3bf3d9d5dc0bb2e6f44c39d8b0df6e0212)
SSIA
> fix trigger conditions of "main" workflow

- .Lib9c.Tests/Model/Item/EquipmentTest.cs
- Lib9c/Model/Item/Equipment.cs
> Serialize Exp field only when it has positive value

- Lib9c/Action/AuraSummon.cs
- Lib9c/TableCSV/Summon/AuraSummonSheet.csv
- Change result equipment id to recipe id in AuraSummonSheet
- Optimize
- Moving out from loop some codes
> Update recipe ID in aura summon sheet

- .Lib9c.Tests/Action/AuraSummonTest.cs
- Lib9c/Action/AuraSummon.cs
> Add AuraSummon constructor with field data

- Lib9c/Model/Stake/StakeStateUtils.cs
> chore: add comments to StakeStateUtils

- .Lib9c.Tests/Model/Stake/ContractTest.cs
- .Lib9c.Tests/Model/Stake/StakeStateV2Test.cs
- Lib9c/Model/Stake/Contract.cs
> chore: work a few unit tests

- .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
- Lib9c/GameConfig.cs
- Lib9c/Model/State/AvatarState.cs
> Fix aura duplicate equip

- .Lib9c.Tests/Action/MockState.cs
- .Lib9c.Tests/Action/MockStateDelta.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/AccountStateDelta.cs
- .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockState.cs
- Lib9c.MessagePack/AccountStateDelta.cs
- Lib9c/Action/ActionBaseExtensions.cs
> ⬆️ Bump libplanet to 3.3.1

- .Lib9c.Tests/Action/PatchTableSheetTest.cs
- Lib9c/Action/PatchTableSheet.cs
> revert changes of PatchTableSheet action

- Lib9c/Lib9c.csproj
> Update Lib9c version to 1.1.0

- Lib9c/GameConfig.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/TableData/UnlockHelper.cs
SSIA
https://app.asana.com/0/1133453747809944/1205473403807575/f
> add aura slot and equip level limit config

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Utils/BlockHelper.cs
> fix: remove `IRenderer`s from `BlockPolicySource`

- .Lib9c.Tests/Action/TransferAssetTest.cs
- .Lib9c.Tests/Action/TransferAssets2Test.cs
- .Lib9c.Tests/Action/TransferAssetsTest.cs
- Lib9c/Action/TransferAsset.cs
- Lib9c/Action/TransferAssets.cs
- Lib9c/Action/TransferAssets2.cs
- Lib9c/ActionObsoleteConfig.cs
> obosolete transfer_assets2

- .Lib9c.Tests/Model/Stake/StakeStateUtilsTest.cs
- Lib9c/Model/Stake/StakeStateUtils.cs
> refactor: make `StakeStateUtils` more general

- Lib9c/Action/ClaimItems.cs
Since `IValue` doesn't inherit `IComparable` interface, it cannot be used as a key to sort.
And I don't understand why they should be sorted 🤔.
> Do not sort pairs

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.StateService.Shared/RemoteEvaluationRequest.cs
- .Lib9c.StateService/Controllers/RemoteEvaluationController.cs
- .Lib9c.StateService/Lib9c.StateService.csproj
- .Lib9c.StateService/Program.cs
- .Lib9c.Tests/Action/ClaimItemsTest.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
- .Libplanet.Extensions.RemoteActionEvaluator/RemoteActionEvaluator.cs
> 🚀  bump: libplanet 3.6.0

- Lib9c/Action/CreateAvatar.cs
- Lib9c/Action/CreateAvatar0.cs
- Lib9c/Action/CreateAvatar8.cs
> refactor: use `GetRandom` instead of `Random`

- Lib9c/TableCSV/CreateAvatarFavSheet.csv.meta
- Lib9c/TableCSV/CreateAvatarItemSheet.csv.meta
> chore: add meta file for CreateAvatar11

- Lib9c/Action/Buy5.cs
- Lib9c/Action/Buy6.cs
- Lib9c/Action/Buy7.cs
- Lib9c/Action/BuyMultiple.cs
- Lib9c/Action/ClaimMonsterCollectionReward0.cs
- Lib9c/Action/RankingBattle11.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/ReRegisterProduct0.cs
Fixes possible bugs introduced in #2165
> 🐛 Fix Random

- Lib9c/Action/CreateAvatar9.cs
> fix: random usage

- Lib9c/Action/CreateAvatar0.cs
> fix: random usage for Unity

- Lib9c/Action/CreateAvatar0.cs
> fix: compile error about CreateAvatar0.CreateAvatarState on unity editor

- .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
- Lib9c/Action/Garages/UnloadFromGarages.cs
> PDX-20: Implement execute method of UnloadFromGarages

- .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
- Lib9c/Action/Garages/UnloadFromGarages.cs
Open PR to test refactoring code in PDX-39. Test code for failing case will added on following PR.
> PDX-21: Add test case for testing success case

- .Lib9c.Tests/Action/Garages/UnloadFromGaragesTest.cs
- Lib9c/Action/Garages/UnloadFromGarages.cs
> PDX-38: Add Mailing feature to build unload from garage action

- .Lib9c.Tests/Action/Garages/BulkUnloadFromGaragesTest.cs
- Lib9c.Abstractions/IBulkUnloadFromGaragesV1.cs
- Lib9c/Action/Garages/BulkUnloadFromGarages.cs
> Rename UnloadFromGarages to BulkUnloadFromGarages

- .Lib9c.Tests/Action/BurnAssetTest.cs
- .Lib9c.Tests/Action/MintAssetsTest.cs
- Lib9c/Action/BurnAsset.cs
- Lib9c/Action/MintAssets.cs
---
- https://app.asana.com/0/0/1205790778399752
> Introduce MintAssets & BurnAssets

- Lib9c.Utils/BlockHelper.cs
This PR introduces new `goldCurrency` argument to configure currency details (i.e., ticker, minters).
> Add goldCurrency argument to BlockHelper.ProposeBlock()

- Lib9c/Action/CancelProductRegistration.cs
- Lib9c/Action/CancelProductRegistration0.cs
- Lib9c/Action/ReRegisterProduct.cs
- Lib9c/Action/ReRegisterProduct0.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Action/RegisterProduct0.cs
- Lib9c/Action/RegisterProduct2.cs
Improve market actions execution time
> Improve market action exectuion time

- Lib9c/Action/MintAssets.cs
This PR fixes errors related C# record on Unity. also, it adds missing gas config for `MintAssets`.
> Replace record with struct

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- Lib9c.Policy/AccessControlService/IAccessControlService.cs
- Lib9c.Policy/NCStagePolicy.cs
Revert https://github.com/planetarium/lib9c/pull/2210 and use it in the next release.
> Revert nc stage policy

- .Lib9c.Tests/Model/State/LazyStateTest.cs
- Lib9c/Action/ValidatorSetOperate.cs
- Lib9c/Model/Coupons/Coupon.cs
In preparation for future [Bencodex](https://github.com/planetarium/bencodex.net) update. (https://github.com/planetarium/bencodex.net/pull/122)
> 🧹 Remove GetValue<T>() usage

- .Lib9c.Miner.Tests/CustomActionsDeserializableValidatorTest.cs
- Lib9c.MessagePack/AccountStateDelta.cs
- Lib9c/CurrencyExtensions.cs
> 🧹 Use bencodability of `Address`

- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/StagePolicyTest.cs
- Lib9c.Policy/AccessControlService/IAccessControlService.cs
- Lib9c.Policy/NCStagePolicy.cs
SSIA
Ref: https://github.com/planetarium/lib9c/pull/2210
> Revert 2210 before v200100 daily build 

- .Lib9c.Tests/Action/ClaimItemsTest.cs
- .Lib9c.Tests/CurrenciesTest.cs
- Lib9c/Action/ClaimItems.cs
- Lib9c/Currencies.cs
- Lib9c/Model/Mail/ClaimItemsMail.cs
- Lib9c/Model/Mail/IMail.cs
- Lib9c/Model/Mail/Mail.cs
- Lib9c/SerializeKeys.cs
- ClaimItems support wrapped fav mint & burn
- Add ClaimItems.memo field 
- Add ClaimItems mail type
---
- https://app.asana.com/0/0/1205936060181170
> Support wrapped fav burn & mint

- Lib9c.Policy/Policy/BlockPolicySource.cs
200tx starting from `v200110`.
> increase MaxTransactionPerBlock to 200

- .Lib9c.Tests/Action/IssueTokensFromGarageTest.cs
- .Lib9c.Tests/Action/MintAssetsTest.cs
- Lib9c/Action/IssueTokensFromGarage.cs
- Lib9c/Action/MintAssets.cs
- Lib9c/Model/FungibleItemValue.cs
This PR introduces a new `IssueTokenFromGarage` action, to convert from items in the garage to the tokens (can be used in `ClaimItems`).
> Introduce IssueTokenFromGarage 

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/Action/MintAssetsTest.cs
- Lib9c.Utils/BlockHelper.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Action/InvalidMinterException.cs
- Lib9c/Action/MintAssets.cs
- Lib9c/Addresses.cs
This PR adds a special state for `MintAsset` allowance to `0000000000000000000000000000000000000019`.
> AssetMinters to genesis & `MintAssets`

- Lib9c/Action/BattleArena.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Model/Buff/BuffFactory.cs
- Lib9c/Model/Character/ArenaCharacter.cs
ref: https://github.com/planetarium/lib9c/pull/2240, https://github.com/planetarium/lib9c/pull/2229
---
- https://app.asana.com/0/0/1205973997679260
> Add `BuffFactory.GetBuffsForArena()`

- .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
> Add test case for aura buff has custom field

- .Lib9c.Tests/Policy/BlockPolicySourceTest.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c/Action/ActionObsoleteAttribute.cs
- Lib9c/Action/ActionObsoleteAttributeExtension.cs
- Lib9c/Planet.cs
- Lib9c/PlanetExtension.cs
---
- https://app.asana.com/0/0/1205745461458878
> Introduce `Planet` and separate the action obsoletions by them

- .Lib9c.Tests/Action/Snapshot/transfer_asset.PlainValue.verified.txt
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionEvaluationMarshaller.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/TransactionMarshaller.cs
- Lib9c.MessagePack/AccountStateDelta.cs
- Lib9c/Action/ActivateAccount.cs
- Lib9c/Action/ActivateAccount0.cs
- Lib9c/Action/Coupons/RedeemCoupon.cs
- Lib9c/Action/Coupons/TransferCoupons.cs
- Lib9c/Action/CreatePendingActivations.cs
- Lib9c/Model/Coupons/Coupon.cs
- Lib9c/Model/State/PendingActivationState.cs
- Lib9c/Model/State/RedeemCodeState.cs
- Lib9c/Model/State/StateExtensions.cs
- Lib9c/TableData/RedeemCodeListSheet.cs
> ⬆️ Bump libplanet to 3.7.0

- Lib9c/TableCSV/Item/EquipmentItemSheet.csv
Update Equipment Item Exp Value Change
- EquipmentItemSheet
---
- https://app.asana.com/0/0/1205987394500387
> Update Equipment Item EXP Value Change

- .Lib9c.Plugin.Shared/IPluginKeyValueStore.cs
- .Libplanet.Extensions.PluginActionEvaluator/PluginRocksDBKeyValueStore.cs
> introduce: `IPluginKeyValueStore`

- .github/workflows/lib9c_plugin_build_and_push_s3.yaml
> 🔀  ci: for plugin upload

- .Lib9c.Plugin.Shared/IPluginActionEvaluator.cs
- .Lib9c.Plugin.Shared/IPluginKeyValueStore.cs
- .Lib9c.Plugin.Shared/Lib9c.Plugin.Shared.csproj
- .Lib9c.Plugin/Lib9c.Plugin.csproj
- .Lib9c.Plugin/PluginActionEvaluator.cs
- .Lib9c.Plugin/WrappedKeyValueStore.cs
- .github/workflows/lib9c_plugin_build_and_push_s3.yaml
- Lib9c.sln
> 🔀 merge release/1.5.1 into main

- .Lib9c.Tests/AccountExtensions.cs
> 🔧  fix: add docs for `AccountExtensions.cs`

- Lib9c/Model/Buff/Vampiric.cs
> change skillInfo.target to cloned character at Vampiric

- Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
> fix: remove max transactions bytes policy range

- .Lib9c.Tests/Model/PlayerTest.cs
- Lib9c/Model/Buff/Vampiric.cs
> fix calculating logic of Vampiric, for avoid int overflow

- .Lib9c.Tests/Action/ClaimMonsterCollectionReward0Test.cs
- .Lib9c.Tests/Action/ClaimMonsterCollectionReward2Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward1Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward2Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward3Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward4Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward5Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward6Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward7Test.cs
- .Lib9c.Tests/Action/ClaimStakeReward8Test.cs
- .Lib9c.Tests/Action/Factory/ClaimStakeRewardFactoryTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward2ScenarioTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeReward3ScenarioTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimStakeRewardScenarioTest.cs
- .Lib9c.Tests/Lib9c.Tests.csproj
- Lib9c/Action/ClaimMonsterCollectionReward0.cs
- Lib9c/Action/ClaimMonsterCollectionReward2.cs
- Lib9c/Action/ClaimStakeReward1.cs
- Lib9c/Action/ClaimStakeReward3.cs
- Lib9c/Action/ClaimStakeReward4.cs
- Lib9c/Action/ClaimStakeReward5.cs
- Lib9c/Action/ClaimStakeReward6.cs
- Lib9c/Action/ClaimStakeReward7.cs
- Lib9c/Action/ClaimStakeReward8.cs
- Lib9c/Action/Factory/ClaimStakeRewardFactory.cs
- Lib9c/Model/State/StakeState.cs
This reverts commit 4316a99f2ada5c527cf280d22c046204401b614f.
There are codes in [9c-headless](https://github.com/planetarium/NineChronicles.Headless) reliant on this. 😕
> ⏪ Revert "chore: cleanup claim action"

- .Lib9c.Tests/Action/TransferAsset2Test.cs
- .Lib9c.Tests/Action/TransferAsset3Test.cs
- .Lib9c.Tests/Action/TransferAsset4Test.cs
- .Lib9c.Tests/Action/TransferAssetTest0.cs
- .Lib9c.Tests/Action/TransferAssets0Test.cs
- .Lib9c.Tests/Action/TransferAssets2Test.cs
- .Lib9c.Tests/Action/UpdateSell0Test.cs
- .Lib9c.Tests/Action/UpdateSell2Test.cs
- .Lib9c.Tests/Action/UpdateSell3Test.cs
- .Lib9c.Tests/Action/UpdateSell4Test.cs
- Lib9c/Action/TransferAsset2.cs
- Lib9c/Action/TransferAsset4.cs
- Lib9c/Action/TransferAssets0.cs
- Lib9c/Action/TransferAssets2.cs
- Lib9c/Action/UpdateSell0.cs
- Lib9c/Action/UpdateSell2.cs
- Lib9c/Action/UpdateSell3.cs
- Lib9c/Action/UpdateSell4.cs
This reverts commit 01c2f81a79ff89f65cf919e76210afd2ab15414c.
Also needed due to reliance from [9c-headless](https://github.com/planetarium/NineChronicles.Headless). 😕
> ⏪ Revert "chore: cleanup action"

- Lib9c.Policy/NCStagePolicy.cs
> use concurrent dictionary in stagepolicy

- Lib9c.Policy/NCStagePolicy.cs
> handle-acs-timeout

- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
Validate negative ticket count
---
- https://app.asana.com/0/0/1206261370536137
> Validate ticket count

- README.md
> Add devforum badge to README

- Lib9c.MessagePack/AccountStateDelta.cs
> ⬆️ Bump libplanet to 3.9.3

- .Libplanet.Extensions.RemoteBlockChainStates/HollowTrie.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteAccount.cs
- Lib9c.MessagePack/AccountStateDelta.cs
> ⬆️ [Libplanet 4.0] Bump libplanet to 92e1e9ad8

- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Market.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteBlockChainStates.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
> ⬆️ [Libplanet 4.0] Bump libplanet to 75c958fcb5

- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Model/State/StakeRewardCalculator.cs
prepare to sign the LoadIntoMyGarages with a cold wallet account, we need to be able to pre-calculate the rewards can receive as a reward through the ClaimStakeReward action. so, extract StakeRewardCalculator to make it possible to perform calculations outside of the action.
> Extract StakeRewardCalculator to check rewards outside of action

- .Lib9c.Tests/Action/Common/MockWorldState.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tools/SubCommand/Account.cs
- .Lib9c.Tools/SubCommand/Market.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteWorldState.cs
- Lib9c.Policy/Policy/BlockPolicySource.Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c/Module/AvatarModule.cs
- Lib9c/Module/LegacyModule.cs
- Lib9c/Module/StateResolver.cs
> ⬆️ [Libplanet 4.0] Bump libplanet to 87492af5b

- .Lib9c.Tests/Model/State/AvatarStateTest.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/Quest/QuestList.cs
- Lib9c/Model/State/AgentState.cs
- Lib9c/Model/State/AvatarState.cs
- Lib9c/Model/WorldInformation.cs
NOTE: Implemented by Serialize / Deserialize, which can cause optimization issue.
> Fix clone method to deep copy

- .Lib9c.Tests/Action/Scenario/ArenaScenarioTest.cs
- Lib9c.DevExtensions/Action/CreateArenaDummy.cs
- Lib9c.DevExtensions/Action/Stage/ClearStage.cs
- Lib9c/Action/JoinArena.cs
> Fix mistaken Get / Set

- Lib9c.Policy/NCStagePolicy.cs
Currently applied in v200131-fix regarding ACS quota value updates.
> exception handling in stagepolicy iteration

- .Lib9c.Tests/Action/Garages/DeliverToOthersGaragesTest.cs
- .Lib9c.Tests/Action/Garages/LoadIntoMyGaragesTest.cs
- Lib9c/Action/Garages/LoadIntoMyGarages.cs
- Lib9c/TableCSV/Garages/LoadIntoMyGaragesCostSheet.csv
- following the changes in #2347, Material allow  upload Garage.
> Allow material in garages

- .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
🧹 There is too much clutter in output when building and testing. 🙄
> 🧹 Reduced warnings

- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c.Policy/NCStagePolicy.cs
- Lib9c/Action/BattleArena.cs
> 🔀 [Libplanet 4.0] Merge 1.7.1 into libplanet 4.0

- .Lib9c.DevExtensions.Tests/Action/ManipulateStateTest.cs
🔀 See
- #2358
- #2361
- #2362
- #2363
> 🔀 [Libplanet 4.0] Merge development into libplanet 4.0

- .Lib9c.Tests/Action/ActivateCollectionTest.cs
- .Lib9c.Tests/Model/State/CollectionStateTest.cs
- .Lib9c.Tests/TableData/CollectionSheetTest.cs
- .Lib9c.Tests/TableSheets.cs
- Lib9c/Action/ActivateCollection.cs
- Lib9c/Addresses.cs
- Lib9c/Model/Collection/CollectionFactory.cs
- Lib9c/Model/Collection/FungibleCollectionMaterial.cs
- Lib9c/Model/Collection/ICollectionMaterial.cs
- Lib9c/Model/Collection/MaterialType.cs
- Lib9c/Model/Collection/NonFungibleCollectionMaterial.cs
- Lib9c/Model/Item/Inventory.cs
- Lib9c/Model/State/CollectionState.cs
- Lib9c/Module/CollectionModule.cs
- Lib9c/TableCSV/CollectionSheet.csv
- Lib9c/TableData/CollectionSheet.cs
> Introduce CollectionState, ActivateCollection

- .Lib9c.Tests/Action/Scenario/AuraScenarioTest.cs
- .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
- .Lib9c.Tests/Model/ArenaSimulatorTest.cs
- .Lib9c.Tests/Model/BattleLogTest.cs
- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/RaidSimulatorV3Test.cs
- .Lib9c.Tests/Model/Skill/NormalAttackTest.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- .Lib9c.Tests/Module/CollectionModuleTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/Raid.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Battle/RaidSimulator.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/Stat/CharacterStats.cs
- Lib9c/Module/CollectionModule.cs
- resolve #2366 
- Add & Calculate CollectionStats layer in CharacterStats
- Calculate CollectionStats related actions
> Calculate collection stats

- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/RankingSimulatorTest.cs
- .Lib9c.Tests/Model/RankingSimulatorV1Test.cs
- .Lib9c.Tests/Model/StageSimulatorTest.cs
- .Lib9c.Tests/Model/StageSimulatorV1Test.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/CharacterBase.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/Stat/CharacterStats.cs
resolve #2371 
- Rename OptionStats to CostumeStats
- BuffStats calculate contains CollectionStats, CostumeStats
- BuffStats calculate by operation type(Add, Percentage)
- StatWithItems calculate contains CollectionStats, CostumeStats
> Rebalancing CharacterStats

- .Lib9c.Tests/Battle/CPHelperTest.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/Raid.cs
- Lib9c/Battle/CPHelper.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/Stat/CharacterStats.cs
- Lib9c/TableData/Rune/RuneOptionSheet.cs
> Calculate collection stats cp

- Lib9c/Action/Garages/GarageUtils.cs
- Lib9c/Action/MintAssets.cs
- Lib9c/Action/Stake.cs
- Lib9c/Exceptions/StateNullException.cs
- Lib9c/Module/AvatarModule.cs
> AvatarState ctor returns null for invalid bencoded values

- .Lib9c.Tests/Model/ArenaSimulatorTest.cs
- .Lib9c.Tests/Model/PlayerTest.cs
- .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
- Lib9c/Model/Buff/BuffFactory.cs
- Lib9c/Model/Stat/CharacterStats.cs
- Rename correct name StatWithItems to StatWithoutBuffs
- Update StatWithoutBuffs.HP when IncreaseHpForArena called
> Fix IncreaseHpForArena

- .Lib9c.Tests/Action/Scenario/CollectionScenarioTest.cs
- Lib9c/Action/EventDungeonBattle.cs
Set collection stats modifier in `EventDungeonBattle` action
> Apply missing collection modifier in event dungeon

- .Lib9c.Tests/TableData/CollectionSheetTest.cs
- Lib9c/TableData/CollectionSheet.cs
- skill or buff skill exist if SkillContains true
- skill and buff skill not exist if SkillContains false
> Update collection material check SkillContains

- .Lib9c.Tests/Model/Skill/BuffFactoryTest.cs
- Lib9c/Arena/ArenaSimulator.cs
- Lib9c/Battle/CPHelper.cs
- Lib9c/Battle/RaidSimulator.cs
- Lib9c/Battle/StageSimulator.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/Player.cs
- Lib9c/Model/Stat/CharacterStats.cs
Encapsulates the calculation of character basic stats (equipment, runes, collections) excluding buff.
> Refactor configure character stats

- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c.Policy/NCStagePolicy.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/MaxTransactionsPerSignerPerBlockPolicy.cs
- Lib9c/Action/BuyProduct0.cs
- Lib9c/Action/MigrationAvatarState.cs
- Lib9c/Action/Sell6.cs
- Lib9c/Action/UnlockEquipmentRecipe.cs
- Lib9c/Action/UnlockWorld.cs
> Main merge bypass fee collector

- Lib9c.Policy/Policy/BlockPolicySource.cs
> restore maxtxperblock

- .Lib9c.Tests/Model/Collection/NonFungibleCollectionMaterialTest.cs
- .Lib9c.Tests/Model/Item/InventoryTest.cs
- Lib9c/Action/ActivateCollection.cs
- Lib9c/Model/Collection/NonFungibleCollectionMaterial.cs
- Lib9c/Model/Item/Inventory.cs
- check required block index in `NonFungibleMaterialCollection.BurnMaterial`
> Add block index validation to NonFungibleItem

- .Lib9c.Tests/Model/Skill/Arena/ArenaNormalAttackTest.cs
- Lib9c/Model/Character/ArenaCharacter.cs
Focus skill must work in arena too.
This PR makes focus skill work in arena.
> Make focus skill works in arena

- .Lib9c.Tests/Module/CollectionModuleTest.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Module/CollectionModule.cs
- Use GetAccountState only instead of `GetReservedState`
- GetCollectionStates return Dictionary for matching avatar address
> Refactoring CollectionModule

- .Lib9c.Tests/Model/ArenaSimulatorTest.cs
- .Lib9c.Tests/Model/PlayerTest.cs
- Lib9c/Model/Character/ArenaCharacter.cs
- Lib9c/Model/Character/Player.cs
hotfix for collection modifier doesn't update current hp
> Fix missing update current hp

- Lib9c/Action/AuraSummon.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Model/State/AgentState.cs
Seems it was never properly used. Removing as it takes up unnecessary storage space and brings down performance.
> ♻️ 🧹 Removed `unlockedOptions` from `AgentState`

- .github/workflows/lib9c_plugin_build_and_push_s3.yaml
For ease of S3 bucket migration
> ci: variable Lib9c.Plugin S3 path for GitHub Action

- .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
- .Lib9c.Tests/Model/Skill/CombatTest.cs
Add buff affect test for arena during dispel is on.
> Add dispel affect test for arena

- Lib9c/Action/HackAndSlashSweep.cs
increase ap stone max count 10 > 20
> Increase UsableApStoneCount

- Lib9c.Policy/Policy/BlockPolicySource.cs
For customizing maxtxperblockpolicy using headless parameters.
> customize maxtransactionperblock

- Lib9c.DPoS/Action/Sys/CancelUndelegation.cs
- Lib9c.DPoS/Action/Sys/Delegate.cs
- Lib9c.DPoS/Action/Sys/PromoteValidator.cs
- Lib9c.DPoS/Action/Sys/Redelegate.cs
- Lib9c.DPoS/Action/Sys/Undelegate.cs
- Lib9c.DPoS/Action/Sys/WithdrawDelegator.cs
- Lib9c.DPoS/Action/Sys/WithdrawValidator.cs
> Add the `type_id` value to pos-related actions.

- Lib9c.DPoS.Tests/DistributeTest.cs
- Lib9c.DPoS/Action/DPoSModule.cs
- Lib9c.DPoS/Control/AllocateReward.cs
- Lib9c.DPoS/Control/DelegateCtrl.cs
- Lib9c.DPoS/Control/RedelegateCtrl.cs
- Lib9c.DPoS/Control/UnbondingSetCtrl.cs
- Lib9c.DPoS/Control/UndelegateCtrl.cs
- Lib9c.DPoS/Control/ValidatorCtrl.cs
- Lib9c.DPoS/Control/ValidatorDelegationSetCtrl.cs
- Lib9c.DPoS/Control/ValidatorPowerIndexCtrl.cs
- Lib9c.DPoS/Control/ValidatorRewardsCtrl.cs
- Lib9c.DPoS/Control/ValidatorSetCtrl.cs
- Lib9c.DPoS/Model/Validator.cs
- Lib9c.sln.DotSettings
> Modify Get methods to take `IWorldState`

- .Lib9c.Tests/Action/ActivateCollectionTest.cs
- Lib9c/Action/ActivateCollection.cs
check duplicate collection id unlock case
> Validate collection id already activated

- .Lib9c.Tests/Action/RuneEnhancementTest.cs
- Lib9c/Action/RuneEnhancement.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Model/State/RuneState.cs
- Update TryEnhancement
- Loop for maxTryCount
- Calculates level up result and used costs
- Check balance after enhancement
---
- Can we check balance inside `RuneEnhancement` action, not in `TryEnhancement` helper function?
- Do we calculate total cost correctly?
- Do we have any flaws inside changed `TryEnhancement` helper function?
> Rune multi level up

- .Lib9c.Tests/Action/RegisterProductTest.cs
- Lib9c/Action/AssetInfo.cs
- Lib9c/Action/RegisterProduct.cs
- Lib9c/Currencies.cs
> Validate fav currency when register product

- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
- Lib9c/Action/RewardGold.cs
- Lib9c/Module/LegacyModule.cs
> ⏪ Revert Libplanet 4.3.0 bump

- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Action/Scenario/MeadScenarioTest.cs
- Lib9c/Action/RewardGold.cs
- Lib9c/Module/LegacyModule.cs
⬆️ Same as Libplanet 4.3.0, only with a downgrade LiteDB (the same as the old version). 🙄
> ⬆️ Bump libplanet to 4.3.1

- .Lib9c.Tests/Action/ValidatorSetOperateTest.cs
- .Libplanet.Extensions.RemoteBlockChainStates/RemoteWorldState.cs
- Lib9c/Action/ValidatorSetOperate.cs
> ⬆️ Bump libplanet to 4.4.1

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Plugin/PluginActionEvaluator.cs
- .Lib9c.Tests/Action/DPoS/DistributeTest.cs
- .Lib9c.Tests/Action/RewardGoldTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/State.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Proposer/Proposer.cs
- Lib9c.Utils/BlockHelper.cs
Bumps to https://github.com/planetarium/libplanet/commit/5cbb2c630450c32c5f72d0be59b4fd8cc4f6be3b
> Bump libplanet for DPoS

- .Lib9c.Tests/Model/QuestListTest.cs
- Lib9c/Model/Quest/CombinationEquipmentQuest.cs
- resolve https://github.com/planetarium/NineChronicles/issues/4808
> Fix CombinationEquipmentQuest deserialize

- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/Raid.cs
- Lib9c/Battle/CPHelper.cs
Apply statCP by rune level bonus
> Apply statCP by rune level bonus

- .Lib9c.Tests/CrystalCalculatorTest.cs
- Lib9c/Action/Grinding.cs
- Lib9c/Helper/CrystalCalculator.cs
- Max level 5 of exponent will be affected
- Total pure crystal from each equipment has limit: 100_000_000
> Add limit of crystal from grinding

- .Lib9c.Tests/Action/DPoS/Control/EvidenceCtrlTest.cs
- .Lib9c.Tests/Action/DPoS/Control/SlashCtrlComplexTest.cs
- .Lib9c.Tests/Action/DPoS/Control/SlashCtrlTest.cs
- .Lib9c.Tests/Action/DPoS/Control/SlashCtrlTestBase.cs
- .Lib9c.Tests/Action/DPoS/Control/ValidatorCtrlTest.cs
- .Lib9c.Tests/Action/DPoS/Control/ValidatorSigningInfoCtrlTest.cs
- .Lib9c.Tests/Action/DPoS/PoSTest.cs
- Lib9c/Action/DPoS/Control/SlashCtrl.cs
- Lib9c/Action/DPoS/Misc/Asset.cs
This PR includes the following.
* Fixed issue where exception is thrown if slash factor is 0.
* Added slashing test code for random NCGs and random delegators.
The reason why I created this PR is to make sure that slashing is working correctly in a variety of situations (such as random NCGs and delegates).
> Add more complex slashing test code with random NCG and delegators.

- Lib9c.Policy/AccessControlService/IAccessControlService.cs
- Lib9c.Policy/NCStagePolicy.cs
Release aimed for v200180 (Merge after v200170 backmerge).
> update acs GetTxQuota Method to async to reduce timeout error

- .Lib9c.Tests/Action/ActionContext.cs
> ⬆️ Bump libplanet to 4.5.0

- Lib9c/Action/AdventureBoss/Wanted.cs
* NOTICE: This contains MVP spec, to this PR should be reviewd after #2571 merged.
---
- Update `wanted` action to final spec.
- This PR has adventure boss data into code, this can be changed.
> Adventure Boss: Wanted

- .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
- Lib9c/Action/AdventureBoss/UnlockFloor.cs
- Lib9c/Model/AdventureBoss/Explorer.cs
Unlock locked floor using NCG or GoldenDust
> Introduce UnlockFloor action

- @planetarium/lib9c/src/actions/claim_items.ts
- @planetarium/lib9c/src/actions/claim_stake_reward.ts
- @planetarium/lib9c/src/actions/common.ts
- @planetarium/lib9c/src/actions/daily_reward.ts
- @planetarium/lib9c/src/actions/deliver_to_others_garages.ts
- @planetarium/lib9c/src/actions/load_into_my_garages.ts
- @planetarium/lib9c/src/actions/stake.ts
- @planetarium/lib9c/src/actions/transfer_asset.ts
- @planetarium/lib9c/src/actions/transfer_assets.ts
- @planetarium/lib9c/src/index.ts
- @planetarium/lib9c/src/models/currencies.ts
- @planetarium/lib9c/src/models/hashdigest.ts
- @planetarium/lib9c/src/models/networks.ts
> Document @planetarium/lib9c

- Lib9c/Action/RegisterProduct.cs
- Lib9c/Currencies.cs
- resolve https://github.com/planetarium/NineChronicles/issues/4994
> Add non tradable runes

- .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
- Lib9c/Helper/AdventureBossHelper.cs
- Remove RaffleReward when `isReal` is false. Only contribution reward will be caclulated.
- Merge raffle reward calculation logic to function.
> Update raffle reward calculation logic

- .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
- Log Breakthrough event only when `logEvent == true`
- Check logs of last stage simulator.
> Update simulator and test

- .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
- .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
- Lib9c/Helper/AdventureBossHelper.cs
- Lib9c/Model/AdventureBoss/BountyBoard.cs
- Lib9c/Module/AdventureBossModule.cs
- 5% of wanted raffle is removed [Reference](https://www.notion.so/planetarium/2024-06-10-9c-a1637638ac2d40b2bb180dcbbf167e69?pvs=4#a5b3152699e347229a05c3ffce7073a8)
> Remove wanted raffle

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tools/SubCommand/State.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Utils/BlockHelper.cs
Bump Libplanet to nightly build for sloth ([prerelease-5.0.0](https://github.com/planetarium/libplanet/tree/5.0.0-alpha%2B1718170149)) and adjust APIs
> Bump Libplanet:sloth

- .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
- .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
- .Lib9c.Tests/Action/AdventureBoss/UnlockFloorTest.cs
- .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
- Lib9c/Action/AdventureBoss/Wanted.cs
- Lib9c/Model/State/GameConfigState.cs
- Lib9c/TableCSV/GameConfigSheet.csv
Move min. wanted bounty from action const to CSV.
> Move wanted min. bounty from action to CSV

- .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
- Lib9c/Action/AdventureBoss/Wanted.cs
Use latest policy and staking sheet, not old staking sheet
> Check staking required level from latest staking policy

- .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
- .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
- Lib9c/Helper/AdventureBossHelper.cs
> Calculate contribution reward based on point, not used AP potion

- Lib9c/TableCSV/AdventureBoss.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossContributionRewardSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossFloorFirstRewardSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossFloorPointSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossFloorSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossFloorWaveSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossNcgRewardRatioSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossUnlockFloorCostSheet.csv.meta
- Lib9c/TableCSV/AdventureBoss/AdventureBossWantedRewardSheet.csv.meta
어드벤처보스 전용시트 유니티 프로젝트에서 참조 하기 위해 메타데이터 추가했습니다.
> add adventureboss sheet metadata

- .Lib9c.Tests/Action/AdventureBoss/WantedTest.cs
- Lib9c/Action/AdventureBoss/Wanted.cs
- Get rid of multiple season bounty limitation
- Update tests 
- Change check from exception to working
- Update `Stake` test function from old MonsterCollection sheet to latest StakePolcy
> Operator can put bounty for multiple season in a row

- .Lib9c.Tests/TableData/Summon/SummonSheetTest.cs
- Lib9c/TableData/Summon/SummonSheet.cs
> Extend summon recipe limit to 100

- .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
- Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
- Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
Don't use floor (1 ~ 20) for floor identifier
Use floor_id (1 ~ 80) for floor identifier.
All the sheet relations are using floor_id, not floor.
If you use floor, you'll get data only for boss ID 1
> Use FloorId to get floor related data

- .Lib9c.Tests/Helper/AdventureBossHelperTest.cs
- Lib9c/Helper/AdventureBossHelper.cs
To pass address validation in libplanet
> Bugfix/adv boss/season address form hex

- .Lib9c.Tests/Model/AdventureBoss/AdventureBossSimulatorTest.cs
- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
- Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
- Lib9c/Battle/AdventureBoss/AdventureBossSimulator.cs
- Lib9c/Model/BattleStatus/AdventureBoss/Breakthrough.cs
- Lib9c/Model/IStage.cs
- Do not use floor as data
- Make `floorIdList` to create breakthrough events
> Use floorId to add breakthrough event

- .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
- Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
- Lib9c/Action/Exceptions/EmptyRewardException.cs
- Lib9c/Data/AdventureBossGameData.cs
- Lib9c/Helper/AdventureBossHelper.cs
- Iterate season in action, not in helper
- Collect methods does not need context anymore - TransferAsset moved out to action from helper
- Throw an exception when no reward to receive
> Optimize ClaimAdventureBossReward action

- Lib9c.Policy/Policy/BlockPolicySource.cs
This bug prevent `BlockChain` of tip older than sloth bump from appending blocks.
Fix with applying `GetWorldState()` on tip protocol version less than `SlothProtocolVersion`.
> Fix to validate with current WorldState before Sloth

- .Lib9c.Tests/Action/ExceptionTest.cs
- Lib9c/Action/Exceptions/AdventureBoss/AlreadyClaimedException.cs
- Lib9c/Action/Exceptions/AdventureBoss/ClaimExpiredException.cs
- Lib9c/Action/Exceptions/AdventureBoss/InsufficientStakingException.cs
- Lib9c/Action/Exceptions/AdventureBoss/InvalidAdventureBossSeasonException.cs
- Lib9c/Action/Exceptions/AdventureBoss/InvalidBountyException.cs
- Lib9c/Action/Exceptions/AdventureBoss/MaxInvestmentCountExceededException.cs
- Lib9c/Action/Exceptions/AdventureBoss/PreviousBountyException.cs
- Lib9c/Action/Exceptions/AdventureBoss/SeasonInProgressException.cs
- Lib9c/Action/Exceptions/EmptyRewardException.cs
- Avoid SerializationException when MessagePack deserialize exception
> Avoid SerializationException when Exception deserialize

- .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
- Lib9c/Helper/AdventureBossHelper.cs
We've changed the reward calculating logic from round to floor.
> Change reward calculating logic from round to floor

- .Lib9c.Tests/Action/AdventureBoss/ClaimAdventureBossRewardTest.cs
- .Lib9c.Tests/Model/Mail/AdventureBossRaffleWinnerMailTest.cs
- Lib9c/Action/AdventureBoss/ClaimAdventureBossReward.cs
- Lib9c/Model/Mail/AdventureBossRaffleWinnerMail.cs
- Lib9c/Model/Mail/IMail.cs
- Lib9c/Model/Mail/Mail.cs
Add new mail type: `AdventureBossRaffleWinnerMail`
Send mail once when raffle winner is decided.
> Send mail to raffle reward winner

- @planetarium/lib9c/src/actions/create_avatar.ts
- @planetarium/lib9c/tests/actions/create_avatar.test.ts
> feat: introduce `CreateAvatar` action to `@planetarium/lib9c` package

- Lib9c/Action/HackAndSlash.cs
- Lib9c/Lib9c.csproj
* Initial tracing for HAS.
* Don't use Pyroscope package in netstandard2.1 framework due to compatibility issue.
Note) https://github.com/planetarium/libplanet/commit/31039424f78e5e34ec9b0021f95f9f05d9519f54 version of libplanet should be bumped in the next release.
> Add pyroscope tracing

- @planetarium/lib9c/src/index.ts
> re-export CreateAvatar from @planetarium/lib9c

- Lib9c/Model/AdventureBoss/SeasonInfo.cs
> Deserialize long to long

- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Plugin/PluginActionEvaluator.cs
- .Lib9c.Tests/Action/ActionContext.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- .Lib9c.Tools/SubCommand/State.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents.Tests/ActionEvaluationSerializerTest.cs
- .Libplanet.Extensions.ActionEvaluatorCommonComponents/ActionContextMarshaller.cs
- Lib9c.DevExtensions/Utils.cs
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Policy/Policy/NCBlockPolicy.cs
- Lib9c.Renderers/Renderers/ActionRenderer.cs
- Lib9c.Utils/BlockHelper.cs
⬆️
- 트랜젝션 실행 전후 그리고 액션 실행 전후에 지정된 액션을 실행할 수 있는 기능이 추가되었습니다.
- 특정한 SRH 에 특정한 Key-Value 값이 있다는 것을 증명하기 위한 proof 를 생성할 수 있습니다.
- 특정한 SRH 에 특정한 Key-Value 값이 있다는 것을 proof 를 통해 증명할 수 있습니다.
> ⬆️ Bump libplanet to 5.2.0

- .github/workflows/publish.yml
- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- publish Lib9c.MessagePack
- update Lib9c.Abstractions version info
- resolve #2729
> nuget publish Lib9c.MessagePack

- .Lib9c.Benchmarks/.gitignore
- .Lib9c.Benchmarks/Actions/AutoJoinGuild.cs
- .Lib9c.Benchmarks/Actions/MigratePledgeToGuild.cs
- .Lib9c.Benchmarks/Actions/TransferAsset.cs
- .Lib9c.Benchmarks/Lib9c.Benchmarks.csproj
- .Lib9c.Benchmarks/Program.cs
- .Lib9c.Plugin/PluginActionEvaluator.cs
- .Lib9c.Tests/Action/Guild/Migration/GuildMigrationCtrlTest.cs
- .Lib9c.Tests/Action/Guild/Migration/MigratePledgeToGuildTest.cs
- @planetarium/lib9c/src/actions/approve_pledge.ts
- @planetarium/lib9c/src/actions/make_guild.ts
- @planetarium/lib9c/src/actions/migrate_pledge_to_guild.ts
- @planetarium/lib9c/src/index.ts
- @planetarium/lib9c/tests/actions/approve_pledge.test.ts
- @planetarium/lib9c/tests/actions/fixtures.ts
- @planetarium/lib9c/tests/actions/make_guild.test.ts
- @planetarium/lib9c/tests/actions/migrate_pledge_to_guild.test.ts
- Lib9c.Policy/Policy/BlockPolicySource.cs
- Lib9c/Action/Guild/Migration/Controls/GuildMigrationCtrl.cs
- Implement `ApprovePledge`, `MakeGuild`, `MigratePledgeToGuild` actions in lib9c.js
- Remove `AutoJoinGuild` from `PolicyActionsRegistry.beginTxActions` list. (Performance issue)
- Fix a bug that `AutoJoinGuild` and `MigratePledgeToGuild` make users with unapproved pledge contract, join Planetarium guild.
> Some works

- Lib9c/Lib9c.csproj
- Bump Libplanet to 5.2.2
- Set `Lib9c` version to 1.16.1
> Bump Libplanet to 5.2.2

- Lib9c/Action/DPoS/Control/AllocateRewardCtrl.cs
- Lib9c/Action/DPoS/Control/DelegateCtrl.cs
- Lib9c/Action/DPoS/Control/LumpSumRewardRecordCtrl.cs
- Lib9c/Action/DPoS/Model/LumpSumRewardRecord.cs
> Optimize reward distribution

- .Lib9c.Tests/Action/DPoS/RedelegateTest.cs
- .Lib9c.Tools/Lib9c.Tools.csproj
- Lib9c/Action/DPoS/Control/AllocateRewardCtrl.cs
- Lib9c/Action/DPoS/Control/Bond.cs
- Lib9c/Action/DPoS/Control/DelegateCtrl.cs
- Lib9c/Action/DPoS/Control/LumpSumRewardRecordCtrl.cs
- Lib9c/Action/DPoS/Model/Delegation.cs
- Lib9c/Action/DPoS/WithdrawDelegator.cs
> Fix reward logic

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/MigrateFeeTest.cs
- Lib9c/Action/MigrateFee.cs
- resolve #2704 
- 마이그레이션을 실행할 대상 주소가 정해지면 현재사용되는 액션들의 fee address도 해당 주소로 변경해야합니다.
> Introduce MigrateFee action

- .Lib9c.Tests/Model/Mail/CustomCraftMailTest.cs
- Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
- Lib9c/Model/Mail/CustomCraftMail.cs
- Lib9c/Model/Mail/IMail.cs
- Lib9c/Model/Mail/Mail.cs
- Create CustomCraft type mail
- Change mail type in CustomEquipmentCraft action
> Introduce new mail type: CustomCraft

- Lib9c/Model/State/AllCombinationSlotState.cs
- Lib9c/Model/State/CombinationSlotState.cs
> fix combination slot index on migration

- Lib9c/Action/UnlockCombinationSlot.cs
- Lib9c/Model/State/CombinationSlotState.cs
> fix combination slot lock property

- Lib9c/Action/HackAndSlash.cs
- Fix ActivitySource as a static member
- Fix initial trace activity to be disposed as `Execute` function finished
> Fix HAS tracing

- .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
- Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
all Combination slot을 custom craft에 적용합니다.
> apply allCombinationstate to custom craft

- .Lib9c.Tests/Action/RapidCombinationTest.cs
- .Lib9c.Tests/Action/Scenario/Pet/IncreaseBlockPerHourglassTest.cs
- Lib9c/Action/RapidCombination.cs
all open기능을 추가하기 위해 기존 RapidCombination에서 사용하던 slotIndex를 list형태로 변경하였습니다.
> apply all open action

- Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
- Lib9c/Action/HackAndSlash.cs
Backmerge 1.16.0 to development
> Backmerge 1.16.0

- Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Real block index is way back from expectation
> Change block index to apply new policy

- Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
> Release 1.17.1

- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Renderers/Lib9c.Renderers.csproj
- Lib9c/Lib9c.csproj
> Set version to 1.17.2

- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- Lib9c/Action/HackAndSlashSweep.cs
Resolving [this issue](https://github.com/planetarium/lib9c/security/advisories/GHSA-7j9m-g7jp-jp24)
> Fix with code formatting

- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- Lib9c/Action/HackAndSlashSweep.cs
> Release 1.17.3

- .Lib9c.Tests/Action/ApprovePledgeTest.cs
- Lib9c/Action/ApprovePledge.cs
This pull request adjusts `ApprovePledge` action to join Planetarium's guild automatically when contracting with Planetarium's patron.
> Join Planetarium guild when contracting with Planetarium patron

- .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
- Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Item/ItemFactory.cs
- Lib9c/SerializeKeys.cs
Add following fields:
- bool ByCustomCraft
- bool CraftWithRandom
- bool HasRandomOnlyIcon
> Add new fields into Equipment model

- .config/dotnet-tools.json
- .github/workflows/publish-docs.yml
- docs/README.md
This pull request introduces dotnet [`tool-manifest`](https://learn.microsoft.com/en-us/dotnet/core/tools/local-tools-how-to-use) with some revisions. WIth tool-manifest, it can specify tool's version and manage it with version-control (Git).
> Use dotnet tool-manifest

- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
- Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/Raid.cs
- Lib9c/Helper/AvatarStateExtensions.cs
- Lib9c/Model/State/AvatarState.cs
Returns a list of held items that is created once inside the item validation method, out of the method, so that it can be reused.
> refactor: change return type of some methods

- .Lib9c.Tests/Action/InitializeStatesTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/AllocateRewardTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/DelegateValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/PromoteValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/RedelegateValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/UndelegateValidatorTest.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- .Lib9c.Tests/TestHelper/BlockChainHelper.cs
- Lib9c.Utils/BlockHelper.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Action/ValidatorDelegation/AllocateReward.cs
- Lib9c/Action/ValidatorDelegation/ClaimRewardValidator.cs
- Lib9c/Action/ValidatorDelegation/DelegateValidator.cs
- Lib9c/Action/ValidatorDelegation/PromoteValidator.cs
- Lib9c/Action/ValidatorDelegation/RedelegateValidator.cs
- Lib9c/Action/ValidatorDelegation/ReleaseValidatorUnbondings.cs
- Lib9c/Action/ValidatorDelegation/SlashValidator.cs
- Lib9c/Action/ValidatorDelegation/UndelegateValidator.cs
- Lib9c/Action/ValidatorDelegation/UnjailValidator.cs
- Lib9c/Action/ValidatorDelegation/UpdateValidators.cs
- Lib9c/Delegation/DelegateeMetadata.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
- Lib9c/ValidatorDelegation/ValidatorRepository.cs
- Add initial delegation with Initialize action
- Use NCG as currency for validator delegation [temporal feature]
> Add initial delegation

- Lib9c/Action/UnlockCombinationSlot.cs
optimize unlock combination slot action
remove redundant get state
> optimize unlock combination slot

- .Lib9c.Tests/Action/ValidatorDelegation/AllocateRewardTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/SetValidatorCommissionTest.cs
- Lib9c/Action/ValidatorDelegation/AllocateReward.cs
- Lib9c/Action/ValidatorDelegation/SetValidatorCommission.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
- Lib9c/ValidatorDelegation/ValidatorRepository.cs
> Use custom commission percentage

- Lib9c/Model/Mail/ProductCancelMail.cs
fix mailtype product cancel mail
> fix mailtype product cancel mail

- Lib9c/Action/RapidCombination.cs
optimize rapidcombination action
- remove redundant get state
> optimize rapid combination

- .Lib9c.Tests/Action/ValidatorDelegation/AllocateRewardTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/ClaimRewardValidatorTest.cs
- .Lib9c.Tests/Delegation/DelegateeTest.cs
- .Lib9c.Tests/Delegation/DelegationFixture.cs
- .Lib9c.Tests/Delegation/DelegatorTest.cs
- .Lib9c.Tests/Delegation/DummyDelegatee.cs
- .Lib9c.Tests/Delegation/TestDelegatee.cs
- Lib9c/Delegation/Delegatee.cs
- Lib9c/Delegation/DelegateeMetadata.cs
- Lib9c/Delegation/DelegationAddress.cs
- Lib9c/Delegation/DelegationRepository.cs
- Lib9c/Delegation/IDelegatee.cs
- Lib9c/Delegation/IDelegateeMetadata.cs
- Lib9c/Delegation/IDelegationRepository.cs
- Lib9c/Delegation/LumpSumRewardsRecord.cs
- Lib9c/Model/Guild/Guild.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
> Clear reward remainder

- Lib9c/TableData/AdventureBoss/AdventureBossFloorFirstRewardSheet.cs
Ignore empty placeholder data from CSV in adventure boss reward
> Ignore empty data with throwing exception for missing data

- .Lib9c.Tests/Action/CustomEquipmentCraft/CustomEquipmentCraftTest.cs
- Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
- Lib9c/Helper/CustomCraftHelper.cs
- Move additional cost calculation logic to separated method
- Check additional cost just before move to next group
> Change custom craft additional cost logic

- .Lib9c.Tests/Action/ValidatorDelegation/AllocateRewardTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/ClaimRewardValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/DelegateValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/PromoteValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/RecordProposerTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/RedelegateValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/ReleaseValidatorUnbondingsTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/SlashValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/UndelegateValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/UnjailValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/UpdateValidatorsTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/ValidatorDelegationTestBase.cs
* Converted to file-scoped namespaces to free up space for additional code.
* Some variable names have been shortened as shown below.
* validatorPrivateKey -> validatorKey
* Refactored existing test code for consistency.
> Improve code readability for PoS test

- .Lib9c.Tests/Delegation/DummyDelegatee.cs
- .Lib9c.Tests/Delegation/TestDelegatee.cs
- .Lib9c.Tests/Policy/BlockPolicyTest.cs
- Lib9c/Action/InitializeStates.cs
- Lib9c/Action/ValidatorDelegation/PromoteValidator.cs
- Lib9c/Action/ValidatorDelegation/ReleaseValidatorUnbondings.cs
- Lib9c/Action/ValidatorDelegation/SetValidatorCommission.cs
- Lib9c/Action/ValidatorDelegation/SlashValidator.cs
- Lib9c/Delegation/Delegatee.cs
- Lib9c/Delegation/DelegateeMetadata.cs
- Lib9c/Delegation/IDelegatee.cs
- Lib9c/Delegation/UnbondingEntry.cs
- Lib9c/Delegation/UnbondingSet.cs
- Lib9c/Model/Guild/Guild.cs
- Lib9c/Module/ValidatorDelegation/ValidatorDelegateeModule.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
- Lib9c/ValidatorDelegation/ValidatorRepository.cs
> Fix bugs on delegation

- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Renderers/Lib9c.Renderers.csproj
- Lib9c/Lib9c.csproj
> Prepare 1.19.0

- Lib9c/Action/Guild/AcceptGuildApplication.cs
- Lib9c/Module/Guild/GuildApplicationModule.cs
- Lib9c/Module/Guild/GuildModule.cs
- Lib9c/Module/Guild/GuildParticipantModule.cs
> Clean Guild Modules

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/GrindingTest.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimScenarioTest.cs
- .Lib9c.Tests/Action/Stake0Test.cs
- .Lib9c.Tests/Action/Stake2Test.cs
- .Lib9c.Tests/Action/StakeTest.cs
- .Lib9c.Tests/Action/TransferAssetTest.cs
- .Lib9c.Tests/Action/TransferAssetsTest.cs
- .Lib9c.Tests/Model/Stake/StakeStateTest.cs
- .Lib9c.Tests/Model/Stake/StakeStateUtilsTest.cs
- .Lib9c.Tests/Model/Stake/StakeStateV2Test.cs
- .Lib9c.Tests/Model/State/LegacyStakeStateTest.cs
- Lib9c/Action/ClaimStakeReward.cs
- Lib9c/Action/MigrateMonsterCollection.cs
- Lib9c/Action/Stake.cs
- Lib9c/Action/Stake0.cs
- Lib9c/Action/Stake2.cs
- Lib9c/Action/TransferAsset.cs
- Lib9c/Model/Guild/GuildParticipant.cs
- Lib9c/Model/Stake/StakeState.cs
- Lib9c/Model/Stake/StakeStateUtils.cs
- Lib9c/Model/Stake/StakeStateV2.cs
- Lib9c/Model/State/LegacyStakeState.cs
- Lib9c/Module/LegacyModule.cs
- Mint & Burn GuildCoin when staking
- Migration (Mint GuildCoin) when `Stake` and `ClaimStakeReward`
- @OnedgeLee You can review only 16e228a6559805d6fba38e293b8ab7f58fdba4ca commit. Other commits just renames class names and method names. If you think it is too messy, I'll reopen with the minimum commits.
- @boscohyun It doesn't target to development branch. But you worked  in staking features so I wanted to share these changes to you. If you think you don't have any plan to work for this feature, you can ignore this mention.
> Mint & Burn GuildCoin when staking

- Lib9c/TableCSV/Pet/PetCostSheet.csv
- Lib9c/TableCSV/Pet/PetOptionSheet.csv
- Lib9c/TableCSV/Pet/PetSheet.csv
> update pet data

- Lib9c/Action/ActionBase.cs
@moreal Can you verify this PR now?
> Cleaning Up Code Of ActionBase

- Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
solve https://github.com/advisories/GHSA-4qm4-8hg2-g2xm
> update message pack to 2.5.187

- Lib9c.Policy/Policy/DebugPolicy.cs
> ⬆️ Bump libplanet(dpos-sloth)

- Lib9c/Action/CustomEquipmentCraft/CustomEquipmentCraft.cs
Add option count when new option or skill added
This PR resolves https://github.com/planetarium/NineChronicles/issues/6225
> Add option count

- @planetarium/lib9c/package.json
- @planetarium/lib9c/src/actions/charge_action_point.ts
- @planetarium/lib9c/src/index.ts
- @planetarium/lib9c/tests/actions/charge_action_point.test.ts
> [feat] add action (charge_action_point)

- @planetarium/lib9c/CONTRIBUTING.md
COTRIBUTING.md에서 생략된 설명을 추가했습니다.
> modify COTRIBUTING.md

- integrations/javascript/@planetarium/lib9c/src/actions/grinding.ts
- integrations/javascript/@planetarium/lib9c/src/index.ts
- integrations/javascript/@planetarium/lib9c/tests/actions/grinding.test.ts
close [#2892](https://github.com/planetarium/lib9c/issues/2892)
> feat: implement grinding.ts

- Lib9c.MessagePack/Formatters/ExceptionFormatter.cs
> improve exception messages

- .Lib9c.Tests/Action/ExceptionTest.cs
> test: add `MedalIdNotFoundException` type to unit test

- .github/workflows/validate-github-actions-workflows.yml
> ci: run gh-actions validation every pushing and cron

- .Lib9c.Tests/Action/StakeTest.cs
- Lib9c/Action/Stake.cs
- Lib9c/Action/ValidatorDelegation/ReleaseValidatorUnbondings.cs
- Lib9c/Addresses.cs
- Lib9c/Delegation/UnbondLockIn.cs
> Enable unstaking without a guild

- Lib9c.Utils/BlockHelper.cs
- GoldCurrencyState의 initialSupply를 설정가능하도록 개선합니다. (블록보상으로 NCG를 지급하지않는 경우 제네시스에서 0으로 설정)
> Make NCG initialSupply configurable

- .Lib9c.Tests/Action/EventDungeonBattleTest.cs
- Lib9c/Action/EventDungeonBattle.cs
> Change event dungeon fee address

- .Lib9c.Tests/Action/BuyTest.cs
- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- .Lib9c.Tests/Action/PetEnhancement0Test.cs
- .Lib9c.Tests/Action/RaidTest.cs
- .Lib9c.Tests/Action/Scenario/MarketScenarioTest.cs
- Lib9c/Action/AuraSummon.cs
- Lib9c/Action/BattleArena.cs
- Lib9c/Action/Buy.cs
- Lib9c/Action/BuyProduct.cs
- Lib9c/Action/CombinationEquipment.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/ItemEnhancement.cs
- Lib9c/Action/ItemEnhancement11.cs
- Lib9c/Action/ItemEnhancement12.cs
- Lib9c/Action/ItemEnhancement13.cs
- Lib9c/Action/JoinArena.cs
- Lib9c/Action/JoinArena1.cs
- Lib9c/Action/JoinArena3.cs
- Lib9c/Action/PetEnhancement.cs
- Lib9c/Action/Raid.cs
- Lib9c/Action/RuneEnhancement.cs
- Lib9c/Action/RuneSummon.cs
- Lib9c/Action/UnlockRuneSlot.cs
- Use `Addresses.RewardPool` instead of arena season derive address in action fee.
> Change action fee address to RewardPool

- .Lib9c.Tests/Action/CreatePledgeTest.cs
- Lib9c/Action/CreatePledge.cs
- Fix guild migrations would be missed when contracted via CreatePledge.
> Fix missing guild migration in CreatePledge

- Lib9c.Policy/Policy/MaxTransactionsBytesPolicy.cs
Table CSV size is bigger than 500KiB
> Extend Thor Tx. size to 1MiB

- Lib9c/Model/Stake/StakeState.cs
> Remove obsolete for cancellable block index

- Lib9c/TableCSV/Skill/BuffLimitSheet.csv.meta
- Lib9c/TableCSV/StakeRegularRewardSheet_V9.csv.meta
> 1.20.0 add metafile

- .Lib9c.Tests/Action/Guild/Migration/FixToRefundFromNonValidatorTest.cs
- Lib9c/Action/Guild/Migration/FixToRefundFromNonValidator.cs
> Add admin fix action

- .Lib9c.Tests/Action/Guild/Migration/FixToRefundFromNonValidatorTest.cs
- Lib9c/Action/Guild/Migration/FixToRefundFromNonValidator.cs
> Fix admin action to handle multiple addresses

- .Lib9c.Tests/Action/Guild/Migration/FixToRefundFromNonValidatorTest.cs
- Lib9c/Action/Guild/Migration/FixToRefundFromNonValidator.cs
> Release 1.19.2

- .Lib9c.Tests/Action/DamageHelperTest.cs
- .Lib9c.Tests/Model/CharacterStatsTest.cs
- .Lib9c.Tests/Model/Skill/Adventure/CombatTest.cs
- .Lib9c.Tests/Model/Skill/Arena/ArenaCombatTest.cs
- Lib9c/Battle/DamageHelper.cs
- Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
- Lib9c/Model/Skill/AttackSkill.cs
- Lib9c/TableCSV/Skill/BuffLimitSheet.csv
- Lib9c/TableData/Skill/BuffLimitSheet.cs
> Set Damage Reduction limit

- .Lib9c.Tests/Action/Guild/Migration/FixToRefundFromNonValidatorTest.cs
- Lib9c/Action/Guild/Migration/FixToRefundFromNonValidator.cs
> Backmerge 1.19.3

- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Renderers/Lib9c.Renderers.csproj
- Lib9c/Lib9c.csproj
> chore: configure project versions to `1.20.0`

- .github/workflows/publish.yml
> Add release/* trigger

- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
> fix floor error

- .Lib9c.Miner.Tests/Lib9c.Proposer.Tests.csproj
- .Lib9c.Miner.Tests/ProposerTest.cs
- .Lib9c.Tests/Action/Guild/Migration/MigratePlanetariumValidatorTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/SlashValidatorTest.cs
- Directory.Build.props
- Lib9c.Policy/Policy/DebugPolicy.cs
- Lib9c.Proposer/Proposer.cs
- Lib9c/Action/Guild/Migration/LegacyModels/MigrationModule.cs
- Lib9c/Action/Guild/Migration/MigrateDelegation.cs
- Lib9c/Action/Guild/Migration/MigrateDelegationHeight.cs
- Lib9c/Action/Guild/Migration/MigratePlanetariumValidator.cs
- Lib9c/Action/ValidatorDelegation/SlashValidator.cs
- Lib9c/Delegation/Delegatee.cs
- Lib9c/Model/Guild/GuildDelegatee.cs
- Lib9c/Module/ValidatorDelegation/ValidatorDelegateeModule.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
This PR fixes below problems.
- Add MigratePlanetariumValidator action
- Fix PAEV with upgrade of Libplanet(5.4.1)
- Fix duplicated slashing
- Fix (De)Activation of Validator
- Fix DebugPolicy to use PoS PolicyActionRegistry
- Fix Proposer for single miner to generate votes with power
> Fix PoS related features

- Lib9c/Action/Guild/Migration/GuildMigrationFailedException.cs
- Lib9c/Action/Guild/Migration/LegacyModels/LegacyGuild.cs
- Lib9c/Action/Guild/Migration/LegacyModels/LegacyGuildParticipant.cs
- Lib9c/Action/Guild/Migration/LegacyModels/MigrationModule.cs
- Lib9c/Action/Guild/Migration/MigrateDelegation.cs
- Lib9c/Action/Guild/Migration/MigrateDelegationHeight.cs
- Lib9c/Action/Guild/Migration/MigratePlanetariumGuild.cs
- Lib9c/Action/Guild/Migration/MigratePlanetariumValidator.cs
- Lib9c/ValidatorDelegation/AbstainHistory.cs
This PR fixes below
- Collection iteration during slashing
- Missing docstrings
> Minor fixes, update docstrings

- Lib9c/Action/ClaimItems.cs
> fix duplicate guid NonFungibleItem in Claimitems

- integrations/javascript/@planetarium/lib9c/README.md
- integrations/javascript/@planetarium/lib9c/src/index.ts
- integrations/javascript/@planetarium/lib9c/src/tx.ts
It resolves #2617
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/planetarium/lib9c/pull/3043?shareId=3ca983bf-8c4f-4156-9063-7f74fe6c6df3).
> Add `makeTx` function with `NetworkProvider` interface

- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Renderers/Lib9c.Renderers.csproj
- Lib9c/Action/Guild/Migration/MigrateDelegation.cs
- Lib9c/Lib9c.csproj
- Fix MigrateDelegation action to migrate agents without guild
> Release 1.19.4

- .Lib9c.Tests/Action/ItemEnhancementTest.cs
- Lib9c/Action/ItemEnhancement.cs
- 망치와 재료를 함께 포함시키는 경우 망치 사용이 불가능한 타입이 강화가 되는 버그 수정
> Fix hammer validation

- .Lib9c.Tests/Action/ValidatorDelegation/SetValidatorCommissionTest.cs
- .Lib9c.Tests/Action/ValidatorDelegation/ValidatorDelegationTestBase.cs
- Lib9c/Action/ValidatorDelegation/SetValidatorCommission.cs
Fix an issue where a non-validator can change the commission
> Fix SetValidatorCommission

- integrations/javascript/@planetarium/lib9c/CONTRIBUTING.md
- integrations/javascript/@planetarium/lib9c/package.json
- integrations/javascript/@planetarium/lib9c/src/actions/mint_assets.ts
- integrations/javascript/@planetarium/lib9c/src/index.ts
- integrations/javascript/@planetarium/lib9c/src/models/currencies.ts
- integrations/javascript/@planetarium/lib9c/tests/actions/common.ts
- integrations/javascript/@planetarium/lib9c/tests/actions/mint_assets.test.ts
- integrations/javascript/@planetarium/lib9c/tests/models/currencies.test.ts
- integrations/javascript/@planetarium/pnpm-lock.yaml
It introduces `mint_assets` action (i.e., `MintAssets` in C#).
And it fixes a bug where `fav(currency, quantity)` wasn't to handle FAV with big quantity well.
> feat(js): introduce `mint_assets` action

- .Lib9c.Tests/Action/ValidatorDelegation/SetValidatorCommissionTest.cs
- Lib9c/ValidatorDelegation/ValidatorDelegatee.cs
> Cannot set commission with the same value

- integrations/javascript/@planetarium/lib9c/jsr.json
- integrations/javascript/@planetarium/lib9c/package.json
> chore: prepare lib9c.js 0.5.0

- .Lib9c.Tests/Action/SynthesizeTest.cs
- Lib9c/Action/Synthesize.cs
- Lib9c/Helper/SynthesizeSimulator.cs
유틸 함수 타입을 중복을 허용하지 않는 HashSet으로 바꿉니다
+잘못된 스펙을 변경합니다
> Refactor Synthesize

- .Lib9c.Tests/Action/BattleArenaTest.cs
- Lib9c/Action/BattleArena.cs
Lib9c/Action/BattleArena.csL357#360 부분의 코드를 추가해서, 장착하려는 RuneSlotState가 AllRuneState에서 정상적으로 가져와지는지 validate하는 코드를 추가했습니다.
> validate RuneSlotInfo with AllRuneState at BattleArena

- integrations/javascript/@planetarium/9c-headless-provider/package.json
- integrations/javascript/@planetarium/9c-headless-provider/src/index.ts
- integrations/javascript/@planetarium/pnpm-lock.yaml
> fix(js): avoid confusion between jsr pkg and monorepo pkg

- integrations/javascript/@planetarium/lib9c/src/index.ts
- integrations/javascript/@planetarium/lib9c/tests/actions/hack_and_slash.test.ts
> Fix has export path

- .github/workflows/publish.yml
> Publish Lib9c.Policy project to nuget

- Lib9c/Model/CollectionMap.cs
Fix Typo in `CollectionMap.cs`
Corrected a typo in the `CollectionMap.cs` file to enhance code documentation accuracy.
- **File Modified:** `Lib9c/Model/CollectionMap.cs`
- **Summary of Changes:**  
- Line 61: Corrected the word "serialzed" to "serialized" in the `Justification` attribute.
N/A
- N/A (Documentation update only)
This is a minor typo fix in the documentation within the code. No functional impact expected. Please review to ensure no further corrections are needed.
---
**Allow edits by maintainers:** [x]
> typo fix CollectionMap.cs

- .github/workflows/publish.yml
> Publish Lib9c.Plugin.Shared to nuget package

- .Lib9c.Plugin.Shared/Lib9c.Plugin.Shared.csproj
> Add output path for nuget

- .Lib9c.Tests/Action/BattleTest.cs
- Lib9c/Action/Arena/ArenaProvider.cs
- Lib9c/Action/Arena/Battle.cs
- Lib9c/Action/Battle.cs
- Lib9c/Addresses.cs
- Lib9c/SerializeKeys.cs
https://github.com/planetarium/lib9c/issues/3089
> Introduce battle action [temp]

- .Lib9c.Tests/Action/Guild/MoveGuildTest.cs
- Lib9c/Module/Guild/GuildParticipantModule.cs
> Fix as issure where agent cannot move to other guild

- .Lib9c.Tests/Action/ClaimStakeRewardTest.cs
- .Lib9c.Tests/Action/MigrateMonsterCollectionTest.cs
- .Lib9c.Tests/Action/Scenario/StakeAndClaimScenarioTest.cs
- .Lib9c.Tests/Action/StakeTest.cs
- Lib9c/Action/AdventureBoss/Wanted.cs
- Lib9c/Action/Grinding.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/ItemEnhancement11.cs
- Lib9c/Module/Guild/GuildModule.cs
- Lib9c/Module/LegacyModule.cs
Stake amount의 변화를 반영합니다.
- 기존 : StakeState Address의 NCG Balance값
- 변경 : StakeState의 버전이 2 이하일 경우 기존과 동일, 3 이상일 경우 위임값 + StakeStateAddress의 GuildGold Balance값
> Apply stake changes

- .Lib9c.Tests/Action/Guild/GuildTestBase.cs
- .Lib9c.Tests/Action/Guild/MoveGuildTest.cs
- .Lib9c.Tests/Delegation/DelegateeTest.cs
- .Lib9c.Tests/Delegation/DelegationTestBase.cs
- .Lib9c.Tests/Delegation/GuildDelegateeTest.cs
- .Lib9c.Tests/Delegation/GuildDelegatorTest.cs
- .Lib9c.Tests/Delegation/ValidatorDelegateeTest.cs
- .Lib9c.Tests/Delegation/ValidatorDelegatorTest.cs
- Lib9c/Delegation/DelegateeMetadata.cs
- Lib9c/Delegation/DelegatorMetadata.cs
- Lib9c/Model/Guild/GuildDelegatee.cs
- Lib9c/Model/Guild/GuildDelegator.cs
- Lib9c/Module/Guild/GuildParticipantModule.cs
- Lib9c/ValidatorDelegation/ValidatorDelegator.cs
길드원이 같은 길드로 이동할 수 있는 문제점을 수정하였습니다.
> Fixed an issue where agents could move to the same guild

- Directory.Build.props
> Bump libplanet 5.5.0

- Lib9c/Action/Arena/Battle.cs
> Disable battle action

- Lib9c/Action/Arena/Battle.cs
Reverts planetarium/lib9c#3146
> Revert "Disable battle action"

- .Lib9c.Tests/Action/Guild/QuitGuildTest.cs
길드 나가기 테스트에서 발생하는 테스트를 수정하였습니다.
모듈 자체는 문제가 없고 테스트 코드의 잘못된 부분만 수정하였습니다.
> Fix test failure for guild

- .Lib9c.Tests/Action/Guild/Migration/MigrateStakeAndJoinGuildTest.cs
- Lib9c.Abstractions/Lib9c.Abstractions.csproj
- Lib9c.MessagePack/Lib9c.MessagePack.csproj
- Lib9c.Renderers/Lib9c.Renderers.csproj
- Lib9c/Action/Guild/Migration/LegacyModels/LegacyGuildParticipant.cs
- Lib9c/Action/Guild/Migration/MigrateStakeAndJoinGuild.cs
- Lib9c/Lib9c.csproj
Hotfix
- 제거되었던 길드 / 위임 관련 마이그레이션 액션을 다시 되돌림
- 마이그레이션되지 않은 유저가 확인되었기 때문
> Release 1.22.1

- .Lib9c.Tests/Action/SwapTest.cs
- .Lib9c.Tests/Fixtures/TableCSV/Swap/SwapRateSheetFixtures.cs
- .Lib9c.Tests/Model/Swap/SwapPoolTest.cs
- .Lib9c.Tests/TableData/Swap/SwapRateSheetTest.cs
- .Lib9c.Tests/TableSheets.cs
- Lib9c/Action/Swap.cs
- Lib9c/Addresses.cs
- Lib9c/Delegation/CurrencyComparer.cs
- Lib9c/Delegation/DelegateeMetadata.cs
- Lib9c/Delegation/LumpSumRewardsRecord.cs
- Lib9c/Delegation/RewardBase.cs
- Lib9c/Model/Swap/SwapPool.cs
- Lib9c/TableCSV/Swap/SwapRateSheet.csv
- Lib9c/TableData/Swap/SwapRateSheet.cs
- Lib9c/TableData/TableExtensions.cs
- SwapPool을 통하여 통화간 교환이 가능합니다.
- SwapPool은 Mint/Burn을 하지 않습니다.
- SwapPool에는 현재 고정적으로 자금이 흘러들어가는 출처가 없습니다.
- SwapPool에 충분히 돈을 넣어주고, 이를 통하여 교환을 유도할 수 있습니다.
- SwapPool로부터 출금하는 것은 불가능합니다.
- SwapPool은 SwapRateSheet의 비율을 바탕으로 통화를 교환해 주고, 남는 금액은 요청자에게 되돌려줍니다.
- 현재, Swap액션은 유저 - 스왑풀의 관계이기 때문에, 길드에 Mead를 공급하고 싶을 때에는 유저가 Swap으로 Mead를 얻어서, Guild에게 교환한 Mead를 Transfer해줘야 합니다.
> Introduce SwapPool

- .Lib9c.Tests/Action/AdventureBoss/ExploreAdventureBossTest.cs
- .Lib9c.Tests/Action/AdventureBoss/SweepAdventureBossTest.cs
- .Lib9c.Tests/Action/BattleTest.cs
- .Lib9c.Tests/Action/EventDungeonBattleTest.cs
- .Lib9c.Tests/Action/HackAndSlashSweepTest.cs
- .Lib9c.Tests/Action/HackAndSlashTest.cs
- .Lib9c.Tests/Action/RaidTest.cs
- Lib9c/Action/AdventureBoss/ExploreAdventureBoss.cs
- Lib9c/Action/AdventureBoss/SweepAdventureBoss.cs
- Lib9c/Action/Arena/Battle.cs
- Lib9c/Action/EventDungeonBattle.cs
- Lib9c/Action/HackAndSlash.cs
- Lib9c/Action/HackAndSlashSweep.cs
- Lib9c/Action/Raid.cs
- Lib9c/Addresses.cs
- Lib9c/Helper/RuneHelper.cs
- Lib9c/Model/State/CpState.cs
- Lib9c/Module/AvatarModule.cs
> Introduce cp state

- .Lib9c.Tests/Action/ClaimWorldBossRewardTest.cs
- Lib9c/Action/ClaimWorldBossReward.cs
> Delete send WorldBossRewardMail

- .Lib9c.Tests/Action/ActionEvaluationTest.cs
- .Lib9c.Tests/Action/RemoveAddressStateTest.cs
- .Lib9c.Tests/Action/SetAddressStateTest.cs
- .gitignore
- Lib9c/Action/RemoveAddressState.cs
- Lib9c/Action/SetAddressState.cs
- https://github.com/planetarium/NCIPs/pull/27 의 명세를 구현합니다.
> Introduce RemoveAddressState

- .Lib9c.Tests/Action/PatchTableSheetTest.cs
- .Lib9c.Tests/Action/RemoveAddressStateTest.cs
- .Lib9c.Tests/Action/SetAddressStateTest.cs
- Lib9c/Action/PatchTableSheet.cs
- Lib9c/Action/RemoveAddressState.cs
- Lib9c/Action/SetAddressState.cs
- Remove & Set state action allow patch table operator
> Allow operator

- .Lib9c.Tests/Model/Item/ItemSerializationFormatCompatibilityTest.cs
- .Lib9c.Tests/Model/Item/ItemSerializationMigrationScenarioTest.cs
- .Lib9c.Tests/Model/Stat/DecimalStatSerializationFormatCompatibilityTest.cs
- .Lib9c.Tests/Model/Stat/StatMapSerializationFormatCompatibilityTest.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Item/ItemUsable.cs
- Lib9c/Model/Stat/DecimalStat.cs
- Lib9c/Model/Stat/StatMap.cs
- Lib9c/Model/Stat/StatsMap.cs
- Lib9c/Model/State/StateExtensions.cs
- use List instead of Dictionary when serialize Stat
> Refactor Stat serialize

- .Lib9c.Tests/Helper/NumberConversionHelperTest.cs
- Lib9c/Battle/StageSimulatorV2.cs
- Lib9c/Extensions/SheetsExtensions.cs
- Lib9c/Helper/AdventureBossHelper.cs
- Lib9c/Helper/NumberConversionHelper.cs
- Lib9c/Helper/WorldBossHelper.cs
- Lib9c/Model/Buff/Bleed.cs
- Lib9c/Model/Buff/BuffFactory.cs
- Lib9c/Model/Buff/Vampiric.cs
- Lib9c/Model/Elemental/ElementalType.cs
- Lib9c/Model/Item/Equipment.cs
- Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
- Lib9c/Model/Skill/Arena/ArenaHealSkill.cs
- Lib9c/Model/Skill/AttackSkill.cs
- Lib9c/Model/Skill/HealSkill.cs
Avoid overflow exception when cast numbers
> Introduce NumberConversionHelper

- .Lib9c.Tests/Model/Skill/Arena/ArenaAttackSkillProcessDamageTest.cs
- .Lib9c.Tests/Model/Skill/AttackSkillProcessDamageTest.cs
- Lib9c/Battle/DamageHelper.cs
- Lib9c/Model/Skill/Arena/ArenaAttackSkill.cs
- Lib9c/Model/Skill/AttackSkill.cs
- Increase arena max damage from int.maxValue to long.maxValue
- avoid overflow exception when calculate total damage
> Fix damage overflow case
